"use strict";
(function(){
  if(window.__PN_CLOUD_SYNC_V2__)return;window.__PN_CLOUD_SYNC_V2__=true;
  const URL="https://emnroovdtopxfzwoyhhp.supabase.co";
  const KEY="sb_publishable__tkOfCLkhpkz4BtvSXNQTg_FAmNF3CO";
  const LEDGER_KEY="profitnode_ledger_v1",ROW_ID="primary",SYNC_KEY="profitnode_cloud_sync_v2";
  let client=null,user=null,cloudRevision=0,saveTimer=null,wrapped=false,syncActive=false;
  function localLedger(){try{return JSON.parse(localStorage.getItem(LEDGER_KEY)||"null")}catch(_){return null}}
  function meaningful(x){return !!(x&&((x.projects&&x.projects.length)||(x.inventory&&x.inventory.length)||(x.sales&&x.sales.length)||(x.treasury&&x.treasury.flows&&x.treasury.flows.length)))}
  function fingerprint(x){try{return JSON.stringify(x)}catch(_){return ""}}
  function syncMeta(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||"null")}catch(_){return null}}
  function setMeta(revision,ledger){localStorage.setItem(SYNC_KEY,JSON.stringify({revision:Number(revision)||0,fingerprint:fingerprint(ledger),syncedAt:new Date().toISOString()}))}
  function backupLocal(tag){const raw=localStorage.getItem(LEDGER_KEY);if(!raw)return;const k="profitnode_cloud_backup_"+tag+"_"+new Date().toISOString().replace(/[:.]/g,"-");localStorage.setItem(k,raw)}
  function hasUnsyncedLocal(local){const m=syncMeta();return meaningful(local)&&(!m||m.fingerprint!==fingerprint(local))}
  function shell(){let el=document.getElementById("pn-cloud-gate");if(el)return el;el=document.createElement("div");el.id="pn-cloud-gate";el.innerHTML='<div class="pn-cloud-card"><div class="pn-cloud-kicker">PROFITNODE CLOUD</div><h2>SYNC ACCESS</h2><p id="pn-cloud-msg">Cloud sync is explicit. Sign in, then choose when to sync.</p><input id="pn-cloud-email" type="email" placeholder="Email"><input id="pn-cloud-pass" type="password" placeholder="Password"><div class="pn-cloud-actions"><button id="pn-cloud-signin">SIGN IN</button><button id="pn-cloud-signup">CREATE ACCOUNT</button></div><button id="pn-cloud-local">USE LOCAL ONLY</button></div>';document.body.appendChild(el);return el}
  function message(t,bad){const m=document.getElementById("pn-cloud-msg");if(m){m.textContent=t;m.style.color=bad?"#ff6972":"#c6bbd3"}}
  function closeGate(){const e=document.getElementById("pn-cloud-gate");if(e)e.remove()}
  async function fetchCloud(){const r=await client.from("profitnode_ledger").select("ledger,revision,updated_at,owner_id").eq("id",ROW_ID).eq("owner_id",user.id).maybeSingle();if(r.error)throw r.error;return r.data}
  async function seedCloud(ledger){const r=await client.from("profitnode_ledger").insert({id:ROW_ID,owner_id:user.id,ledger,revision:1,source_device:navigator.userAgent,updated_at:new Date().toISOString()}).select().single();if(r.error)throw r.error;cloudRevision=1;setMeta(1,ledger);return r.data}
  async function saveCloud(){if(!syncActive||!user||typeof Store==="undefined"||!Store.load)return;const ledger=Store.load();if(!meaningful(ledger))return;const remote=await fetchCloud();if(!remote)throw new Error("Cloud row missing. Sync stopped.");const actual=Number(remote.revision)||0;if(actual!==cloudRevision){syncActive=false;throw new Error("Cloud changed since last sync (expected revision "+cloudRevision+", found "+actual+"). Reload/reconcile before saving.")};const next=actual+1;const r=await client.from("profitnode_ledger").update({ledger,revision:next,source_device:navigator.userAgent,updated_at:new Date().toISOString()}).eq("id",ROW_ID).eq("owner_id",user.id).eq("revision",actual).select("revision").maybeSingle();if(r.error)throw r.error;if(!r.data){syncActive=false;throw new Error("Cloud save conflict. Nothing was overwritten.")};cloudRevision=Number(r.data.revision);setMeta(cloudRevision,ledger)}
  function scheduleSave(){if(!syncActive)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCloud().catch(e=>console.error("PROFITNODE CLOUD SAVE STOPPED",e)),500)}
  function wrapPersist(){if(wrapped||typeof Store==="undefined")return;wrapped=true;const old=Store.persist.bind(Store);Store.persist=function(){const ok=old();if(ok)scheduleSave();return ok}}
  function applyRemote(remote){backupLocal("pre-cloud-load");localStorage.setItem(LEDGER_KEY,JSON.stringify(remote.ledger));if(typeof Store!=="undefined"){Store._data=remote.ledger;Store.error=null;Store._writeLocked=false}cloudRevision=Number(remote.revision)||0;setMeta(cloudRevision,remote.ledger);syncActive=true;wrapPersist();closeGate();if(typeof render==="function")render()}
  async function activate(){const local=localLedger(),remote=await fetchCloud();if(!remote){if(!meaningful(local))throw new Error("Cloud is empty and this device has no meaningful local ledger.");if(!confirm("Initialize PROFITNODE cloud from this local ledger?"))return;backupLocal("pre-seed");await seedCloud(local);syncActive=true;wrapPersist();closeGate();return}
    const remoteRev=Number(remote.revision)||0,m=syncMeta();
    if(hasUnsyncedLocal(local)){const choice=confirm("Local PROFITNODE data has changes not known to the last cloud sync.\n\nOK = keep LOCAL and do not overwrite it.\nCancel = review manually.\n\nCloud will NOT be applied automatically.");syncActive=false;if(choice)message("Local changes preserved. Cloud sync remains off until reconciled.",true);return}
    if(m&&Number(m.revision)>remoteRev){syncActive=false;throw new Error("Local sync revision is newer than cloud. Refusing overwrite.")}
    if(!confirm("Load cloud revision "+remoteRev+" and replace this device's current ledger? A backup will be created first.")){syncActive=false;return}
    applyRemote(remote)
  }
  async function signIn(){const email=document.getElementById("pn-cloud-email").value.trim(),password=document.getElementById("pn-cloud-pass").value;message("Signing in...");const r=await client.auth.signInWithPassword({email,password});if(r.error)throw r.error;user=r.data.user;message("Signed in. Cloud has NOT been loaded automatically.");if(confirm("Signed in. Sync with PROFITNODE cloud now?"))await activate()}
  async function signUp(){const email=document.getElementById("pn-cloud-email").value.trim(),password=document.getElementById("pn-cloud-pass").value;message("Creating account...");const r=await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(r.error)throw r.error;if(r.data.session){user=r.data.user;message("Account created. Cloud sync remains off until explicitly activated.")}else message("Account created. Confirm the email, then return here and sign in.")}
  function wireGate(){shell();document.getElementById("pn-cloud-signin").onclick=()=>signIn().catch(e=>message(e.message||String(e),true));document.getElementById("pn-cloud-signup").onclick=()=>signUp().catch(e=>message(e.message||String(e),true));document.getElementById("pn-cloud-local").onclick=()=>{syncActive=false;closeGate();sessionStorage.setItem("pn_cloud_local_only","1")}}
  async function boot(){if(!window.supabase||!window.supabase.createClient){console.error("PROFITNODE CLOUD: Supabase client missing");return}client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const r=await client.auth.getUser();if(r.data&&r.data.user){user=r.data.user;syncActive=false;console.info("PROFITNODE CLOUD: authenticated session found; automatic sync intentionally disabled.")}if(!sessionStorage.getItem("pn_cloud_local_only"))wireGate();client.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){user=null;cloudRevision=0;syncActive=false}else if(session&&session.user){user=session.user;syncActive=false}})}
  const style=document.createElement("style");style.textContent='#pn-cloud-gate{position:fixed;inset:0;z-index:9999;background:rgba(5,3,9,.9);display:grid;place-items:center;padding:20px}.pn-cloud-card{width:min(430px,100%);background:#15111c;border:1px solid #7e22ce;box-shadow:0 0 40px rgba(168,85,247,.25);padding:24px;font-family:IBM Plex Mono,monospace}.pn-cloud-kicker{font-size:10px;letter-spacing:.16em;color:#a855f7}.pn-cloud-card h2{margin:6px 0 8px;font:700 24px Oswald,sans-serif}.pn-cloud-card p{color:#c6bbd3;min-height:34px}.pn-cloud-card input{margin:5px 0}.pn-cloud-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.pn-cloud-card button{background:#261e32;color:#fff;border:1px solid #4a3760;padding:9px;cursor:pointer;font:600 11px Oswald,sans-serif;letter-spacing:.05em}.pn-cloud-card button:hover{border-color:#a855f7}.pn-cloud-card #pn-cloud-local{width:100%;margin-top:8px;color:#a89faf}';document.head.appendChild(style);
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>boot().catch(console.error));else boot().catch(console.error);
})();
