"use strict";
const fs = require('fs');
const path = require('path');
const env = require('./pn_test_env.js');

const DIR = __dirname;
const sandbox = env.createSandbox();

const hardware = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_hardware_ratings_v1.json'), 'utf8'));
const motherboards = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_motherboard_catalog_v1.json'), 'utf8'));
const ram = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_ram_catalog_v1.json'), 'utf8'));
const storage = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_storage_catalog_v1.json'), 'utf8'));
const cases = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_case_catalog_v1.json'), 'utf8'));
const coolers = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_cooler_catalog_v1.json'), 'utf8'));
const gpuPsu = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_gpu_psu_requirements_v1.json'), 'utf8'));

sandbox.canonicalHardware = hardware;
sandbox.canonicalBoards = motherboards;
sandbox.canonicalRam = ram;
sandbox.canonicalStorage = storage;
sandbox.canonicalCases = cases;
sandbox.canonicalCoolers = coolers;
sandbox.canonicalGpuPsu = gpuPsu;

env.loadAll(sandbox, DIR);

const results = env.run(sandbox, `(() => {
  HardwareCatalog.cpus = canonicalHardware.cpus;
  HardwareCatalog.gpus = canonicalHardware.gpus;
  HardwareCatalog.boards = canonicalBoards.boards;
  HardwareCatalog.ramFamilies = canonicalRam.families.map(f=>Object.assign({model:f.series,technology:'DDR4'},f));
  HardwareCatalog.ramSupported = canonicalRam.supported;
  HardwareCatalog.storage = canonicalStorage.entries.map(e=>Object.assign({overall:e.overall_score},e));
  HardwareCatalog.status = 'ready';
  HardwareCatalog.gpuPsuRequirements = canonicalGpuPsu.gpus;
  const out=[];
  out.push(['canonical CPU count is 241', HardwareCatalog.cpus.length===241]);
  out.push(['canonical GPU count is 123', HardwareCatalog.gpus.length===123]);
  out.push(['canonical motherboard count is 935', HardwareCatalog.boards.length===935]);
  out.push(['canonical DDR4 family catalog is loaded', HardwareCatalog.ramFamilies.length>=100]);
  out.push(['canonical storage catalog has 1,324 entries', HardwareCatalog.storage.length===1324]);
  out.push(['storage type counts are preserved', HardwareCatalog.storage.filter(e=>e.drive_type==='NVMe SSD').length===658&&HardwareCatalog.storage.filter(e=>e.drive_type==='SATA SSD').length===462&&HardwareCatalog.storage.filter(e=>e.drive_type==='HDD').length===204]);
  out.push(['storage catalog searches model and capacity', catalogSearch('STORAGE','970 evo plus 1tb').some(e=>e.series.includes('970 EVO Plus')&&e.capacity_gb===1000)]);
  out.push(['RAM catalog searches by brand and series', catalogSearch('RAM','vengeance lpx').some(r=>r.series==='Vengeance LPX')]);
  const anchor=catalogFind('CPU','AMD Ryzen 7 5800X3D');
  out.push(['5800X3D canonical gaming anchor preserved', anchor&&anchor.gaming===100&&anchor.overall===90]);
  out.push(['canonical tier order preserved', PN_GEAR_TIERS.join('>')==='SCRAPBLADE>SCRAPWRAITH>REVENANT>GHOUL>ALGHOUL']);
  out.push(['catalog suggestions wait for 2 characters', catalogSearch('MOBO','B').length===0]);
  out.push(['catalog suggestions are capped at 12', catalogSearch('MOBO','B5').length<=12]);
  out.push(['catalog search matches brand + chipset even with a sub-line name between them', catalogSearch('MOBO','MSI B650').some(b=>b.brand==='MSI'&&b.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['catalogSearchAll matches brand + chipset even with a sub-line name between them', catalogSearchAll('MSI B650').some(m=>m.cat==='MOTHERBOARD'&&m.item.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['catalog search word order does not matter', catalogSearch('MOBO','TOMAHAWK MSI').some(b=>b.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['Deal Score remains a separate 0-10 system', DealScore.auto({purchasePrice:50,estimatedMarketValue:100,condition:'WORKING',category:'GPU'}).score<=10]);
  out.push(['PARTS VAULT visual tiers are a separate five-level system', Object.keys(PN_PART_NAME_TIERS).join('>')==='1>2>3>4>5'&&PN_PART_NAME_TIERS[5].label==='Restrained Gold']);
  out.push(['GPU visual tiers follow the strict category examples', pnPartNameTier({category:'GPU',manufacturer:'NVIDIA',model:'GTX 1070 Hercules'}).key==='T3'&&pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600'}).key==='T4'&&pnPartNameTier({category:'GPU',manufacturer:'NVIDIA',model:'RTX 3080'}).key==='T5']);
  out.push(['CPU visual tiers follow the category examples', pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 5 3600'}).key==='T3'&&pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 5 5600'}).key==='T4'&&pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).key==='T5']);
  out.push(['unknown X570 is not promoted to gold by chipset alone', pnPartNameTier({category:'MOTHERBOARD',manufacturer:'Mystery',model:'X570 Board'}).key==='T3']);
  out.push(['RAM configuration drives category-relative visual tier', pnPartNameTier({category:'RAM',manufacturer:'Kingston',model:'8GB DDR4 single channel'}).key==='T1'&&pnPartNameTier({category:'RAM',manufacturer:'G.Skill',model:'32GB DDR5 6000MHz CL30'}).key==='T5']);
  out.push(['PSU reputation outweighs wattage in visual tiering', pnPartNameTier({category:'PSU',manufacturer:'Generic',model:'1000W PSU'}).key==='T1'&&pnPartNameTier({category:'PSU',manufacturer:'Corsair',model:'RMx 750W'}).key==='T5']);
  out.push(['storage type/capacity and health affect its visual tier', pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING'}).key==='T5'&&pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING',healthPercent:72}).key==='T2']);
  out.push(['zero-percent storage health is preserved as failed media evidence', pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING',driveHealthPercent:0}).key==='T1']);
  out.push(['purchase price never changes the visual tier', pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600',purchasePrice:1}).key===pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600',purchasePrice:999999}).key]);
  const exactCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'});
  const normalizedCatalog=pnPartCatalogResolution({category:'GPU',manufacturer:'NVIDIA',model:'GTX 1070 8GB GDDR5 OC'});
  const manualCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'AMD Ryzen 7 5800X3D'});
  const unresolvedCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'Not a real canonical model'});
  out.push(['catalog matching exposes exact and normalized confidence', exactCatalog.item&&exactCatalog.confidence==='EXACT'&&normalizedCatalog.item&&['NORMALIZED','FAMILY'].includes(normalizedCatalog.confidence)]);
  out.push(['manual catalog override is explicit and deterministic', manualCatalog.item&&manualCatalog.confidence==='MANUAL'&&String(manualCatalog.item.model).includes('5800X3D')]);
  out.push(['unresolved manual override fails safely without invented evidence', !unresolvedCatalog.item&&unresolvedCatalog.confidence==='UNRESOLVED'&&pnPartNameTier({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'Not a real canonical model'}).source==='heuristic']);
  out.push(['tier inspector explains the tier source and exposes advanced correction', pnPartTierExplanationHtml({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).includes('Exact brand and model match')&&pnPartTierExplanationHtml({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).includes('CATALOG LINK / ADVANCED')]);

  function cat(type,label,cost=0){ return {kind:'CATALOG',catalogType:type,label,cost,currency:'RSD'}; }
  function example(cpu,gpu,board){ const r=newRigDraft('FOUNDATION'); r.slots.CPU=cat('CPU',cpu); r.slots.GPU=cat('GPU',gpu); r.slots.MOBO=cat('MOBO',board); r.slots.RAM={kind:'PLANNED',label:'2x8GB DDR4 dual channel',cost:0,currency:'RSD'}; r.slots.PSU={kind:'PLANNED',label:'Corsair 750W',cost:0,currency:'RSD'}; r.slots.STORAGE={kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,currency:'RSD'}; r.slots.COOLER={kind:'PLANNED',label:'Tower cooler',cost:0,currency:'RSD'}; return r; }
  const ex1=rigHardwareProfile(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'));
  const ex2=rigHardwareProfile(example('AMD Ryzen 5 5600','AMD RX 6700 XT 12GB','Gigabyte B550 AORUS MASTER'));
  const ex3=rigHardwareProfile(example('AMD Ryzen 7 5700X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi'));
  const ex4=rigHardwareProfile(example('AMD Ryzen 5 2600','NVIDIA GTX 1070 8GB','MSI B450 TOMAHAWK MAX'));
  const bad=rigHardwareProfile(example('AMD Ryzen 7 5800X3D','AMD RX 580 8GB','MSI B450 TOMAHAWK MAX'));
  out.push(['3600 + RTX 2060 + B450 is REVENANT', ex1.tier==='REVENANT']);
  out.push(['5600 + RX 6700 XT + B550 is GHOUL', ex2.tier==='GHOUL']);
  out.push(['5700X3D + RTX 3080 + X570 is ALGHOUL', ex3.tier==='ALGHOUL']);
  out.push(['2600 + GTX 1070 is REVENANT', ex4.tier==='REVENANT']);
  out.push(['5800X3D + RX 580 is not ALGHOUL', bad.tier!=='ALGHOUL']);
  out.push(['severe CPU/GPU imbalance warning fires', bad.warnings.some(w=>w.includes('Severe CPU/GPU imbalance'))]);
  const editor=renderRigSlotRow('CPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['mode menu no longer exposes PN Hardware Catalog', !editor.includes('PN Hardware Catalog')]);
  out.push(['legacy catalog slots display as Planned Part', editor.includes('<option value="PLANNED" selected>Planned Part</option>')]);
  out.push(['catalog selector uses an automatic results panel', editor.includes('data-rig-catalog-item="CPU"')&&!editor.includes('<datalist')]);
  state.rigDraft = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  state.rigDraft.slots.CPU.label = '3600';
  const searching = renderRigEditor();
  out.push(['typing 3600 immediately renders Ryzen 5 3600', searching.includes('data-rig-catalog-choice="CPU"')&&searching.includes('AMD Ryzen 5 3600')]);
  out.push(['search result separates performance and tier badges', searching.includes('pn-result-rating')&&searching.includes('pn-result-tier pn-tier-revenant')]);
  out.push(['part rating and Gear Tier render separately', editor.includes('pn-meta-pill')&&editor.includes('Performance')&&editor.includes('pn-tier-pill')&&editor.includes('Tier')]);
  out.push(['selected part carries its canonical tier color class', editor.includes('pn-tier-pill pn-tier-revenant')]);
  const ram3200=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16});
  const ram3600=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3600,casLatency:16});
  out.push(['DDR4 true latency formula gives 10ns for 3200 CL16', ram3200.latencyNs===10]);
  out.push(['DDR4 overall formula exposes all five component results', ram3200.capacityScore===75&&ram3200.speedScore===65&&ram3200.latencyScore===80&&ram3200.channelScore===100&&ram3200.overall===78]);
  out.push(['DDR4 3600 CL16 follows canonical formula without brand/RGB bonus', ram3600.overall===84&&ram3600.tier==='GHOUL']);
  const ramRig=newRigDraft('RAM TEST');ramRig.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'Corsair Vengeance LPX',cost:0,originalPrice:0,currency:'RSD',ram:{technology:'DDR4',moduleCount:1,perModuleCapacity:8,totalCapacity:8,speed:2400,casLatency:16}};
  const ramEditor=renderRigSlotRow('RAM',ramRig);
  out.push(['RIG BUILD renders the compact DDR4 configuration fields', ramEditor.includes('data-rig-ram-field="moduleCount"')&&ramEditor.includes('data-rig-ram-field="speed"')&&!ramEditor.includes('data-rig-ram-field="casLatency"')&&!ramEditor.includes('data-rig-ram-field="voltage"')&&!ramEditor.includes('data-rig-ram-field="model"')]);
  const gpuEditor=renderRigSlotRow('GPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['GPU detail omits Raster and RT options', !gpuEditor.includes('Raster')&&!gpuEditor.includes('· RT')]);
  out.push(['user-facing hardware labels spell out PROFITNODE', PNCoreRenderRigEditor.toString().includes('PROFITNODE Rig Performance')&&!PNCoreRenderRigEditor.toString().includes('PN Rig Performance')]);
  out.push(['single-channel and insufficient-capacity RAM warnings fire', rigWarnings(ramRig).some(w=>w.includes('Single-channel'))&&rigWarnings(ramRig).some(w=>w.includes('below 16 GB'))]);
  const am5Cpu=catalogFind('CPU','AMD Ryzen 7 9800X3D');
  out.push(['AM5 9800X3D found in CPU catalog', am5Cpu&&am5Cpu.cores===8&&am5Cpu.threads===16]);
  const am5Board=catalogFind('MOBO','ASUS ROG CROSSHAIR X870E HERO');
  out.push(['AM5 X870E board found in motherboard catalog', am5Board&&am5Board.socket==='AM5'&&am5Board.chipset==='X870E']);
  const b850Board=catalogFind('MOBO','MSI MAG B850 TOMAHAWK WIFI');
  out.push(['AM5 B850 board found in motherboard catalog', b850Board&&b850Board.socket==='AM5'&&b850Board.chipset==='B850']);
  out.push(['detectMoboSocket recognizes AM5 socket', detectMoboSocket('ASUS ROG STRIX X870E-E GAMING WIFI')==='AM5']);
  out.push(['detectMoboSocket recognizes 800-series as AM5', detectMoboSocket('MSI MAG B850 TOMAHAWK MAX WIFI')==='AM5']);
  out.push(['detectMoboSocket recognizes B840 as AM5', detectMoboSocket('ASRock B840M Pro-A WiFi')==='AM5']);
  out.push(['detectMoboPcieGeneration returns Gen5 for AM5 boards', detectMoboPcieGeneration('ASUS ROG CROSSHAIR X870E HERO')===5]);
  out.push(['detectMoboPcieGeneration returns Gen5 for A620', detectMoboPcieGeneration('ASRock A620M-HDV/M.2')===5]);
  const ddr5Family=catalogSearch('RAM','G.Skill Trident Z5');
  out.push(['DDR5 RAM families found via catalog search', ddr5Family.length>0&&ddr5Family[0].technology==='DDR5']);
  const ddr5Kit=HardwareCatalog.ramFamilies.find(f=>f.technology==='DDR5'&&f.kits&&f.kits.length>0);
  out.push(['DDR5 RAM families carry kit data', ddr5Kit&&ddr5Kit.kits[0].capacity>0&&ddr5Kit.kits[0].speed>=4800]);
  out.push(['DDR5 6000 MT/s scores as top-tier in ramRating', ramRating({technology:'DDR5',moduleCount:2,perModuleCapacity:16,totalCapacity:32,speed:6000,casLatency:30}).tier==='ALGHOUL']);
  const am5Build=newRigDraft('AM5 TEST');am5Build.slots.CPU=cat('CPU','AMD Ryzen 7 9800X3D');am5Build.slots.GPU=cat('GPU','NVIDIA RTX 5070 Ti 16GB');am5Build.slots.MOBO=cat('MOBO','ASUS ROG CROSSHAIR X870E HERO');am5Build.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'2x16GB DDR5 6000',cost:0,originalPrice:0,currency:'RSD',ram:{technology:'DDR5',moduleCount:2,perModuleCapacity:16,totalCapacity:32,speed:6000,casLatency:30}};am5Build.slots.PSU=cat('PSU','Corsair RM850x 850W Gold');am5Build.slots.STORAGE=cat('STORAGE','Samsung 990 Pro 2TB NVMe');am5Build.slots.CASE=cat('CASE','Fractal Design Meshify 2');am5Build.slots.COOLER=cat('COOLER','Noctua NH-D15');
  const am5Integrity=rigIntegrity(am5Build);
  out.push(['AM5 build integrity resolves SOUND with DDR5', am5Integrity.state==='SOUND']);
  const am5BuildCheck=buildCheckModel(am5Build);
  out.push(['AM5 build check passes RAM_PLATFORM with DDR5', am5BuildCheck.findings.some(f=>f.id==='RAM_PLATFORM'&&f.status==='PASS')]);
  const am5Profile=rigHardwareProfile(am5Build);
  out.push(['AM5 build profiling succeeds', !!(am5Profile&&am5Profile.complete)]);
  out.push(['AM5 build resolves ALGHOUL tier with RTX 5070 Ti', !!(am5Profile.complete&&am5Profile.tierIndex>=3)]);
  const storageRig=example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  const hdd=HardwareCatalog.storage.find(e=>e.drive_type==='HDD'&&e.capacity_gb===2000),gen4=HardwareCatalog.storage.find(e=>e.drive_type==='NVMe SSD'&&/PCIe 4/.test(e.interface));
  storageRig.slots.STORAGE=cat('STORAGE',hdd.brand+' '+hdd.model);
  storageRig.slots.STORAGE2=cat('STORAGE2',gen4.brand+' '+gen4.model);
  const storageWarnings=rigWarnings(storageRig);
  out.push(['primary and secondary storage slots are distinct', RIG_SLOT_LABELS.STORAGE==='Primary Storage'&&RIG_SLOT_LABELS.STORAGE2==='Storage 2']);
  out.push(['HDD-only primary warning fires', storageWarnings.some(w=>w.includes('HDD-ONLY PRIMARY'))]);
  out.push(['newer NVMe on older platform is compatible but speed limited', storageWarnings.some(w=>w.includes('COMPATIBLE — PCIe SPEED LIMITED'))]);
  const storageEditor=renderRigSlotRow('STORAGE2',storageRig);
  out.push(['secondary storage shows role-specific suitability', storageEditor.includes('Secondary ')&&storageEditor.includes('Bulk ')&&storageEditor.includes('Archive ')]);

  HardwareCatalog.cases = canonicalCases.cases;
  HardwareCatalog.coolers = canonicalCoolers.coolers;
  out.push(['canonical case catalog is loaded with 24 entries', HardwareCatalog.cases.length === 24]);
  out.push(['canonical cooler catalog is loaded with 24 entries', HardwareCatalog.coolers.length === 24]);
  out.push(['case catalog searches brand + model', catalogSearch('CASE','Lancool 216').some(e => e.brand === 'Lian Li' && e.model === 'Lancool 216')]);
  out.push(['cooler catalog searches brand + model', catalogSearch('COOLER','NH-D15').some(e => e.brand === 'Noctua' && e.caps.type === 'DUAL TOWER')]);
  out.push(['cooler and case names receive restrained category-aware tiers', pnPartNameTier({category:'COOLING',manufacturer:'Noctua',model:'NH-D15'}).key==='T5'&&pnPartNameTier({category:'CASE',manufacturer:'Lian Li',model:'Lancool 216'}).key==='T4'&&pnPartNameHtml({category:'COOLING',manufacturer:'Noctua',model:'NH-D15'}).includes('pn-part-name-subtle')]);
  const hydCase = {kind:'PLANNED',catalogType:'CASE',catalogKey:null,label:'Fractal Design Meshify 2',cost:0,currency:'RSD'};
  const hydCC = caseCapabilities(hydCase,'Fractal Design Meshify 2');
  out.push(['case capabilities hydrate from the canonical catalog', hydCC && hydCC.maxGpuLengthMm === 355 && hydCC.airflow === 'EXCELLENT' && hydCase.source === 'CATALOG' && hydCase.catalogKey === 'CASE:FRACTAL DESIGN MESHIFY 2']);
  const encRig = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  encRig.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'NZXT H510',cost:0,currency:'RSD'};
  encRig.slots.COOLER = {kind:'CATALOG',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,currency:'RSD'};
  const caseSlotHtml = renderRigSlotRow('CASE',encRig);
  out.push(['CASE slot renders the enclosure editor', caseSlotHtml.includes('data-rig-generic="CASE"') && caseSlotHtml.includes('data-rig-cap-field="CASE.maxGpuLengthMm"') && caseSlotHtml.includes('data-rig-catalog-item="CASE"')]);
  const coolerSlotHtml = renderRigSlotRow('COOLER',encRig);
  out.push(['COOLER slot renders the compact final component editor', coolerSlotHtml.includes('COOLER DETAILS / ADVANCED') && coolerSlotHtml.includes('data-rig-cap-field="COOLER.coolingClass"') && coolerSlotHtml.includes('data-rig-catalog-item="COOLER"') && coolerSlotHtml.includes('FIT:')]);
  out.push(['COOLER UI omits nonessential technical fields', !/TDP class|Fan count|Noise class|RAM clearance|Heatpipe|Pump speed/i.test(coolerSlotHtml)]);
  out.push(['legacy cooler catalog values normalize to AIR and BASIC/MID/HIGH', (function(){const c=normalizeCoolerCaps({type:'DUAL TOWER',coolingClass:'EXTREME'});return c.type==='AIR'&&c.coolingClass==='HIGH'})()]);

  function cat2(type,label){ return {kind:'CATALOG',catalogType:type,label,cost:0,originalPrice:0,currency:'RSD'}; }
  function goodRig(){
    const r = newRigDraft('INTG');
    r.slots.CPU = cat2('CPU','AMD Ryzen 5 3600');
    r.slots.GPU = cat2('GPU','NVIDIA GTX 1650 4GB GDDR5 280mm');
    r.slots.MOBO = cat2('MOBO','ASRock B450M-HDV');
    r.slots.RAM = {kind:'PLANNED',catalogType:'RAM',label:'DDR4 test kit',cost:0,originalPrice:0,currency:'RSD',ram:{moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16}};
    r.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,originalPrice:0,currency:'RSD'};
    r.slots.COOLER = {kind:'PLANNED',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,originalPrice:0,currency:'RSD',caps:{type:'DUAL TOWER',radiator:null,heightMm:160,sockets:['AM4','AM5','LGA1200','LGA1700'],coolingClass:'EXTREME',fanCount:2,noiseClass:'NORMAL',tdpClass:'EXTREME',ramClearance:'NO',notes:''}};
    r.slots.PSU = cat2('PSU','BeQuiet Pure Power 750W');
    r.slots.STORAGE = {kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,originalPrice:0,currency:'RSD'};
    return r;
  }
  const moboSlotHtml=renderRigSlotRow('MOBO',goodRig());
  out.push(['motherboard slot exposes canonical form, socket and chipset compactly', moboSlotHtml.includes('FORM mATX · SOCKET AM4 · CHIPSET B450')]);
  out.push(['canonical Micro-ATX board fits a case supporting mATX and ATX', rigIntegrity(goodRig()).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='PASS'&&c.detail.includes('mATX motherboard'))]);
  const atxMismatch=goodRig();atxMismatch.slots.MOBO=cat2('MOBO','Gigabyte GA-A320-DS3');atxMismatch.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'mATX-only case',cost:0,originalPrice:0,currency:'RSD',source:'MANUAL',caps:{formFactors:['ITX','MATX']}};
  out.push(['canonical ATX board fails a case limited to mATX', rigIntegrity(atxMismatch).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='FAIL')]);
  const unknownMoboSize=goodRig();unknownMoboSize.slots.MOBO=cat2('MOBO','Mystery Z999M-K');
  out.push(['uncataloged M-style motherboard name remains UNVERIFIED', rigIntegrity(unknownMoboSize).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='UNVERIFIED')]);
  HardwareCatalog.psus = [
    {brand:'BeQuiet',model:'Pure Power 750W',wattage_w:750,quality_score:90,quality_class:'GOLD',safety_status:'ACCEPTABLE',connector_data_confidence:'OFFICIAL',pcie_6_2_connectors:6,pcie_16pin_connectors:0,atx_spec:'ATX'},
    {brand:'Montech',model:'CENTURY 550W',wattage_w:550,quality_score:84,quality_class:'STRONG',safety_status:'APPROVED',connector_data_confidence:'DERIVED',pcie_6_2_connectors:2,pcie_16pin_connectors:0,atx_spec:'ATX 2.52'}
  ];
  const perfectIt = rigIntegrity(goodRig());
  out.push(['fully-characterized build judges BUILD INTEGRITY EXCELLENT', perfectIt.state === 'EXCELLENT']);
  out.push(['EXCELLENT build has every present check PASS or informational', perfectIt.checks.every(c => c.status === 'PASS' || c.status === 'INFO') && perfectIt.checks.filter(c => c.status === 'WARN' || c.status === 'FAIL').length === 0]);
  const socketFail=goodRig();socketFail.slots.COOLER.caps.sockets=['LGA1700'];
  out.push(['incompatible cooler socket is a confirmed FAIL', rigIntegrity(socketFail).checks.some(c=>c.id==='CPU_SOCKET'&&c.status==='FAIL')]);
  const weakCooler=goodRig();weakCooler.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');weakCooler.slots.COOLER.caps.coolingClass='BASIC';
  out.push(['obviously inadequate cooler is a WARNING, not a compatibility FAIL', rigIntegrity(weakCooler).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='WARN')]);
  const noRequiredCooler=goodRig();noRequiredCooler.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');noRequiredCooler.slots.COOLER=null;
  out.push(['missing cooler for a CPU that requires one is a confirmed FAIL', rigIntegrity(noRequiredCooler).checks.some(c=>c.id==='MISSING_COOLER'&&c.status==='FAIL')&&buildCheckModel(noRequiredCooler).verdict==='FAIL']);
  const bundledStock=goodRig();bundledStock.slots.COOLER=null;
  out.push(['adequate bundled stock cooling is accepted without an aftermarket cooler', rigIntegrity(bundledStock).checks.some(c=>c.id==='MISSING_COOLER'&&c.status==='PASS')]);
  const tallAir=goodRig();tallAir.slots.COOLER.caps.heightMm=220;
  out.push(['air cooler over the case height limit is a confirmed FAIL', rigIntegrity(tallAir).checks.some(c=>c.id==='COOLER_HEIGHT'&&c.status==='FAIL')]);
  const badAio=goodRig();badAio.slots.CASE.caps={formFactors:['MATX','ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:180,psuSupport:'ATX',radiator:{front:'240',top:'240',rear:'120'},airflow:'GOOD'};badAio.slots.COOLER.caps={type:'AIO',radiator:'360',heightMm:null,sockets:['AM4'],coolingClass:'HIGH'};
  out.push(['unsupported AIO radiator size is a confirmed FAIL', rigIntegrity(badAio).checks.some(c=>c.id==='RADIATOR_FIT'&&c.status==='FAIL')]);
  const stronger=goodRig();stronger.slots.CPU=cat2('CPU','AMD Ryzen 3 3100');stronger.slots.COOLER.caps.coolingClass='HIGH';
  out.push(['stronger cooling than required passes without warning', rigIntegrity(stronger).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='PASS')&&!rigIntegrity(stronger).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='WARN')]);
  const coolerTierA=goodRig(),coolerTierB=goodRig();coolerTierA.slots.COOLER.caps.coolingClass='BASIC';coolerTierB.slots.COOLER.caps.coolingClass='HIGH';
  out.push(['cooler strength cannot promote rig performance or Gear Tier', rigHardwareProfile(coolerTierA).performance===rigHardwareProfile(coolerTierB).performance&&rigHardwareProfile(coolerTierA).tier===rigHardwareProfile(coolerTierB).tier]);
  const oversized = goodRig();
  oversized.slots.GPU = cat2('GPU','NVIDIA RTX 3080 10GB 500mm');
  const marginalIt = rigIntegrity(oversized);
  out.push(['GPU beyond the case envelope judges MARGINAL with a clearance WARN', marginalIt.state === 'MARGINAL' && marginalIt.checks.some(c => c.id === 'GPU_CLEARANCE' && c.status === 'WARN')]);
  const plain = goodRig();
  plain.slots.CASE = {kind:'PLANNED',label:'Generic steel case',cost:0,originalPrice:0,currency:'RSD'};
  plain.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD'};
  const unknownIt = rigIntegrity(plain);
  out.push(['unknown enclosure stays SOUND — UNKNOWN is never INCOMPATIBLE', unknownIt.state === 'SOUND' && unknownIt.checks.every(c => c.status !== 'WARN')]);
  out.push(['unreadable GPU length grades UNVERIFIED rather than failing the build', unknownIt.checks.find(c => c.id === 'GPU_CLEARANCE').status === 'UNVERIFIED']);
  const dec = example('AMD Ryzen 7 5800X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi');
  const perfBefore = rigHardwareProfile(dec).performance;
  dec.slots.CASE = {kind:'PLANNED',label:'NZXT H510',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:160,psuSupport:'ATX',radiator:{front:'none',top:'240',rear:'none'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'steel',notes:''}};
  dec.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD',caps:{type:'SINGLE TOWER',radiator:null,heightMm:155,sockets:[],coolingClass:'STANDARD',fanCount:1,noiseClass:'NORMAL',tdpClass:'STANDARD',ramClearance:'NO',notes:''}};
  dec.slots.PSU = {kind:'PLANNED',label:'Corsair 750W',cost:0,originalPrice:0,currency:'RSD'};
  out.push(['MARGINAL enclosure profile never changes the CPU/GPU/MOBO performance score', rigHardwareProfile(dec).performance === perfBefore && rigIntegrity(dec).state === 'MARGINAL']);
  out.push(['integrity findings no longer duplicate into rigWarnings', !rigWarnings(oversized).some(w => w.includes('GPU EXCEEDS CASE CLEARANCE'))]);
  const passModel=buildCheckModel(goodRig());
  out.push(['Build Check PASS-only build resolves compatible and completely verified', passModel.verdict==='PASS'&&passModel.compatibility==='PASS'&&passModel.verification==='COMPLETE'&&passModel.counts.PASS>0&&passModel.counts.UNVERIFIED===0&&passModel.counts.WARN===0&&passModel.counts.FAIL===0]);
  const unverifiedModel=buildCheckModel(plain);
  out.push(['Build Check PASS + UNVERIFIED remains compatible but partial', unverifiedModel.verdict==='PASS'&&unverifiedModel.compatibility==='PASS'&&unverifiedModel.verification==='PARTIAL'&&unverifiedModel.counts.PASS>0&&unverifiedModel.counts.UNVERIFIED>0&&unverifiedModel.counts.WARN===0&&unverifiedModel.counts.FAIL===0]);
  const warningRig=goodRig();warningRig.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Airflow test case',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['MATX','ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:180,psuSupport:'ATX',radiator:{front:'360',top:'280',rear:'120'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'mesh',notes:''}};
  const warningModel=buildCheckModel(warningRig);
  out.push(['Build Check PASS + WARNING resolves WARNING', warningModel.verdict==='WARNING'&&warningModel.compatibility==='WARNING'&&warningModel.counts.WARN>0&&warningModel.counts.FAIL===0]);
  const failModel=buildCheckModel(oversized);
  out.push(['Build Check confirmed incompatibility resolves FAIL', failModel.verdict==='FAIL'&&failModel.compatibility==='FAIL'&&failModel.counts.FAIL>0]);
  const mixedRig=goodRig();mixedRig.slots.GPU=cat2('GPU','NVIDIA RTX 3080 10GB 500mm');mixedRig.slots.PSU={kind:'PLANNED',catalogType:'PSU',label:'Unknown 750W PSU',cost:0,originalPrice:0,currency:'RSD'};
  const mixedModel=buildCheckModel(mixedRig);
  out.push(['Build Check mixed FAIL + UNVERIFIED stays FAIL', mixedModel.verdict==='FAIL'&&mixedModel.counts.FAIL>0&&mixedModel.counts.UNVERIFIED>0]);
  out.push(['Build Check prevents duplicate messages', new Set(failModel.findings.map(f=>pnNorm(f.id+' '+f.detail))).size===failModel.findings.length]);
  state.rigDraft=oversized;const failHtml=renderBuildCheck();
  out.push(['contradictory severity states stay impossible against a socket-clash build', (function(){const r=goodRig();r.slots.CPU=cat2('CPU','AMD Ryzen 5 7600');r.slots.MOBO=cat2('MOBO','ASRock B550M-HDV');const m=buildCheckModel(r);return m.verdict==='FAIL'&&m.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='FAIL')})()]);
  state.rigDraft=plain;const unverifiedHtml=renderBuildCheck();
  out.push(['PASS/UNVERIFIED Build Check details default collapsed', !/<details class="pn-bc-details" open/.test(unverifiedHtml)]);
  out.push(['Build Check renders compatibility and verification as separate axes', unverifiedHtml.includes('data-build-check-verdict="PASS"')&&unverifiedHtml.includes('data-build-check-verification="PARTIAL"')&&unverifiedHtml.includes('COMPATIBILITY')&&unverifiedHtml.includes('VERIFICATION')]);
  out.push(['case advanced capabilities default collapsed', caseSlotHtml.includes('<summary>CASE CAPABILITIES / ADVANCED</summary>')&&!caseSlotHtml.includes('<details class="pn-cap-details" open>')]);
  const scenarios=[['PASS',goodRig()],['PASS',plain],['WARNING',warningRig],['FAIL',oversized]];
  out.push(['complete Build Check scenario matrix renders the same overall state as its model', scenarios.every(([expected,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck();return model.verdict===expected&&html.includes('data-build-check-verdict="'+expected+'"')} )]);
  out.push(['contradictory Build Check severity states are impossible', scenarios.every(([,rig])=>{const model=buildCheckModel(rig),expected=model.counts.FAIL?'FAIL':model.counts.WARN?'WARNING':(model.counts.PASS||model.counts.INFO)?'PASS':'UNVERIFIED';return model.verdict===expected} )]);
  const clash=goodRig();clash.slots.CPU=cat2('CPU','AMD Ryzen 5 7600');clash.slots.MOBO=cat2('MOBO','ASRock B550M-HDV');
  const clashModel=buildCheckModel(clash);state.rigDraft=clash;const clashHtml=renderBuildCheck();
  out.push(['socket clash is a genuine incompatibility', clashModel.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='FAIL')&&clashModel.verdict==='FAIL']);
  out.push(['socket clash routes into the Build Integrity tile with visible FAIL detail', (function(){const seg=clashHtml.slice(clashHtml.indexOf('data-bc-tile="build-integrity"'),clashHtml.indexOf('data-bc-tile="psu"')),levels=[...seg.matchAll(/data-bc-level="([^"]+)"/g)].map(m=>m[1]);return seg.includes('Build Integrity')&&levels.includes('FAIL')&&clashHtml.includes('motherboard platform')})()]);
  const verdicts=scenarios.map(([,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck(),tileLevels=[...html.matchAll(/pn-bc-chip pn-bc-status(?: is-partial)?" data-bc-level="([^"]+)"/g)].map(m=>m[1]),expected=model.counts.FAIL?'FAIL':model.counts.WARN?'WARNING':(model.counts.PASS||model.counts.INFO)?'PASS':'UNVERIFIED';return tileLevels.length===5&&model.verdict===expected&&(model.counts.FAIL>0)===tileLevels.includes('FAIL')&&(model.counts.WARN>0)===tileLevels.includes('WARN')&&!(!model.counts.FAIL&&!model.counts.WARN)===tileLevels.some(l=>l==='FAIL'||l==='WARN')});
  out.push(['each FAIL/WARN finding lands in exactly one tile and the five tile chips mirror the verdict', verdicts.every(Boolean)&&scenarios.every(([,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck();return model.findings.filter(f=>f.status==='FAIL'||f.status==='WARN').every(f=>html.includes(f.detail))})]);
  const reserve=goodRig();reserve.slots.PSU={kind:'PLANNED',label:'Unknown wattage PSU',cost:0,originalPrice:0,currency:'RSD'};
  const reserveModel=buildCheckModel(reserve);state.rigDraft=reserve;const reserveHtml=renderBuildCheck();
  out.push(['unreadable PSU wattage stays UNVERIFIED and never hard-fails the build', reserveModel.verdict==='PASS'&&reserveModel.counts.UNVERIFIED>0&&reserveModel.counts.FAIL===0&&reserveHtml.includes('UNVERIFIED</span>')]);
  const viable=goodRig();viable.expectedSalePrice=100000;
  const shopStates=[rigOperatorRead(viable,rigDerived(viable),buildCheckModel(viable)).title,rigOperatorRead(plain,rigDerived(plain),buildCheckModel(plain)).title,rigOperatorRead(warningRig,rigDerived(warningRig),buildCheckModel(warningRig)).title,rigOperatorRead(oversized,rigDerived(oversized),buildCheckModel(oversized)).title];
  out.push(['SHOP READ explains good, unknown, warning and incompatible complete states', shopStates.join('|')==='READY TO ASSEMBLE|SET SALE TARGET|REVIEW BEFORE ASSEMBLY|HOLD BUILD']);
  const assembled=JSON.parse(JSON.stringify(viable));assembled.status='ASSEMBLED';const sold=JSON.parse(JSON.stringify(viable));sold.status='SOLD';
  out.push(['SHOP READ covers assembled and sold operational states', rigOperatorRead(assembled,rigDerived(assembled),buildCheckModel(assembled)).title==='SELLING CANDIDATE'&&rigOperatorRead(sold,rigDerived(sold),buildCheckModel(sold)).title==='SALE CLOSED']);
  const valueRig=goodRig();valueRig.id='VALUE';valueRig.status='TEST_BUILD';valueRig.slots.CPU.cost=20000;valueRig.expectedSalePrice=50000;
  const performanceRig=goodRig();performanceRig.id='PERFORMANCE';performanceRig.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');performanceRig.slots.CPU.cost=30000;performanceRig.expectedSalePrice=100000;
  const familyRanks=rigVariantRankings([valueRig,performanceRig]);
  out.push(['family ranking identifies active, cheapest, fastest and best-margin variants', familyRanks.activeId==='VALUE'&&familyRanks.cheapestId==='VALUE'&&familyRanks.fastestId==='PERFORMANCE'&&familyRanks.bestMarginId==='PERFORMANCE']);
  out.push(['family ranking badges expose the decision hierarchy', rigRankBadges(valueRig,familyRanks).includes('ACTIVE')&&rigRankBadges(valueRig,familyRanks).includes('CHEAPEST')&&rigRankBadges(performanceRig,familyRanks).includes('BEST PERFORMANCE')&&rigRankBadges(performanceRig,familyRanks).includes('BEST MARGIN')]);
  const weakRig=goodRig();weakRig.id='WEAK';weakRig.status='TEST_BUILD';weakRig.slots.CPU.cost=20000;weakRig.expectedSalePrice=15000;
  const healthy=goodRig();healthy.id='HEALTHY';healthy.slots.CPU.cost=20000;healthy.expectedSalePrice=120000;
  const recCheck=rigFamilyRecommendation([weakRig,healthy]);
  out.push(['family recommendation skips a weak deal and names the viable variant', !!(recCheck&&recCheck.id==='HEALTHY')]);
  out.push(['family recommendation prefers an assembled selling candidate', (function(){const a=JSON.parse(JSON.stringify(healthy));a.id='ASSEMBLED_BUILD';a.status='ASSEMBLED';const p=goodRig();p.id='PLANNED_HIGHER';p.slots.CPU.cost=20000;p.expectedSalePrice=160000;const r=rigFamilyRecommendation([p,a]);return !!(r&&r.id==='ASSEMBLED_BUILD')})()]);
  out.push(['all-fail family produces no clear assembly candidate', rigFamilyRecommendation([weakRig,JSON.parse(JSON.stringify(weakRig))])===null]);
  out.push(['qualification chips expose the per-variant operational read', rigReadChip(healthy).includes('READY')&&rigReadChip(clash).includes('HOLD')&&rigReadChip(plain).includes('SET TARGET')&&rigReadChip(viable).includes('READY')]);
  const sanity=goodRig();sanity.slots.STORAGE={kind:'PLANNED',catalogType:'STORAGE',label:'Samsung 850 EVO 120GB',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.GPU=cat2('GPU','NVIDIA GTX 1070 8GB');
  sanity.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:10000,originalPrice:0,currency:'RSD'};
  sanity.slots.COOLER={kind:'PLANNED',catalogType:'COOLER',label:'AMD Wraith Stealth',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.PSU={kind:'PLANNED',catalogType:'PSU',label:'Montech Century 550W 80 Plus Gold',cost:7500,originalPrice:0,currency:'RSD'};
  sanity.expectedSalePrice=65000;
  const sanityModel=buildCheckModel(sanity),sanityRead=rigOperatorRead(sanity,rigDerived(sanity),sanityModel);
  out.push(['Ryzen5-3600 / B450M / GTX-1070 / 550W Gold reference build resolves PASS with no warnings and no failures', sanityModel.verdict==='PASS'&&sanityModel.counts.FAIL===0&&sanityModel.counts.WARN===0&&sanityModel.counts.PASS>0]);
  out.push(['the same reference build keeps only unavailable connector inventory unverified', sanityModel.counts.UNVERIFIED===1&&sanityModel.findings.some(f=>f.id==='PSU_CONNECTORS'&&f.status==='UNVERIFIED')]);
  out.push(['uncataloged planned parts complete the platform without breaking compatibility', sanityModel.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='RAM_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='GPU_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='STORAGE_INTERFACE'&&f.status==='PASS')]);
  out.push(['canonical B450M form factor fits the case without name parsing', sanityModel.findings.some(f=>f.id==='MOBO_FORM_FACTOR'&&f.status==='PASS')]);
  out.push(['bundled AMD stock cooling is positively verified, not treated as unknown', sanityModel.findings.some(f=>f.id==='COOLER_SUFFICIENCY'&&f.status==='PASS'&&f.detail.includes('OEM STOCK COOLING'))&&sanityModel.findings.some(f=>f.id==='COOLER_OPERATING_NOTE'&&f.status==='INFO')]);
  out.push(['reference build PSU wattage grades against the real GPU requirement', sanityModel.findings.some(f=>f.id==='PSU_WATTAGE'&&f.status==='PASS'&&f.detail.includes('RECOMMENDED'))]);
  out.push(['PSU checks preserve known capacity, requirement, quality and safety beside unknown connector inventory', ['PSU_CAPACITY','GPU_PSU_BASELINE','PSU_WATTAGE','GPU_CONNECTOR_REQUIREMENT','PSU_QUALITY','PSU_SAFETY'].every(id=>sanityModel.findings.some(f=>f.id===id&&f.status==='PASS'))&&sanityModel.findings.some(f=>f.id==='PSU_CONNECTORS'&&f.status==='UNVERIFIED')]);
  out.push(['generic GTX 1070 envelope verifies comfortable clearance without pretending to know an exact card length', sanityModel.findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='PASS'&&f.detail.includes('generic envelope'))]);
  out.push(['uncataloged planned parts are clear work notes, never operational warnings', sanityModel.counts.WARN===0&&sanityRead.title==='READY TO ASSEMBLE'&&sanityRead.detail.includes('remain unverified')&&sanityRead.tone==='pass'&&rigReadChip(sanity).includes('READY')]);
  state.rigDraft=sanity;const sanityHtml=renderBuildCheck();state.rigDraft=null;
  out.push(['reference build renders a calm Build Check dashboard', sanityHtml.includes('data-build-check-verdict="PASS"')&&!/data-bc-level="(WARN|FAIL)"/.test(sanityHtml)&&sanityHtml.includes('NOTES <b>3</b>')&&!/<details class="pn-bc-details" open/.test(sanityHtml)]);
  out.push(['PSU tile exposes six verified sub-checks and its one honest unknown', sanityHtml.includes('data-bc-tile="psu" data-bc-pass="6" data-bc-unverified="1"')&&sanityHtml.includes('6 PASS / 1 UNVERIFIED')&&sanityHtml.includes('data-bc-finding="PSU_WATTAGE" data-bc-level="PASS"')&&sanityHtml.includes('data-bc-finding="PSU_CONNECTORS" data-bc-level="UNVERIFIED"')]);
  const genericCase=JSON.parse(JSON.stringify(sanity));genericCase.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Generic ATX Airflow Case',genericId:'generic-atx-airflow',cost:0,originalPrice:0,currency:'RSD'};
  const genericCaseModel=buildCheckModel(genericCase);state.rigDraft=genericCase;const genericCaseHtml=renderBuildCheck();state.rigDraft=null;
  out.push(['generic ATX case independently verifies motherboard, cooler and conservative GPU envelope fit', ['MOBO_FORM_FACTOR','COOLER_HEIGHT','GPU_CLEARANCE'].every(id=>genericCaseModel.findings.some(f=>f.id===id&&f.status==='PASS'))&&genericCaseHtml.includes('data-bc-tile="fit" data-bc-pass="3" data-bc-unverified="0"')]);
  const closeGpuCase=JSON.parse(JSON.stringify(genericCase));closeGpuCase.slots.CASE.caps={formFactors:['ITX','MATX','ATX'],maxGpuLengthMm:305,maxCoolerHeightMm:160,psuSupport:'ATX',radiator:{front:'280',top:'240',rear:'120'},airflow:'GOOD'};closeGpuCase.slots.CASE.source='MANUAL';
  out.push(['generic GPU envelope near the case limit requests the exact card model', buildCheckModel(closeGpuCase).findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='UNVERIFIED'&&f.detail.includes('exact card model required'))]);
  const exactGpuCase=JSON.parse(JSON.stringify(closeGpuCase));exactGpuCase.slots.GPU=cat2('GPU','NVIDIA GTX 1070 8GB 320mm');
  out.push(['exact selected-card dimensions override the family envelope and can confirm a clearance failure', buildCheckModel(exactGpuCase).findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='FAIL'&&f.detail.includes('320 mm GPU'))]);
  out.push(['every reference-build finding lands in exactly one tile and cooling never leaks into core integrity', (function(){const sets=bcTileSets(sanityModel.findings),flat=[];Object.keys(sets).forEach(k=>flat.push(...sets[k]));return new Set(flat.map(f=>f.id)).size===flat.length&&flat.length===sanityModel.findings.length&&(sets.cooling||[]).some(f=>f.id==='COOLER_SUFFICIENCY')&&!(sets.integrity||[]).some(f=>f.id==='COOLER_SUFFICIENCY')&&!(sets.integrity||[]).some(f=>/COOLER|COOLING/.test(f.id))})()]);

  const plainTxt=rigExportBuildText(sanity,'plain'),aiTxt=rigExportBuildText(sanity,'ai');
  out.push(['COPY BUILD export carries the build identity, tier, status and completeness', plainTxt.includes('PROFITNODE RIG BUILD EXPORT')&&plainTxt.includes('BUILD NAME: INTG · MAIN')&&plainTxt.includes('BUILD TIER: ')&&plainTxt.includes('BUILD STATUS: PLANNED')&&plainTxt.includes('HARDWARE: COMPLETE')&&plainTxt.includes('SALE READY: NO')]);
  out.push(['COPY BUILD export lists every component and no missing parts', ['CPU:','GPU:','Motherboard:','RAM:','PSU:','Case:','Cooler:','Primary Storage:'].every(s=>plainTxt.includes(s))&&plainTxt.includes('AMD Ryzen 5 3600')&&plainTxt.includes('NVIDIA GTX 1070 8GB')&&plainTxt.includes('MISSING PARTS:')&&plainTxt.includes('  NONE')&&!plainTxt.includes('REVIEW REQUEST')]);
  out.push(['COPY BUILD export embeds both Build Check axes and the shop read', plainTxt.includes('BUILD CHECK:')&&plainTxt.includes('COMPATIBILITY: COMPATIBLE')&&plainTxt.includes('VERIFICATION: PARTIAL')&&plainTxt.includes('COMPATIBLE')&&plainTxt.includes('SHOP READ:')&&plainTxt.includes('READY TO ASSEMBLE')&&plainTxt.includes('NOTES:')]);
  out.push(['COPY FOR AI REVIEW appends the seven-point review request', aiTxt.includes('REVIEW REQUEST:')&&aiTxt.split(String.fromCharCode(10)).filter(l=>/^ {2}[1-7]. /.test(l)).length===7&&aiTxt.includes('1. Rate this build 1-10')&&aiTxt.includes('7. What changes would you make before assembly to maximize resale value?')]);
  out.push(['COPY FOR AI REVIEW adds hardware metadata with honest statuses', aiTxt.includes('Socket: AM4')&&aiTxt.includes('Chipset: B450')&&aiTxt.includes('RAM type: DDR4')&&aiTxt.includes('Wattage: 550 W')&&aiTxt.includes('GPU limit: 355 mm')&&aiTxt.includes('Connectors: 1x8-pin')&&aiTxt.includes('Estimated power: 150 W')&&aiTxt.includes('UNVERIFIED')&&aiTxt.includes('COMPATIBLE')]);
  out.push(['COPY FOR AI REVIEW carries prices and business metrics', aiTxt.includes('PRICES:')&&aiTxt.includes('Total paid:')&&aiTxt.includes('Expected sale price:')&&aiTxt.includes('Expected profit:')&&aiTxt.includes('ROI:')&&aiTxt.includes('Margin:')]);
  const gr=goodRig(),grAi=rigExportBuildText(gr,'ai');
  out.push(['AI export reports catalog-grade PSU, cooler and GPU detail', grAi.includes('Wattage: 750 W')&&grAi.includes('Quality: 90 / 100 GOLD')&&grAi.includes('Type: AIR')&&grAi.includes('Height: 160 mm')&&grAi.includes('Sockets: AM4 / AM5 / LGA1200 / LGA1700')&&grAi.includes('Length: 280 mm')&&grAi.includes('Config: 2x8 GB')&&grAi.includes('Speed: 3200 MT/s')&&grAi.includes('XMP: UNKNOWN')]);
  const bare=newRigDraft('BARE');bare.slots.CPU=cat2('CPU','AMD Ryzen 5 3600');
  const bareTxt=rigExportBuildText(bare,'plain');
  out.push(['incomplete build export flags every missing part and no tier', bareTxt.includes('BUILD TIER: —')&&bareTxt.includes('HARDWARE: INCOMPLETE')&&['- GPU','- Motherboard','- RAM','- PSU','- Case','- Cooler','- Primary Storage'].every(m=>bareTxt.includes(m))&&bareTxt.includes('VIDEO OUTPUT: WARNING')&&bareTxt.includes('REVIEW BEFORE ASSEMBLY')]);
  out.push(['export reflects the live draft, never a canned snapshot', rigExportBuildText(sanity,'plain')!==rigExportBuildText(clash,'plain')&&rigExportBuildText(sanity,'ai')!==rigExportBuildText(sanity,'plain')]);
  out.push(['Build Check head exposes the EXPORT BUILD dropdown with both copy modes', sanityHtml.includes('EXPORT BUILD')&&sanityHtml.includes('pn-bc-export-panel')&&sanityHtml.includes('data-rig-export="plain"')&&sanityHtml.includes('data-rig-export="ai"')&&sanityHtml.includes('COPY BUILD')&&sanityHtml.includes('COPY FOR AI REVIEW')]);
  out.push(['SALE READY flips YES only for an assembled selling candidate', rigExportBuildText(Object.assign({},sanity,{status:'ASSEMBLED'}),'plain').includes('SALE READY: YES')&&rigExportBuildText(Object.assign({},sanity,{status:'SOLD'}),'plain').includes('SALE READY: NO')&&bareTxt.includes('SALE READY: NO')]);
  out.push(['AI export names the exact catalog GPU model when it differs from the label', grAi.includes('Model: GTX 1650 4GB GDDR5')]);
  const invGpu=Store.insert('inventory',{category:'GPU',manufacturer:'MSI',model:'GTX 1650 Ventus',purchasePrice:2300,currency:'RSD',estimatedMarketValue:3400,condition:'FAULTY',status:'IN_STORAGE'});
  const invSsd=Store.insert('inventory',{category:'STORAGE',manufacturer:'Kingston',model:'A400 240GB SATA SSD',purchasePrice:2500,currency:'RSD',estimatedMarketValue:3200,condition:'WORKING',status:'IN_STORAGE',driveHealthPercent:82});
  const invRig=goodRig();invRig.slots.GPU={kind:'INVENTORY',inventoryItemId:invGpu.id};invRig.slots.STORAGE={kind:'INVENTORY',inventoryItemId:invSsd.id};
  const invAi=rigExportBuildText(invRig,'ai');
  out.push(['AI export carries per-part condition only where the ledger tracks it', invAi.includes('Condition: FAULTY')&&invAi.includes('Condition: WORKING')&&!grAi.includes('Condition:')]);
  out.push(['AI export reports case fan configuration from the catalog', invAi.includes('Fans: 2 included · 9 positions')]);
  out.push(['AI export reports storage health only when the ledger tracks it', invAi.includes('Health: 82%')&&!grAi.includes('Health:')]);
  out.push(['warning text is compressed: a note that repeats a build-check detail appears once', (function(){const noStor=goodRig();delete noStor.slots.STORAGE;const t=rigExportBuildText(noStor,'ai');return (t.split('No primary storage selected.').length-1)===1&&t.includes('COMPLETENESS: UNVERIFIED — No primary storage selected.')&&!t.includes('BALANCE & OPERATIONAL NOTES')})()]);
  out.push(['connector uncertainty is not repeated between the PSU/GPU block and Build Check', (invAi.split('No GPU connector baseline available.').length-1)===1&&invAi.includes('  Status: UNVERIFIED')&&!invAi.includes('  Connectors: No GPU connector baseline available.')]);
  out.push(['build-check detail lines stay within a concise length bound', (function(){const NL=String.fromCharCode(10),re=/^  [A-Z0-9 ()&-]+: (COMPATIBLE|WARNING|FAIL|UNVERIFIED|NOTE)( —|$)/;return [aiTxt,grAi,invAi].every(t=>t.split(NL).filter(l=>re.test(l)).every(l=>l.length<=160))})()]);

  HardwareCatalog.cases = [];
  HardwareCatalog.coolers = [];
  const missingCaseCaps = caseCapabilities({kind:'PLANNED',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,currency:'RSD'},'Fractal Design Meshify 2');
  out.push(['missing case catalog degrades to UNVERIFIED, never a hard fail', missingCaseCaps === null && rigIntegrity(plain).state === 'SOUND']);
  return out;
})()`);

let failures=0;
for(const [name, ok] of results){
  console.log((ok ? 'PASS' : 'FAIL') + ' - ' + name);
  if(!ok) failures++;
}
console.log('\n'+(failures===0?'ALL PASSED':failures+' FAILED')+' ('+results.length+' assertions)');
process.exit(failures===0?0:1);
