"use strict";
const fs = require('fs');
const path = require('path');
const env = require('./pn_test_env.js');

const DIR = __dirname;
const sandbox = env.createSandbox();

const hardware = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_hardware_ratings_v1.json'), 'utf8'));
const motherboards = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_motherboard_catalog_v1.json'), 'utf8'));
const ram = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_ram_catalog_v1.json'), 'utf8'));
const storage = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_storage_catalog_v1.json'), 'utf8'));
const cases = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_case_catalog_v1.json'), 'utf8'));
const coolers = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_cooler_catalog_v1.json'), 'utf8'));
const gpuPsu = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_gpu_psu_requirements_v1.json'), 'utf8'));

sandbox.canonicalHardware = hardware;
sandbox.canonicalBoards = motherboards;
sandbox.canonicalRam = ram;
sandbox.canonicalStorage = storage;
sandbox.canonicalCases = cases;
sandbox.canonicalCoolers = coolers;
sandbox.canonicalGpuPsu = gpuPsu;

env.loadAll(sandbox, DIR);

const results = env.run(sandbox, `(() => {
  HardwareCatalog.cpus = canonicalHardware.cpus;
  HardwareCatalog.gpus = canonicalHardware.gpus;
  HardwareCatalog.boards = canonicalBoards.boards;
  HardwareCatalog.ramFamilies = canonicalRam.families.map(f=>Object.assign({model:f.series,technology:'DDR4'},f));
  HardwareCatalog.ramSupported = canonicalRam.supported;
  HardwareCatalog.storage = canonicalStorage.entries.map(e=>Object.assign({overall:e.overall_score},e));
  HardwareCatalog.status = 'ready';
  HardwareCatalog.gpuPsuRequirements = canonicalGpuPsu.gpus;
  const out=[];
  out.push(['canonical CPU count is 221', HardwareCatalog.cpus.length===221]);
  out.push(['canonical GPU count is 123', HardwareCatalog.gpus.length===123]);
  out.push(['canonical motherboard count is 911', HardwareCatalog.boards.length===911]);
  out.push(['canonical DDR4 family catalog is loaded', HardwareCatalog.ramFamilies.length>=90]);
  out.push(['canonical storage catalog has 1,324 entries', HardwareCatalog.storage.length===1324]);
  out.push(['storage type counts are preserved', HardwareCatalog.storage.filter(e=>e.drive_type==='NVMe SSD').length===658&&HardwareCatalog.storage.filter(e=>e.drive_type==='SATA SSD').length===462&&HardwareCatalog.storage.filter(e=>e.drive_type==='HDD').length===204]);
  out.push(['storage catalog searches model and capacity', catalogSearch('STORAGE','970 evo plus 1tb').some(e=>e.series.includes('970 EVO Plus')&&e.capacity_gb===1000)]);
  out.push(['RAM catalog searches by brand and series', catalogSearch('RAM','vengeance lpx').some(r=>r.series==='Vengeance LPX')]);
  const anchor=catalogFind('CPU','AMD Ryzen 7 5800X3D');
  out.push(['5800X3D canonical gaming anchor preserved', anchor&&anchor.gaming===100&&anchor.overall===90]);
  out.push(['canonical tier order preserved', PN_GEAR_TIERS.join('>')==='SCRAPBLADE>SCRAPWRAITH>REVENANT>GHOUL>ALGHOUL']);
  out.push(['catalog suggestions wait for 2 characters', catalogSearch('MOBO','B').length===0]);
  out.push(['catalog suggestions are capped at 12', catalogSearch('MOBO','B5').length<=12]);
  out.push(['Deal Score remains a separate 0-10 system', DealScore.auto({purchasePrice:50,estimatedMarketValue:100,condition:'WORKING',category:'GPU'}).score<=10]);

  function cat(type,label,cost=0){ return {kind:'CATALOG',catalogType:type,label,cost,currency:'RSD'}; }
  function example(cpu,gpu,board){ const r=newRigDraft('FOUNDATION'); r.slots.CPU=cat('CPU',cpu); r.slots.GPU=cat('GPU',gpu); r.slots.MOBO=cat('MOBO',board); r.slots.RAM={kind:'PLANNED',label:'2x8GB DDR4 dual channel',cost:0,currency:'RSD'}; r.slots.PSU={kind:'PLANNED',label:'Corsair 750W',cost:0,currency:'RSD'}; r.slots.STORAGE={kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,currency:'RSD'}; r.slots.COOLER={kind:'PLANNED',label:'Tower cooler',cost:0,currency:'RSD'}; return r; }
  const ex1=rigHardwareProfile(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'));
  const ex2=rigHardwareProfile(example('AMD Ryzen 5 5600','AMD RX 6700 XT 12GB','Gigabyte B550 AORUS MASTER'));
  const ex3=rigHardwareProfile(example('AMD Ryzen 7 5700X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi'));
  const ex4=rigHardwareProfile(example('AMD Ryzen 5 2600','NVIDIA GTX 1070 8GB','MSI B450 TOMAHAWK MAX'));
  const bad=rigHardwareProfile(example('AMD Ryzen 7 5800X3D','AMD RX 580 8GB','MSI B450 TOMAHAWK MAX'));
  out.push(['3600 + RTX 2060 + B450 is REVENANT', ex1.tier==='REVENANT']);
  out.push(['5600 + RX 6700 XT + B550 is GHOUL', ex2.tier==='GHOUL']);
  out.push(['5700X3D + RTX 3080 + X570 is ALGHOUL', ex3.tier==='ALGHOUL']);
  out.push(['2600 + GTX 1070 is REVENANT', ex4.tier==='REVENANT']);
  out.push(['5800X3D + RX 580 is not ALGHOUL', bad.tier!=='ALGHOUL']);
  out.push(['severe CPU/GPU imbalance warning fires', bad.warnings.some(w=>w.includes('Severe CPU/GPU imbalance'))]);
  const editor=renderRigSlotRow('CPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['mode menu no longer exposes PN Hardware Catalog', !editor.includes('PN Hardware Catalog')]);
  out.push(['legacy catalog slots display as Planned Part', editor.includes('<option value="PLANNED" selected>Planned Part</option>')]);
  out.push(['catalog selector uses an automatic results panel', editor.includes('data-rig-catalog-item="CPU"')&&!editor.includes('<datalist')]);
  state.rigDraft = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  state.rigDraft.slots.CPU.label = '3600';
  const searching = renderRigEditor();
  out.push(['typing 3600 immediately renders Ryzen 5 3600', searching.includes('data-rig-catalog-choice="CPU"')&&searching.includes('AMD Ryzen 5 3600')]);
  out.push(['search result separates performance and tier badges', searching.includes('pn-result-rating')&&searching.includes('pn-result-tier pn-tier-revenant')]);
  out.push(['part rating and Gear Tier render separately', editor.includes('pn-meta-pill')&&editor.includes('Performance')&&editor.includes('pn-tier-pill')&&editor.includes('Tier')]);
  out.push(['selected part carries its canonical tier color class', editor.includes('pn-tier-pill pn-tier-revenant')]);
  const ram3200=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16});
  const ram3600=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3600,casLatency:16});
  out.push(['DDR4 true latency formula gives 10ns for 3200 CL16', ram3200.latencyNs===10]);
  out.push(['DDR4 overall formula exposes all five component results', ram3200.capacityScore===75&&ram3200.speedScore===65&&ram3200.latencyScore===80&&ram3200.channelScore===100&&ram3200.overall===78]);
  out.push(['DDR4 3600 CL16 follows canonical formula without brand/RGB bonus', ram3600.overall===84&&ram3600.tier==='GHOUL']);
  const ramRig=newRigDraft('RAM TEST');ramRig.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'Corsair Vengeance LPX',cost:0,originalPrice:0,currency:'RSD',ram:{technology:'DDR4',moduleCount:1,perModuleCapacity:8,totalCapacity:8,speed:2400,casLatency:16}};
  const ramEditor=renderRigSlotRow('RAM',ramRig);
  out.push(['RIG BUILD renders the compact DDR4 configuration fields', ramEditor.includes('data-rig-ram-field="moduleCount"')&&ramEditor.includes('data-rig-ram-field="speed"')&&!ramEditor.includes('data-rig-ram-field="casLatency"')&&!ramEditor.includes('data-rig-ram-field="voltage"')&&!ramEditor.includes('data-rig-ram-field="model"')]);
  const gpuEditor=renderRigSlotRow('GPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['GPU detail omits Raster and RT options', !gpuEditor.includes('Raster')&&!gpuEditor.includes('· RT')]);
  out.push(['user-facing hardware labels spell out PROFITNODE', PNCoreRenderRigEditor.toString().includes('PROFITNODE Rig Performance')&&!PNCoreRenderRigEditor.toString().includes('PN Rig Performance')]);
  out.push(['single-channel and insufficient-capacity RAM warnings fire', rigWarnings(ramRig).some(w=>w.includes('Single-channel'))&&rigWarnings(ramRig).some(w=>w.includes('below 16 GB'))]);
  const storageRig=example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  const hdd=HardwareCatalog.storage.find(e=>e.drive_type==='HDD'&&e.capacity_gb===2000),gen4=HardwareCatalog.storage.find(e=>e.drive_type==='NVMe SSD'&&/PCIe 4/.test(e.interface));
  storageRig.slots.STORAGE=cat('STORAGE',hdd.brand+' '+hdd.model);
  storageRig.slots.STORAGE2=cat('STORAGE2',gen4.brand+' '+gen4.model);
  const storageWarnings=rigWarnings(storageRig);
  out.push(['primary and secondary storage slots are distinct', RIG_SLOT_LABELS.STORAGE==='Primary Storage'&&RIG_SLOT_LABELS.STORAGE2==='Storage 2']);
  out.push(['HDD-only primary warning fires', storageWarnings.some(w=>w.includes('HDD-ONLY PRIMARY'))]);
  out.push(['newer NVMe on older platform is compatible but speed limited', storageWarnings.some(w=>w.includes('COMPATIBLE — PCIe SPEED LIMITED'))]);
  const storageEditor=renderRigSlotRow('STORAGE2',storageRig);
  out.push(['secondary storage shows role-specific suitability', storageEditor.includes('Secondary ')&&storageEditor.includes('Bulk ')&&storageEditor.includes('Archive ')]);

  HardwareCatalog.cases = canonicalCases.cases;
  HardwareCatalog.coolers = canonicalCoolers.coolers;
  out.push(['canonical case catalog is loaded with 24 entries', HardwareCatalog.cases.length === 24]);
  out.push(['canonical cooler catalog is loaded with 24 entries', HardwareCatalog.coolers.length === 24]);
  out.push(['case catalog searches brand + model', catalogSearch('CASE','Lancool 216').some(e => e.brand === 'Lian Li' && e.model === 'Lancool 216')]);
  out.push(['cooler catalog searches brand + model', catalogSearch('COOLER','NH-D15').some(e => e.brand === 'Noctua' && e.caps.type === 'DUAL TOWER')]);
  const hydCase = {kind:'PLANNED',catalogType:'CASE',catalogKey:null,label:'Fractal Design Meshify 2',cost:0,currency:'RSD'};
  const hydCC = caseCapabilities(hydCase,'Fractal Design Meshify 2');
  out.push(['case capabilities hydrate from the canonical catalog', hydCC && hydCC.maxGpuLengthMm === 355 && hydCC.airflow === 'EXCELLENT' && hydCase.source === 'CATALOG' && hydCase.catalogKey === 'CASE:FRACTAL DESIGN MESHIFY 2']);
  const encRig = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  encRig.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'NZXT H510',cost:0,currency:'RSD'};
  encRig.slots.COOLER = {kind:'CATALOG',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,currency:'RSD'};
  const caseSlotHtml = renderRigSlotRow('CASE',encRig);
  out.push(['CASE slot renders the enclosure editor', caseSlotHtml.includes('data-rig-generic="CASE"') && caseSlotHtml.includes('data-rig-cap-field="CASE.maxGpuLengthMm"') && caseSlotHtml.includes('data-rig-catalog-item="CASE"')]);
  const coolerSlotHtml = renderRigSlotRow('COOLER',encRig);
  out.push(['COOLER slot renders the enclosure editor', coolerSlotHtml.includes('data-rig-generic="COOLER"') && coolerSlotHtml.includes('data-rig-cap-field="COOLER.coolingClass"') && coolerSlotHtml.includes('data-rig-catalog-item="COOLER"')]);

  function cat2(type,label){ return {kind:'CATALOG',catalogType:type,label,cost:0,originalPrice:0,currency:'RSD'}; }
  function goodRig(){
    const r = newRigDraft('INTG');
    r.slots.CPU = cat2('CPU','AMD Ryzen 5 3600');
    r.slots.GPU = cat2('GPU','NVIDIA GTX 1650 4GB GDDR5 280mm');
    r.slots.MOBO = cat2('MOBO','ASRock B450M-HDV mATX');
    r.slots.RAM = {kind:'PLANNED',catalogType:'RAM',label:'DDR4 test kit',cost:0,originalPrice:0,currency:'RSD',ram:{moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16}};
    r.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,originalPrice:0,currency:'RSD'};
    r.slots.COOLER = {kind:'PLANNED',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,originalPrice:0,currency:'RSD',caps:{type:'DUAL TOWER',radiator:null,heightMm:160,sockets:['AM4','AM5','LGA1200','LGA1700'],coolingClass:'EXTREME',fanCount:2,noiseClass:'NORMAL',tdpClass:'EXTREME',ramClearance:'NO',notes:''}};
    r.slots.PSU = cat2('PSU','BeQuiet Pure Power 750W');
    r.slots.STORAGE = {kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,originalPrice:0,currency:'RSD'};
    return r;
  }
  HardwareCatalog.psus = [{brand:'BeQuiet',model:'Pure Power 750W',wattage_w:750,quality_score:90,quality_class:'GOLD',safety_status:'ACCEPTABLE',connector_data_confidence:'OFFICIAL',pcie_6_2_connectors:6,pcie_16pin_connectors:0,atx_spec:'ATX'}];
  const perfectIt = rigIntegrity(goodRig());
  out.push(['fully-characterized build judges BUILD INTEGRITY EXCELLENT', perfectIt.state === 'EXCELLENT']);
  out.push(['EXCELLENT build has every present check PASS', perfectIt.checks.every(c => c.status === 'PASS') && perfectIt.warnings.length === 0]);
  const oversized = goodRig();
  oversized.slots.GPU = cat2('GPU','NVIDIA RTX 3080 10GB 500mm');
  const marginalIt = rigIntegrity(oversized);
  out.push(['GPU beyond the case envelope judges MARGINAL with a clearance WARN', marginalIt.state === 'MARGINAL' && marginalIt.checks.some(c => c.id === 'GPU_CLEARANCE' && c.status === 'WARN')]);
  const plain = goodRig();
  plain.slots.CASE = {kind:'PLANNED',label:'Generic steel case',cost:0,originalPrice:0,currency:'RSD'};
  plain.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD'};
  const unknownIt = rigIntegrity(plain);
  out.push(['unknown enclosure stays SOUND — UNKNOWN is never INCOMPATIBLE', unknownIt.state === 'SOUND' && unknownIt.checks.every(c => c.status !== 'WARN')]);
  out.push(['unreadable GPU length grades UNVERIFIED rather than failing the build', unknownIt.checks.find(c => c.id === 'GPU_CLEARANCE').status === 'UNVERIFIED']);
  const dec = example('AMD Ryzen 7 5800X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi');
  const perfBefore = rigHardwareProfile(dec).performance;
  dec.slots.CASE = {kind:'PLANNED',label:'NZXT H510',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:160,psuSupport:'ATX',radiator:{front:'none',top:'240',rear:'none'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'steel',notes:''}};
  dec.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD',caps:{type:'SINGLE TOWER',radiator:null,heightMm:155,sockets:[],coolingClass:'STANDARD',fanCount:1,noiseClass:'NORMAL',tdpClass:'STANDARD',ramClearance:'NO',notes:''}};
  dec.slots.PSU = {kind:'PLANNED',label:'Corsair 750W',cost:0,originalPrice:0,currency:'RSD'};
  out.push(['MARGINAL enclosure profile never changes the CPU/GPU/MOBO performance score', rigHardwareProfile(dec).performance === perfBefore && rigIntegrity(dec).state === 'MARGINAL']);
  out.push(['integrity findings no longer duplicate into rigWarnings', !rigWarnings(oversized).some(w => w.includes('GPU EXCEEDS CASE CLEARANCE'))]);
  const passModel=buildCheckModel(goodRig());
  out.push(['Build Check PASS-only build resolves PASS', passModel.verdict==='PASS'&&passModel.counts.PASS>0&&passModel.counts.UNVERIFIED===0&&passModel.counts.WARN===0&&passModel.counts.FAIL===0]);
  const unverifiedModel=buildCheckModel(plain);
  out.push(['Build Check PASS + UNVERIFIED resolves UNVERIFIED', unverifiedModel.verdict==='UNVERIFIED'&&unverifiedModel.counts.PASS>0&&unverifiedModel.counts.UNVERIFIED>0&&unverifiedModel.counts.FAIL===0]);
  const warningRig=goodRig();warningRig.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Airflow test case',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['MATX','ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:180,psuSupport:'ATX',radiator:{front:'360',top:'280',rear:'120'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'mesh',notes:''}};
  const warningModel=buildCheckModel(warningRig);
  out.push(['Build Check PASS + WARNING resolves WARNING', warningModel.verdict==='WARNING'&&warningModel.counts.WARN>0&&warningModel.counts.FAIL===0]);
  const failModel=buildCheckModel(oversized);
  out.push(['Build Check confirmed incompatibility resolves FAIL', failModel.verdict==='FAIL'&&failModel.counts.FAIL>0]);
  const mixedRig=goodRig();mixedRig.slots.GPU=cat2('GPU','NVIDIA RTX 3080 10GB 500mm');mixedRig.slots.PSU={kind:'PLANNED',catalogType:'PSU',label:'Unknown 750W PSU',cost:0,originalPrice:0,currency:'RSD'};
  const mixedModel=buildCheckModel(mixedRig);
  out.push(['Build Check mixed FAIL + UNVERIFIED stays FAIL', mixedModel.verdict==='FAIL'&&mixedModel.counts.FAIL>0&&mixedModel.counts.UNVERIFIED>0]);
  out.push(['Build Check prevents duplicate messages', new Set(failModel.findings.map(f=>pnNorm(f.id+' '+f.detail))).size===failModel.findings.length]);
  state.rigDraft=oversized;const failHtml=renderBuildCheck();
  out.push(['Build Check tile severity matches FAIL detail severity', failHtml.includes('data-build-check-verdict="FAIL"')&&failHtml.includes('data-bc-level="FAIL"')&&failHtml.includes('is-fail')]);
  state.rigDraft=plain;const unverifiedHtml=renderBuildCheck();
  out.push(['PASS/UNVERIFIED Build Check details default collapsed', !/<details class="pn-bc-details" open/.test(unverifiedHtml)]);
  out.push(['case advanced capabilities default collapsed', caseSlotHtml.includes('<summary>CASE CAPABILITIES / ADVANCED</summary>')&&!caseSlotHtml.includes('<details class="pn-cap-details" open>')]);
  const scenarios=[['PASS',goodRig()],['UNVERIFIED',plain],['WARNING',warningRig],['FAIL',oversized]];
  out.push(['complete Build Check scenario matrix renders the same overall state as its model', scenarios.every(([expected,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck();return model.verdict===expected&&html.includes('data-build-check-verdict="'+expected+'"')} )]);
  out.push(['contradictory Build Check severity states are impossible', scenarios.every(([,rig])=>{const model=buildCheckModel(rig),max=Math.max(...model.findings.map(f=>BC_SEVERITY[bcStatus(f.status)]),0),expected=max===3?'FAIL':max===2?'WARNING':max===1?'UNVERIFIED':'PASS';return model.verdict===expected} )]);
  const viable=goodRig();viable.expectedSalePrice=100000;
  const shopStates=[rigOperatorRead(viable,rigDerived(viable),buildCheckModel(viable)).title,rigOperatorRead(plain,rigDerived(plain),buildCheckModel(plain)).title,rigOperatorRead(warningRig,rigDerived(warningRig),buildCheckModel(warningRig)).title,rigOperatorRead(oversized,rigDerived(oversized),buildCheckModel(oversized)).title];
  out.push(['SHOP READ explains good, unknown, warning and incompatible complete states', shopStates.join('|')==='ASSEMBLY CANDIDATE|VERIFY BEFORE ASSEMBLY|REVIEW BEFORE ASSEMBLY|HOLD BUILD']);
  const assembled=JSON.parse(JSON.stringify(viable));assembled.status='ASSEMBLED';const sold=JSON.parse(JSON.stringify(viable));sold.status='SOLD';
  out.push(['SHOP READ covers assembled and sold operational states', rigOperatorRead(assembled,rigDerived(assembled),buildCheckModel(assembled)).title==='SELLING CANDIDATE'&&rigOperatorRead(sold,rigDerived(sold),buildCheckModel(sold)).title==='SALE CLOSED']);
  const valueRig=goodRig();valueRig.id='VALUE';valueRig.status='TEST_BUILD';valueRig.slots.CPU.cost=20000;valueRig.expectedSalePrice=50000;
  const performanceRig=goodRig();performanceRig.id='PERFORMANCE';performanceRig.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');performanceRig.slots.CPU.cost=30000;performanceRig.expectedSalePrice=100000;
  const familyRanks=rigVariantRankings([valueRig,performanceRig]);
  out.push(['family ranking identifies active, cheapest, fastest and best-margin variants', familyRanks.activeId==='VALUE'&&familyRanks.cheapestId==='VALUE'&&familyRanks.fastestId==='PERFORMANCE'&&familyRanks.bestMarginId==='PERFORMANCE']);
  out.push(['family ranking badges expose the decision hierarchy', rigRankBadges(valueRig,familyRanks).includes('ACTIVE')&&rigRankBadges(valueRig,familyRanks).includes('CHEAPEST')&&rigRankBadges(performanceRig,familyRanks).includes('BEST PERFORMANCE')&&rigRankBadges(performanceRig,familyRanks).includes('BEST MARGIN')]);

  HardwareCatalog.cases = [];
  HardwareCatalog.coolers = [];
  const missingCaseCaps = caseCapabilities({kind:'PLANNED',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,currency:'RSD'},'Fractal Design Meshify 2');
  out.push(['missing case catalog degrades to UNVERIFIED, never a hard fail', missingCaseCaps === null && rigIntegrity(plain).state === 'SOUND']);
  return out;
})()`);

let failures=0;
for(const [name, ok] of results){
  console.log((ok ? 'PASS' : 'FAIL') + ' - ' + name);
  if(!ok) failures++;
}
console.log('\n'+(failures===0?'ALL PASSED':failures+' FAILED')+' ('+results.length+' assertions)');
process.exit(failures===0?0:1);
