"use strict";
const fs = require('fs');
const path = require('path');
const env = require('./pn_test_env.js');

const DIR = __dirname;
const sandbox = env.createSandbox();

const hardware = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_hardware_ratings_v1.json'), 'utf8'));
const motherboards = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_motherboard_catalog_v1.json'), 'utf8'));
const ram = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_ram_catalog_v1.json'), 'utf8'));
const storage = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_storage_catalog_v1.json'), 'utf8'));
const cases = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_case_catalog_v1.json'), 'utf8'));
const coolers = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_cooler_catalog_v1.json'), 'utf8'));
const gpuPsu = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_gpu_psu_requirements_v1.json'), 'utf8'));
const nvmeRegistry = JSON.parse(fs.readFileSync(path.join(DIR, 'profitnode_nvme_registry_v1.json'), 'utf8'));

sandbox.canonicalHardware = hardware;
sandbox.canonicalBoards = motherboards;
sandbox.canonicalRam = ram;
sandbox.canonicalStorage = storage;
sandbox.canonicalCases = cases;
sandbox.canonicalCoolers = coolers;
sandbox.canonicalGpuPsu = gpuPsu;
sandbox.canonicalNvmeRegistry = nvmeRegistry;

env.loadAll(sandbox, DIR);

const results = env.run(sandbox, `(() => {
  function tierName(idx){return idx!=null&&idx>=0?PN_GEAR_TIERS[idx]:null}
  canonicalHardware.cpus = canonicalHardware.cpus.map(c=>{const idx=cpuGearTier(c);return Object.assign({},c,{pn_tier:tierName(idx),pn_tier_index:idx})});
  canonicalHardware.gpus = canonicalHardware.gpus.map(g=>{const idx=gpuGearTier(g);return Object.assign({},g,{pn_tier:tierName(idx),pn_tier_index:idx})});
  canonicalBoards.boards = canonicalBoards.boards.map(b=>{const idx=motherboardGearTier(b);return Object.assign({},b,{pn_tier:tierName(idx),pn_tier_index:idx})});
  canonicalRam.families = canonicalRam.families.map(f=>{const idx=ramRating(f).tierIndex;return Object.assign({model:f.series,technology:'DDR4',pn_tier:PN_GEAR_TIERS[idx],pn_tier_index:idx},f)});
  canonicalStorage.entries = canonicalStorage.entries.map(e=>{const idx=storageGearTier(e);return Object.assign({overall:e.overall_score,pn_tier:tierName(idx),pn_tier_index:idx},e)});
  HardwareCatalog.cpus = canonicalHardware.cpus;
  HardwareCatalog.gpus = canonicalHardware.gpus;
  HardwareCatalog.boards = canonicalBoards.boards;
  HardwareCatalog.ramFamilies = canonicalRam.families.map(f=>Object.assign({model:f.series,technology:'DDR4'},f));
  HardwareCatalog.ramSupported = canonicalRam.supported;
  HardwareCatalog.storage = canonicalStorage.entries.map(e=>Object.assign({overall:e.overall_score},e));
  HardwareCatalog.status = 'ready';
  HardwareCatalog.gpuPsuRequirements = canonicalGpuPsu.gpus;
  const out=[];
  out.push(['canonical CPU count is 279', HardwareCatalog.cpus.length===279]);
  out.push(['canonical GPU count is 208', HardwareCatalog.gpus.length===208]);
  out.push(['canonical motherboard count is 1362 (936 legacy + ASUS + MSI + Gigabyte + ASRock + NZXT + Biostar + Colorful AM5 registries)', HardwareCatalog.boards.length===1362]);
  const tb250=catalogFind('MOBO','Biostar TB250-BTC');
  out.push(['BIOSTAR TB250-BTC is added to the canonical B250 roster as a functional desktop board', tb250&&tb250.brand==='Biostar'&&tb250.model==='TB250-BTC'&&tb250.chipset==='B250'&&tb250.socket==='LGA1151-v1'&&tb250.form_factor==='ATX'&&tb250.overall===49&&PN_GEAR_TIERS[motherboardGearTier(tb250)]==='UNCOMMON']);
  out.push(['BIOSTAR TB250-BTC is not conflated with any TB250 mining-variant submodel', (function(){const all=canonicalBoards.boards.filter(x=>/^TB250/i.test(x.model||''));return all.length===1&&all[0].model==='TB250-BTC'})()]);
  out.push(['BIOSTAR TB250-BTC is findable through motherboard search and lookup', catalogSearch('MOBO','TB250 BTC').some(b=>b.model==='TB250-BTC')&&catalogSearch('MOBO','BIOSTAR TB250').some(b=>b.model==='TB250-BTC')]);
  out.push(['canonical DDR4 family catalog is loaded', HardwareCatalog.ramFamilies.length>=100]);
  out.push(['canonical storage catalog has 1,325 entries', HardwareCatalog.storage.length===1325]);
  out.push(['storage type counts include the canonical PC601 NVMe entry', HardwareCatalog.storage.filter(e=>e.drive_type==='NVMe SSD').length===659&&HardwareCatalog.storage.filter(e=>e.drive_type==='SATA SSD').length===462&&HardwareCatalog.storage.filter(e=>e.drive_type==='HDD').length===204]);
  out.push(['storage catalog searches model and capacity', catalogSearch('STORAGE','970 evo plus 1tb').some(e=>e.series.includes('970 EVO Plus')&&e.capacity_gb===1000)]);
  const pc601Rows=HardwareCatalog.storage.filter(e=>e.series==='PC601');
  const pc601=pc601Rows[0];
  const pc601Aliases=['SK hynix PC601 512GB','PC601 NVMe SK hynix 512GB','SK hynix PC601 HFS512GD9TNG-L2A0A','HFS512GD9TNG-L2A0A','HFS512GD9TNG-L2A0A BA','HFS512GD9TNG','V4RWG','0V4RWG','KR-0V4RWG'];
  out.push(['PC601 uses one canonical 512GB row for exact, suffix and Dell OEM labels', pc601Rows.length===1&&pc601.model==='PC601 512GB'&&pc601.part_number==='HFS512GD9TNG-L2A0A'&&pc601.observed_suffixes.join(',')==='BA'&&pc601.oem_part_numbers.join(',')==='V4RWG,0V4RWG,KR-0V4RWG']);
  out.push(['PC601 keeps exact physical, protocol, NAND and firmware evidence', pc601.capacity_gb===512&&pc601.usable_capacity_gib===476.9&&pc601.drive_type==='NVMe SSD'&&pc601.protocol==='NVMe'&&pc601.interface==='PCIe 3.0 x4'&&pc601.form_factor==='M.2 2280'&&pc601.nand_detail==='3D TLC'&&pc601.dram==='True'&&pc601.firmware==='80002111']);
  out.push(['PC601 storage formula yields score 78 and current EPIC tier', Math.round(.35*pc601.performance_score+.30*pc601.capacity_score+.25*pc601.quality_score+.10*pc601.endurance_score)===78&&pc601.overall_score===78&&pc601.pn_score===78&&pc601.pn_tier==='EPIC'&&pc601.gear_tier==='GHOUL'&&pnTier(storageGearTier(pc601))==='EPIC']);
  out.push(['every required PC601 alias resolves to the same canonical row', pc601Aliases.every(alias=>catalogFind('STORAGE',alias)===pc601)]);
  out.push(['PC601 aliases participate in slot and global catalog search', catalogSearch('STORAGE','Dell V4RWG').includes(pc601)&&catalogSearchAll('HFS512GD9TNG-L2A0A BA').some(m=>m.cat==='STORAGE'&&m.item===pc601)]);
  Store.replaceAll({meta:{seeded:true,schemaVersion:4},inventory:[{id:'pc601-import',category:'STORAGE',manufacturer:'Dell',model:'0V4RWG',purchasePrice:0,currency:'RSD',estimatedMarketValue:0,source:'OTHER',condition:'WORKING',status:'IN_STORAGE'}]});
  const importedPc601=Store.get('inventory','pc601-import'),importedPc601Resolution=pnPartCatalogResolution(importedPc601),importedPc601Rig=rigSlotResolved({kind:'INVENTORY',inventoryItemId:'pc601-import'},'RSD','STORAGE');
  out.push(['restored PARTS VAULT inventory resolves a PC601 Dell alias canonically', importedPc601Resolution.item===pc601&&importedPc601Resolution.confidence==='EXACT'&&pnPartNameTier(importedPc601).source==='catalog']);
  out.push(['restored PC601 inventory resolves in RIG ASSEMBLY without renaming', importedPc601Rig&&importedPc601Rig.pn&&importedPc601Rig.pn.data===pc601&&importedPc601Rig.pn.performance===78&&importedPc601Rig.pn.tier==='EPIC']);
  out.push(['RAM catalog searches by brand and series', catalogSearch('RAM','vengeance lpx').some(r=>r.series==='Vengeance LPX')]);
  const anchor=catalogFind('CPU','AMD Ryzen 7 5800X3D');
  out.push(['5800X3D canonical gaming anchor preserved', anchor&&anchor.gaming===100&&anchor.overall===90]);
  out.push(['canonical tier order preserved', PN_GEAR_TIERS.join('>')==='POOR>COMMON>UNCOMMON>RARE>EPIC>LEGENDARY>ARTIFACT']);
  out.push(['AM5 CPU registry has 58 entries', canonicalHardware.cpus.filter(c=>c.platform==='AM5').length===58]);
  out.push(['AM5 registry has 56 active released SKUs', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').length===56]);
  out.push(['AM5 registry has 2 documented HOLD records', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='DOCUMENTED_UNRELEASED').length===2]);
  out.push(['AM5 HOLD records carry no invented ratings', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='DOCUMENTED_UNRELEASED').every(c=>c.pn_score===null&&c.pn_tier===null)]);
  out.push(['every active AM5 CPU has a pn_score', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').every(c=>Number.isFinite(c.pn_score)&&c.pn_score>=0&&c.pn_score<=100)]);
  out.push(['active AM5 tiers match the PN tier mapping', HardwareCatalog.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').every(c=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(c.pn_tier))]);
  out.push(['AM5 tier boundaries honor the canonical scale', HardwareCatalog.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').every(c=>{const s=c.pn_score;const t=c.pn_tier;return(t==='ARTIFACT'&&s>=97&&s<=100)||(t==='LEGENDARY'&&s>=88&&s<97)||(t==='EPIC'&&s>=75&&s<88)||(t==='RARE'&&s>=60&&s<75)||(t==='UNCOMMON'&&s>=45&&s<60)||(t==='COMMON'&&s>=30&&s<45)||(t==='POOR'&&s>=0&&s<30)})]);
  out.push(['every active AM5 CPU is PN_AM5_CPU_V2 rated', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').every(c=>c.rating_method==='PN_AM5_CPU_V2')]);
  out.push(['every AM5 record carries rating confidence', canonicalHardware.cpus.filter(c=>c.platform==='AM5').every(c=>['HIGH','MEDIUM','LOW'].includes(c.rating_confidence))]);
  out.push(['every active AM5 CPU has a source_url', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.availability_status==='RELEASED').every(c=>typeof c.source_url==='string'&&c.source_url.length>5)]);
  out.push(['no duplicate canonical AM5 CPU models', canonicalHardware.cpus.filter(c=>c.platform==='AM5').map(c=>c.model).sort().every((m,i,a)=>i===0||m!==a[i-1])]);
  out.push(['AM5 registry exposes the canonical gameplay anchors', canonicalHardware.cpus.find(c=>c.model==='Ryzen 7 7800X3D').pn_score===91&&HardwareCatalog.cpus.find(c=>c.model==='Ryzen 7 7800X3D').pn_tier==='LEGENDARY']);
  out.push(['AM5 registry scores the 9800X3D flagship', canonicalHardware.cpus.find(c=>c.model==='Ryzen 7 9800X3D').pn_score===96&&canonicalHardware.cpus.find(c=>c.model==='Ryzen 7 7800X3D').pn_score<canonicalHardware.cpus.find(c=>c.model==='Ryzen 7 9800X3D').pn_score]);
  out.push(['AM5 registry scores the 9950X3D2 as peak capability', canonicalHardware.cpus.find(c=>c.model==='Ryzen 9 9950X3D2 Dual Edition').pn_score===100]);
  out.push(['AM5 registry scores the budget APU floor', canonicalHardware.cpus.find(c=>c.model==='Ryzen 3 PRO 8300GE').pn_score===53&&canonicalHardware.cpus.find(c=>c.model==='Ryzen 5 7500F').pn_score===72]);
  out.push(['AM5 PRO SKUs inherit non-reduced capability', canonicalHardware.cpus.filter(c=>c.platform==='AM5'&&c.family&&c.family.includes('PRO')&&c.availability_status==='RELEASED').every(c=>Number.isFinite(c.pn_score)&&c.pn_score>0)]);
  out.push(['HOLD records stay out of catalog search', catalogSearch('CPU','9600X3D').length===0&&catalogSearch('CPU','PRO 9400').length===0]);
  out.push(['HOLD records stay out of all-slot search', catalogSearchAll('9600X3D').length===0&&catalogSearchAll('PRO 9400').length===0]);
  out.push(['HOLD records never resolve through catalogFind', catalogFind('CPU','AMD Ryzen 5 9600X3D')===null&&catalogFind('CPU','AMD Ryzen 5 PRO 9400')===null]);
  out.push(['released AM5 CPUs still resolve through catalogFind', catalogFind('CPU','AMD Ryzen 7 9800X3D')!==null&&catalogFind('CPU','AMD Ryzen 5 7500F')!==null]);
  out.push(['catalog suggestions wait for 2 characters', catalogSearch('MOBO','B').length===0]);
  out.push(['catalog suggestions are capped at 12', catalogSearch('MOBO','B5').length<=12]);
  out.push(['catalog search matches brand + chipset even with a sub-line name between them', catalogSearch('MOBO','MSI B650').some(b=>b.brand==='MSI'&&b.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['catalogSearchAll matches brand + chipset even with a sub-line name between them', catalogSearchAll('MSI B650').some(m=>m.cat==='MOTHERBOARD'&&m.item.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['catalog search word order does not matter', catalogSearch('MOBO','TOMAHAWK MSI').some(b=>b.model==='MAG B650 TOMAHAWK WIFI')]);
  out.push(['PARTS VAULT visual tiers are a separate five-level system', Object.keys(PN_PART_NAME_TIERS).join('>')==='1>2>3>4>5>6>7'&&PN_PART_NAME_TIERS[6].label==='Legendary']);
  out.push(['GPU visual tiers follow the strict category examples', pnPartNameTier({category:'GPU',manufacturer:'NVIDIA',model:'GTX 1070 Hercules'}).key==='UNCOMMON'&&pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600'}).key==='RARE'&&pnPartNameTier({category:'GPU',manufacturer:'NVIDIA',model:'RTX 3080'}).key==='EPIC']);
  out.push(['CPU visual tiers follow the category examples', pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 5 3600'}).key==='UNCOMMON'&&pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 5 5600'}).key==='RARE'&&pnPartNameTier({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).key==='EPIC']);
  out.push(['unknown X570 is not promoted to gold by chipset alone', pnPartNameTier({category:'MOTHERBOARD',manufacturer:'Mystery',model:'X570 Board'}).key==='RARE']);
  out.push(['RAM configuration drives category-relative visual tier', pnPartNameTier({category:'RAM',manufacturer:'Kingston',model:'8GB DDR4 single channel'}).key==='POOR'&&pnPartNameTier({category:'RAM',manufacturer:'G.Skill',model:'32GB DDR5 6000MHz CL30'}).key==='ARTIFACT']);
  out.push(['PSU reputation outweighs wattage in visual tiering', pnPartNameTier({category:'PSU',manufacturer:'Generic',model:'1000W PSU'}).key==='POOR'&&pnPartNameTier({category:'PSU',manufacturer:'Corsair',model:'RMx 750W'}).key==='ARTIFACT']);
  out.push(['storage type/capacity and health affect its visual tier', pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING'}).key==='ARTIFACT'&&pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING',healthPercent:72}).key==='RARE']);
  out.push(['zero-percent storage health is preserved as failed media evidence', pnPartNameTier({category:'STORAGE',manufacturer:'Samsung',model:'990 Pro 2TB NVMe',condition:'WORKING',driveHealthPercent:0}).key==='POOR']);
  out.push(['purchase price never changes the visual tier', pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600',purchasePrice:1}).key===pnPartNameTier({category:'GPU',manufacturer:'AMD',model:'RX 6600',purchasePrice:999999}).key]);
  const exactCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'});
  const normalizedCatalog=pnPartCatalogResolution({category:'GPU',manufacturer:'NVIDIA',model:'GTX 1070 8GB GDDR5 OC'});
  const manualCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'AMD Ryzen 7 5800X3D'});
  const unresolvedCatalog=pnPartCatalogResolution({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'Not a real canonical model'});
  out.push(['catalog matching exposes exact and normalized confidence', exactCatalog.item&&exactCatalog.confidence==='EXACT'&&normalizedCatalog.item&&['NORMALIZED','FAMILY'].includes(normalizedCatalog.confidence)]);
  out.push(['manual catalog override is explicit and deterministic', manualCatalog.item&&manualCatalog.confidence==='MANUAL'&&String(manualCatalog.item.model).includes('5800X3D')]);
  out.push(['unresolved manual override fails safely without invented evidence', !unresolvedCatalog.item&&unresolvedCatalog.confidence==='UNRESOLVED'&&pnPartNameTier({category:'CPU',manufacturer:'Mystery',model:'Processor',catalogOverride:'Not a real canonical model'}).source==='heuristic']);
  out.push(['tier inspector explains the tier source and exposes advanced correction', pnPartTierExplanationHtml({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).includes('Exact brand and model match')&&pnPartTierExplanationHtml({category:'CPU',manufacturer:'AMD',model:'Ryzen 7 5800X3D'}).includes('CATALOG LINK / ADVANCED')]);

  function cat(type,label,cost=0){ return {kind:'CATALOG',catalogType:type,label,cost,currency:'RSD'}; }
  function example(cpu,gpu,board){ const r=newRigDraft('FOUNDATION'); r.slots.CPU=cat('CPU',cpu); r.slots.GPU=cat('GPU',gpu); r.slots.MOBO=cat('MOBO',board); r.slots.RAM={kind:'PLANNED',label:'2x8GB DDR4 dual channel',cost:0,currency:'RSD'}; r.slots.PSU={kind:'PLANNED',label:'Corsair 750W',cost:0,currency:'RSD'}; r.slots.STORAGE={kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,currency:'RSD'}; r.slots.COOLER={kind:'PLANNED',label:'Tower cooler',cost:0,currency:'RSD'}; return r; }
  const ex1=rigHardwareProfile(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'));
  const ex2=rigHardwareProfile(example('AMD Ryzen 5 5600','AMD RX 6700 XT 12GB','Gigabyte B550 AORUS MASTER'));
  const ex3=rigHardwareProfile(example('AMD Ryzen 7 5700X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi'));
  const ex4=rigHardwareProfile(example('AMD Ryzen 5 2600','NVIDIA GTX 1070 8GB','MSI B450 TOMAHAWK MAX'));
  const bad=rigHardwareProfile(example('AMD Ryzen 7 5800X3D','AMD RX 580 8GB','MSI B450 TOMAHAWK MAX'));
  out.push(['3600 + RTX 2060 + B450 is UNCOMMON', ex1.tier==='UNCOMMON']);
  out.push(['5600 + RX 6700 XT + B550 is RARE', ex2.tier==='RARE']);
  out.push(['5700X3D + RTX 3080 + X570 is ALRARE', ex3.tier==='EPIC']);
  out.push(['2600 + GTX 1070 is UNCOMMON', ex4.tier==='UNCOMMON']);
  out.push(['5800X3D + RX 580 is not ALRARE', bad.tier!=='EPIC']);
  out.push(['severe CPU/GPU imbalance warning fires', bad.warnings.some(w=>w.includes('Severe CPU/GPU imbalance'))]);
  const editor=renderRigSlotRow('CPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['mode menu no longer exposes PN Hardware Catalog', !editor.includes('PN Hardware Catalog')]);
  out.push(['legacy catalog slots display as Planned Part', editor.includes('<option value="PLANNED" selected>Planned Part</option>')]);
  out.push(['catalog selector uses an automatic results panel', editor.includes('data-rig-catalog-item="CPU"')&&!editor.includes('<datalist')]);
  state.rigDraft = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  state.rigDraft.slots.CPU.label = '3600';
  const searching = renderRigEditor();
  out.push(['typing 3600 immediately renders Ryzen 5 3600', searching.includes('data-rig-catalog-choice="CPU"')&&searching.includes('AMD Ryzen 5 3600')]);
  out.push(['search result separates performance and tier badges', searching.includes('pn-result-rating')&&searching.includes('pn-result-tier pn-tier-uncommon')]);
  out.push(['part rating and Gear Tier render separately', editor.includes('pn-meta-pill')&&editor.includes('Performance')&&editor.includes('pn-tier-pill')&&editor.includes('Tier')]);
  out.push(['selected part carries its canonical tier color class', editor.includes('pn-tier-pill pn-tier-uncommon')]);
  const ram3200=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16});
  const ram3600=ramRating({moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3600,casLatency:16});
  out.push(['DDR4 true latency formula gives 10ns for 3200 CL16', ram3200.latencyNs===10]);
  out.push(['DDR4 V3.1 exposes V3 component scores plus its generation-relative class', ram3200.capacityScore===45&&ram3200.bandwidthScore===38&&ram3200.latencyScore===84&&ram3200.topologyScore===100&&ram3200.baseV3Score===59&&ram3200.overall===60&&ram3200.tier==='RARE'&&ram3200.ddr4Class==='GAMING'&&ram3200.matrixTier==='RARE']);
  out.push(['DDR4 3600 CL16 follows V3.1 without brand/RGB bonus', ram3600.overall===62&&ram3600.tier==='RARE'&&ram3600.rating_method==='PN_RAM_V3_1_2026']);
  const ramThree=ramRating({technology:'DDR4',moduleCount:3,perModuleCapacity:8,speed:3200,casLatency:16});
  out.push(['three-DIMM DDR4 derives its real capacity and applies only the asymmetric-topology warning', ramThree.totalCapacity===24&&ramThree.capacityScore===60&&ramThree.topologyScore===75&&ramThree.warnings.some(w=>/Three-DIMM/.test(w))&&!ramThree.warnings.some(w=>/Four-DIMM/.test(w))]);
  const tight4133=ramRating({technology:'DDR4',moduleCount:2,perModuleCapacity:8,speed:4133,casLatency:19});
  const loose4133=ramRating({technology:'DDR4',moduleCount:2,perModuleCapacity:8,speed:4133,casLatency:30});
  out.push(['DDR4 V3.1 requires qualified latency before a fast kit earns the extreme matrix column', tight4133.tier==='EPIC'&&tight4133.ddr4Class==='EXTREME'&&loose4133.tier==='UNCOMMON'&&loose4133.ddr4Class==='BASIC']);
  out.push(['RAM V3.1 publishes its doctrine and complete DDR4 topology matrix', __PN_RAM_V31.version==='PN_RAM_V3_1_2026'&&__PN_RAM_V31.moduleCounts.join(',')==='1,2,3,4'&&__PN_RAM_V31.anchors.length===13]);
  const ramRig=newRigDraft('RAM TEST');ramRig.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'Corsair Vengeance LPX',cost:0,originalPrice:0,currency:'RSD',ram:{technology:'DDR4',moduleCount:1,perModuleCapacity:8,totalCapacity:8,speed:2400,casLatency:16}};
  const ramEditor=renderRigSlotRow('RAM',ramRig);
  out.push(['RIG BUILD renders the complete V3.1 DDR4 configuration fields', ramEditor.includes('data-rig-ram-field="technology"')&&ramEditor.includes('data-rig-ram-field="dimmType"')&&ramEditor.includes('data-rig-ram-field="moduleCount"')&&ramEditor.includes('<option value="3"')&&ramEditor.includes('data-rig-ram-field="speed"')&&ramEditor.includes('data-rig-ram-field="casLatency"')&&ramEditor.includes('data-rig-ram-field="expo"')&&!ramEditor.includes('data-rig-ram-field="voltage"')&&!ramEditor.includes('data-rig-ram-field="model"')]);
  const gpuEditor=renderRigSlotRow('GPU',Object.assign(example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX'),{id:null}));
  out.push(['GPU detail omits Raster and RT options', !gpuEditor.includes('Raster')&&!gpuEditor.includes('· RT')]);
  out.push(['user-facing hardware labels spell out PROFITNODE', PNCoreRenderRigEditor.toString().includes('PROFITNODE Rig Performance')&&!PNCoreRenderRigEditor.toString().includes('PN Rig Performance')]);
  out.push(['single-channel and insufficient-capacity RAM warnings fire', rigWarnings(ramRig).some(w=>w.includes('Single-channel'))&&rigWarnings(ramRig).some(w=>w.includes('below 16 GB'))]);
  const am5Cpu=catalogFind('CPU','AMD Ryzen 7 9800X3D');
  out.push(['AM5 9800X3D found in CPU catalog', am5Cpu&&am5Cpu.cores===8&&am5Cpu.threads===16]);
  const am5Board=catalogFind('MOBO','ASUS ROG CROSSHAIR X870E HERO');
  out.push(['AM5 X870E board found in motherboard catalog', am5Board&&am5Board.socket==='AM5'&&am5Board.chipset==='X870E']);
  const b850Board=catalogFind('MOBO','MSI MAG B850 TOMAHAWK WIFI');
  out.push(['AM5 B850 board found in motherboard catalog', b850Board&&b850Board.socket==='AM5'&&b850Board.chipset==='B850']);
  out.push(['detectMoboSocket recognizes AM5 socket', detectMoboSocket('ASUS ROG STRIX X870E-E GAMING WIFI')==='AM5']);
  out.push(['detectMoboSocket recognizes 800-series as AM5', detectMoboSocket('MSI MAG B850 TOMAHAWK MAX WIFI')==='AM5']);
  out.push(['detectMoboSocket recognizes B840 as AM5', detectMoboSocket('ASRock B840M Pro-A WiFi')==='AM5']);
  out.push(['detectMoboPcieGeneration returns Gen5 for AM5 X870E boards', detectMoboPcieGeneration('ASUS ROG CROSSHAIR X870E HERO')===5]);
  out.push(['detectMoboPcieGeneration returns Gen4 for A620 (never blanket Gen5)', detectMoboPcieGeneration('ASRock A620M-HDV/M.2')===4]);
  out.push(['AMD PCIe matrix: B850 label resolves Gen4 GPU / Gen5 M.2', detectMoboPcieGeneration('MSI MAG B850 TOMAHAWK WIFI')===4&&detectMoboStoragePcieGeneration('MSI MAG B850 TOMAHAWK WIFI')===5]);
  out.push(['AMD PCIe matrix: X670 label resolves Gen4 GPU / Gen5 M.2', detectMoboPcieGeneration('ASUS PRIME X670-P WIFI')===4&&detectMoboStoragePcieGeneration('ASUS PRIME X670-P WIFI')===5]);
  out.push(['AMD PCIe matrix: B650E resolves Gen5 GPU / Gen5 M.2', detectMoboPcieGeneration('ASUS ROG STRIX B650E-F GAMING WIFI')===5&&detectMoboStoragePcieGeneration('ASUS ROG STRIX B650E-F GAMING WIFI')===5]);
  out.push(['AMD PCIe matrix: B840 resolves Gen4 GPU / Gen4 M.2', detectMoboPcieGeneration('ASUS PRIME B840M-A WIFI')===4&&detectMoboStoragePcieGeneration('ASUS PRIME B840M-A WIFI')===4]);
  out.push(['AMD PCIe matrix: PRO665 workstation resolves Gen4 GPU / Gen5 M.2', detectMoboPcieGeneration('ASUS Pro WS 665-ACE')===4&&detectMoboStoragePcieGeneration('ASUS Pro WS 665-ACE')===5]);
  out.push(['AMD PCIe matrix: A620A resolves Gen4 GPU / Gen4 M.2', detectMoboPcieGeneration('ASUS PRIME A620A-PLUS WIFI')===4&&detectMoboStoragePcieGeneration('ASUS PRIME A620A-PLUS WIFI')===4]);
  out.push(['detectMoboSocket recognizes PRO 665 as AM5', detectMoboSocket('ASUS Pro WS 665-ACE')==='AM5']);

  const asusAm5 = HardwareCatalog.boards.filter(b=>b.brand==='ASUS'&&b.socket==='AM5');
  out.push(['ASUS AM5 registry is live with 124 verified SKUs', asusAm5.length===124]);
  out.push(['every ASUS AM5 board carries PN_AM5_MOBO_V2 rating', asusAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every ASUS AM5 board resolves to a valid tier', ['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].every(t=>asusAm5.some(b=>b.pn_tier===t))||asusAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier))]);
  out.push(['ASUS tier never equals the chipset name', asusAm5.every(b=>b.pn_tier!==b.chipset&&!new RegExp('^'+b.pn_tier+'$','i').test(b.chipset))&&asusAm5.every(b=>['X870E','X870','B850','B840','B650E','B650','X670E','X670','A620A','A620','PRO 665','PRO 600'].includes(b.chipset))]);
  out.push(['every ASUS AM5 board has per-board PCIe generation and M.2 detail', asusAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate ASUS AM5 model keys', (function(){const s=new Set();let dup=0;asusAm5.forEach(b=>{const k=(b.brand+' '+b.model).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();s.has(k)&&dup++,s.add(k)});return dup===0})()]);
  out.push(['every ASUS AM5 board is RELEASED (no fabricated HOLD)', asusAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the board score', asusAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['ASUS high-tier boards land LEGENDARY, entry boards stay below', catalogFind('MOBO','ASUS ROG CROSSHAIR X870E GLACIAL').pn_tier==='LEGENDARY'&&catalogFind('MOBO','ASUS PRIME A620M-K').pn_tier!=='ALRARE'&&catalogFind('MOBO','ASUS ROG CROSSHAIR X870E HERO').pn_score>=80]);

  const msiAm5 = HardwareCatalog.boards.filter(b=>b.brand==='MSI'&&b.socket==='AM5');
  out.push(['MSI AM5 registry is live with 64 verified SKUs', msiAm5.length===64]);
  out.push(['every MSI AM5 board carries PN_AM5_MOBO_V2 rating', msiAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every MSI AM5 board resolves to a valid tier on a valid chipset', msiAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X870','B850','B840','B650E','B650','X670E','X670','A620'].includes(b.chipset)&&b.pn_tier!==b.chipset)]);
  out.push(['every MSI AM5 board has per-board PCIe generation and M.2 detail', msiAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate MSI AM5 model keys', (function(){const s=new Set();let dup=0;msiAm5.forEach(b=>{const k=(b.brand+' '+b.model).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();s.has(k)&&dup++,s.add(k)});return dup===0})()]);
  out.push(['every MSI AM5 board is RELEASED (no fabricated HOLD)', msiAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the MSI board score', msiAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['all seven legacy MSI AM5 rows are covered by the new registry', ['MAG B650 TOMAHAWK WIFI','PRO B650M-A WIFI','MEG X670E ACE','MAG B850 TOMAHAWK WIFI','MPG X870E EDGE TI WIFI','PRO A620M-B','PRO B840M-P WIFI'].every(m=>{const b=catalogFind('MOBO','MSI '+m);return b&&b.socket==='AM5'&&b.rating_method==='PN_AM5_MOBO_V2'})]);
  out.push(['MSI flagships land LEGENDARY while entry boards stay below', catalogFind('MOBO','MSI MEG X870E GODLIKE').pn_tier==='LEGENDARY'&&catalogFind('MOBO','MSI MEG X870E GODLIKE').pn_score>=85&&catalogFind('MOBO','MSI PRO A620M-B').pn_tier!=='ALRARE'&&catalogFind('MOBO','MSI MAG B650 TOMAHAWK WIFI').pn_score>=75]);
  out.push(['MSI submodels resolve independently (MAX vs non-MAX, PZ)', catalogFind('MOBO','MSI MAG B650 TOMAHAWK WIFI').model!==catalogFind('MOBO','MSI MAG B650 TOMAHAWK MAX WIFI').model&&catalogFind('MOBO','MSI MAG B850 TOMAHAWK WIFI').model!==catalogFind('MOBO','MSI MAG B850 TOMAHAWK MAX WIFI').model&&catalogFind('MOBO','MSI MAG X870E TOMAHAWK PZ WIFI').chipset==='X870E']);
  out.push(['unconfirmable MSI SKUs were dropped, real boards keep distinct entries', !msiAm5.some(b=>/X870I CARBON|X870 GAMING MAX/.test(b.model))&&catalogFind('MOBO','MSI MPG X870I EDGE TI EVO WIFI').model==='MPG X870I EDGE TI EVO WIFI']);
  const carbWifi=catalogFind('MOBO','MSI MPG X870E CARBON WIFI');
  out.push(['MPG X870E CARBON WIFI carries the verified 5G + 2.5G network stack', carbWifi&&carbWifi.ethernet_speed==='5G + 2.5G'&&carbWifi.usb4===true&&carbWifi.vrm_phases===18&&carbWifi.pn_score>=80]);
  const b650m=catalogFind('MOBO','MSI MAG B650M MORTAR WIFI');
  out.push(['MSI M-series boards normalize to Micro-ATX', b650m.form_factor==='Micro-ATX'&&motherboardCatalogFormFactor({pn:{data:b650m}})==='MATX'&&catalogFind('MOBO','MSI PRO B650M-A WIFI').form_factor==='Micro-ATX'&&catalogFind('MOBO','MSI PRO B840M-P WIFI').form_factor==='Micro-ATX'&&catalogFind('MOBO','MSI PRO A620M-B').form_factor==='Micro-ATX']);
  out.push(['MSI X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('MSI MPG X870E CARBON WIFI')===5&&detectMoboStoragePcieGeneration('MSI MPG X870E CARBON WIFI')===5]);
  out.push(['MSI B840 micro resolves Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('MSI PRO B840M-P WIFI')===4&&detectMoboStoragePcieGeneration('MSI PRO B840M-P WIFI')===4]);
  out.push(['MSI X870 TOMAHAWK carries verified Gen5 PCB, USB4 and RTL8126-CG facts', (function(){const b=catalogFind('MOBO','MSI MAG X870 TOMAHAWK WIFI');return b&&b.primary_pcie_generation===5&&b.m2_slots===4&&b.usb4===true&&String(b.ethernet_controller).includes('RTL8126')})()]);

  const gigAm5=HardwareCatalog.boards.filter(b=>b.brand==='Gigabyte'&&b.socket==='AM5');
  out.push(['Gigabyte AM5 registry is live with 136 verified SKUs', gigAm5.length===136]);
  out.push(['every Gigabyte AM5 board carries PN_AM5_MOBO_V2 rating', gigAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every Gigabyte AM5 board resolves to a valid tier on a valid chipset', gigAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X870','B850','B840','B650E','B650','X670E','X670','A620'].includes(b.chipset)&&b.pn_tier!==b.chipset)]);
  out.push(['every Gigabyte AM5 board has per-board PCIe generation and M.2 detail', gigAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate Gigabyte AM5 model keys', (function(){const s=new Set();let dup=0;gigAm5.forEach(b=>{const k=(b.brand+' '+b.model).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();s.has(k)&&dup++,s.add(k)});return dup===0})()]);
  out.push(['every Gigabyte AM5 board is RELEASED (no fabricated HOLD)', gigAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the Gigabyte board score', gigAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['all five legacy Gigabyte AM5 rows are covered by the new registry', ['B650 AORUS ELITE AX','B650M DS3H','X670E AORUS MASTER','X870E AORUS MASTER','B650I AORUS ULTRA'].every(m=>{const b=catalogFind('MOBO','Gigabyte '+m);return b&&b.socket==='AM5'&&b.rating_method==='PN_AM5_MOBO_V2'})]);
  out.push(['Gigabyte flagships land LEGENDARY while entry boards stay below', catalogFind('MOBO','Gigabyte X870E AORUS XTREME AI TOP').pn_tier==='LEGENDARY'&&catalogFind('MOBO','Gigabyte X870E AORUS XTREME AI TOP').pn_score>=85&&catalogFind('MOBO','Gigabyte A620M H').pn_tier!=='ALRARE'&&catalogFind('MOBO','Gigabyte B650 AORUS ELITE AX').pn_score>=75]);
  out.push(['Gigabyte X870 AORUS INFINITY carries verified 5G, 22-phase VRM and USB4 facts', (function(){const b=catalogFind('MOBO','Gigabyte X870 AORUS INFINITY');return b&&b.ethernet_speed==='5G'&&b.vrm_phases===22&&b.usb4===true&&b.m2_slots===3&&b.pn_score>=85})()]);
  out.push(['Gigabyte Wi-Fi / non-Wi-Fi submodels are distinct SKUs', catalogFind('MOBO','Gigabyte B650M DS3H').wifi===false&&catalogFind('MOBO','Gigabyte B650I AORUS ULTRA').wifi===true&&catalogFind('MOBO','Gigabyte B650I AORUS ULTRA').wifi_standard==='Wi-Fi 6E'&&catalogFind('MOBO','Gigabyte B650E AORUS PRO X USB4').wifi_standard==='Wi-Fi 7']);
  out.push(['Gigabyte ICE submodels stay distinct and carry the white variant tag', (function(){const ice=catalogFind('MOBO','Gigabyte X870E AORUS MASTER X3D ICE');const std=catalogFind('MOBO','Gigabyte X870E AORUS MASTER X3D');return ice&&ice.model!==std.model&&ice.color_variant==='ICE'&&std.color_variant===null})()]);
  out.push(['Gigabyte mATX / Mini-ITX / E-ATX form factors normalize through the mapper', motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','Gigabyte X870M AORUS ELITE WIFI7')}})==='MATX'&&motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','Gigabyte B650I AORUS ULTRA')}})==='ITX'&&catalogFind('MOBO','Gigabyte X870E AORUS XTREME AI TOP').form_factor==='E-ATX']);
  out.push(['Gigabyte X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('Gigabyte B650E AORUS MASTER')===5&&detectMoboStoragePcieGeneration('Gigabyte B650E AORUS MASTER')===5]);
  out.push(['Gigabyte B650M resolves Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('Gigabyte B650M DS3H')===4&&detectMoboStoragePcieGeneration('Gigabyte B650M DS3H')===4]);

  const asrockAm5=HardwareCatalog.boards.filter(b=>b.brand==='ASRock'&&b.socket==='AM5');
  out.push(['ASRock AM5 registry is live with 87 verified SKUs', asrockAm5.length===87]);
  out.push(['every ASRock AM5 board carries PN_AM5_MOBO_V2 rating', asrockAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every ASRock AM5 board resolves to a valid tier on a valid chipset', asrockAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X870','B850','B650E','B650','A620','A620A'].includes(b.chipset)&&b.pn_tier!==b.chipset)]);
  out.push(['every ASRock AM5 board has per-board PCIe generation and M.2 detail', asrockAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate ASRock AM5 model names', asrockAm5.every(b=>asrockAm5.filter(x=>x.model===b.model).length===1)]);
  out.push(['every ASRock AM5 board is RELEASED (no fabricated HOLD)', asrockAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the ASRock board score', asrockAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['legacy ASRock AM5 rows are covered by the new registry', ['B650M Pro RS WiFi','A620M-HDV'].every(m=>{const b=catalogFind('MOBO','ASRock '+m);return b&&b.socket==='AM5'&&b.rating_method==='PN_AM5_MOBO_V2'})]);
  out.push(['ASRock flagships land LEGENDARY while entry boards stay below', catalogFind('MOBO','ASRock X870E Nova WiFi').pn_tier==='LEGENDARY'&&catalogFind('MOBO','ASRock X870E Nova WiFi').pn_score>=85&&catalogFind('MOBO','ASRock A620M Pro RS WiFi').pn_tier!=='ALRARE']);
  out.push(['ASRock X870E Taichi carries verified 24+2+1 VRM, 5G LAN and USB4 facts', (function(){const b=catalogFind('MOBO','ASRock X870E Taichi');return b&&b.vrm_phases===27&&b.ethernet_speed==='5G'&&b.usb4===true&&b.m2_slots===4&&b.pn_score>=85})()]);
  out.push(['ASRock B650E PG-ITX carries verified 10+2+1 VRM, ALC1220 and Mini-ITX form', (function(){const b=catalogFind('MOBO','ASRock B650E PG-ITX WiFi');return b&&b.vrm_phases===13&&b.audio_codec==='Realtek ALC1220'&&b.form_factor==='Mini-ITX'&&b.m2_slots===2&&b.pn_score>=70})()]);
  out.push(['ASRock B850 Steel Legend carries verified 14+2+1 VRM, Wi-Fi 7 and 4x M.2', (function(){const b=catalogFind('MOBO','ASRock B850 Steel Legend WiFi');return b&&b.vrm_phases===17&&b.wifi_standard==='Wi-Fi 7'&&b.m2_slots===4&&b.pn_score>=80})()]);
  out.push(['ASRock mATX / Mini-ITX / E-ATX form factors normalize through the mapper', motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','ASRock B850M Steel Legend WiFi')}})==='MATX'&&motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','ASRock B650E PG-ITX WiFi')}})==='ITX'&&catalogFind('MOBO','ASRock X870E Taichi').form_factor==='E-ATX']);
  out.push(['ASRock X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('ASRock X870E Nova WiFi')===5&&detectMoboStoragePcieGeneration('ASRock X870E Nova WiFi')===5]);
  out.push(['ASRock A620 resolves Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('ASRock A620M Pro RS WiFi')===4&&detectMoboStoragePcieGeneration('ASRock A620M Pro RS WiFi')===4]);

  const nzxtAm5=HardwareCatalog.boards.filter(b=>b.brand==='NZXT'&&b.socket==='AM5');
  out.push(['NZXT AM5 registry is live with 4 verified SKUs', nzxtAm5.length===4]);
  out.push(['every NZXT AM5 board carries PN_AM5_MOBO_V2 rating', nzxtAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every NZXT AM5 board resolves to a valid tier on a valid chipset', nzxtAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X870','B850','B650E','B650','A620','A620A'].includes(b.chipset)&&b.pn_tier!==b.chipset)]);
  out.push(['every NZXT AM5 board has per-board PCIe generation and M.2 detail', nzxtAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate NZXT AM5 model names', nzxtAm5.every(b=>nzxtAm5.filter(x=>x.model===b.model).length===1)]);
  out.push(['every NZXT AM5 board is RELEASED (no fabricated HOLD)', nzxtAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the NZXT board score', nzxtAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['NZXT N9 X870E carries verified 20+2+1 VRM, 5G/2.5G LAN, Wi-Fi 7 and USB4 facts', (function(){const b=catalogFind('MOBO','NZXT N9 X870E');return b&&b.vrm_phases===23&&b.ethernet_speed==='5G'&&b.wifi_standard==='Wi-Fi 7'&&b.usb4===true&&b.m2_slots===4&&b.pn_score>=85})()]);
  out.push(['N7 B650E carries verified 16+2+1 VRM, ALC1220, Wi-Fi 6E and 3x M.2', (function(){const b=catalogFind('MOBO','N7 B650E');return b&&b.vrm_phases===19&&b.audio_codec==='Realtek ALC1220'&&b.wifi_standard==='Wi-Fi 6E'&&b.m2_slots===3&&b.ethernet_speed==='2.5G'&&b.pn_score>=75})()]);
  out.push(['N7 B850 carries verified 16+2+1 VRM with 80A DrMOS and 2.5G LAN', (function(){const b=catalogFind('MOBO','N7 B850');return b&&b.vrm_phases===19&&b.power_stage_rating===80&&b.ethernet_speed==='2.5G'&&b.wifi_standard==='Wi-Fi 6E'&&b.pn_score>=75})()]);
  out.push(['NZXT N9 X870E Kraken Elite bundle stays a distinct verified SKU', (function(){const b=catalogFind('MOBO','NZXT N9 X870E + Kraken Elite 360 RGB');return b&&b.rating_method==='PN_AM5_MOBO_V2'&&b.pn_score===catalogFind('MOBO','NZXT N9 X870E').pn_score})()]);
  out.push(['NZXT X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('NZXT N9 X870E')===5&&detectMoboStoragePcieGeneration('NZXT N9 X870E')===5]);
  out.push(['NZXT B650E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('N7 B650E')===5&&detectMoboStoragePcieGeneration('N7 B650E')===5]);
  out.push(['ASRock AM5 rows no longer carry NZXT N-series co-branded boards', HardwareCatalog.boards.filter(b=>b.brand==='ASRock'&&/^N7|^N9/.test(b.model||'')).length===0]);

  const biostarAm5=HardwareCatalog.boards.filter(b=>b.brand==='Biostar'&&b.socket==='AM5');
  out.push(['Biostar AM5 registry is live with 22 verified SKUs', biostarAm5.length===22]);
  out.push(['every Biostar AM5 board carries PN_AM5_MOBO_V2 rating', biostarAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every Biostar AM5 board resolves to a valid tier on a valid chipset', biostarAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X670E','X670','B850','B840','B650E','B650','A620A','A620'].includes(b.chipset))]);
  out.push(['every Biostar AM5 board links out to its official S_ID page', biostarAm5.every(b=>b.source_url.indexOf('biostar.com.tw/app/en/mb/introduction.php?S_ID=')!==-1&&Number.isInteger(Number(b.source_url.split('S_ID=')[1]))&&Number(b.source_url.split('S_ID=')[1])>0)]);
  out.push(['every Biostar AM5 board has per-board PCIe generation and M.2 detail', biostarAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate Biostar AM5 model names', biostarAm5.every(b=>biostarAm5.filter(x=>x.model===b.model).length===1)]);
  out.push(['every Biostar AM5 board is RELEASED (no fabricated HOLD)', biostarAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the Biostar board score', biostarAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['Biostar X870E VALKYRIE carries verified 18+2+2 VRM, 110A, USB4 and 4x M.2 facts', (function(){const b=catalogFind('MOBO','Biostar X870E VALKYRIE');return b&&b.vrm_phases===22&&b.power_stage_rating===110&&b.usb4===true&&b.m2_slots===4&&b.sata_ports===6&&b.pn_score>=85})()]);
  out.push(['Biostar X670E VALKYRIE carries verified 22-phase, 105A VRM and 4x M.2', (function(){const b=catalogFind('MOBO','Biostar X670E VALKYRIE');return b&&b.chipset==='X670E'&&b.vrm_phases===22&&b.power_stage_rating===105&&b.m2_slots===4&&b.pn_score>=80})()]);
  out.push(['Biostar B650EGTQ carries verified B650E chipset, 14-phase VRM and Micro-ATX form', (function(){const b=catalogFind('MOBO','Biostar B650EGTQ');return b&&b.chipset==='B650E'&&b.vrm_phases===14&&b.power_stage_rating===90&&b.form_factor==='Micro-ATX'&&b.m2_slots===3&&b.pn_score>=70})()]);
  out.push(['Biostar B840MT-E carries verified Gen4 PCIe and 2-DIMM DDR5 up to 128GB', (function(){const b=catalogFind('MOBO','Biostar B840MT-E');return b&&b.chipset==='B840'&&b.primary_pcie_generation===4&&b.memory_slots===2&&b.max_memory===128&&b.form_factor==='Micro-ATX'})()]);
  out.push(['Biostar X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('Biostar X870E VALKYRIE')===5&&detectMoboStoragePcieGeneration('Biostar X870E VALKYRIE')===5]);
  out.push(['Biostar B650E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('Biostar B650EGTQ')===5&&detectMoboStoragePcieGeneration('Biostar B650EGTQ')===5]);
  out.push(['Biostar B650 resolves Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('Biostar B650M-SILVER')===4&&detectMoboStoragePcieGeneration('Biostar B650M-SILVER')===4]);
  out.push(['Biostar A620A and B840 boards resolve Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('Biostar A620MH AURORA')===4&&detectMoboStoragePcieGeneration('Biostar A620MH AURORA')===4&&detectMoboPcieGeneration('Biostar B840MT-E')===4&&detectMoboStoragePcieGeneration('Biostar B840MT-E')===4]);

  const colorfulAm5=HardwareCatalog.boards.filter(b=>b.brand==='Colorful'&&b.socket==='AM5');
  out.push(['Colorful AM5 registry is live with 13 verified SKUs', colorfulAm5.length===13]);
  out.push(['every Colorful AM5 board carries PN_AM5_MOBO_V2 rating', colorfulAm5.every(b=>b.rating_method==='PN_AM5_MOBO_V2'&&typeof b.pn_score==='number'&&b.pn_score>=0&&b.pn_score<=100&&b.pn_tier)]);
  out.push(['every Colorful AM5 board resolves to a valid tier on a valid chipset', colorfulAm5.every(b=>['POOR','COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','ARTIFACT'].includes(b.pn_tier)&&['X870E','X870','B850','B650','A620'].includes(b.chipset))]);
  out.push(['every Colorful AM5 board links out to an official Colorful series page', colorfulAm5.every(b=>b.source_url.indexOf('colorfulgroup.com/en/home/productlist?mid=')!==-1&&b.source_url.indexOf('https://')===0)]);
  out.push(['every Colorful AM5 board has per-board PCIe generation and M.2 detail', colorfulAm5.every(b=>Number.isFinite(Number(b.primary_pcie_generation))&&b.m2_details&&b.m2_details!=='UNKNOWN'&&b.source_url)]);
  out.push(['no duplicate Colorful AM5 model names', colorfulAm5.every(b=>colorfulAm5.filter(x=>x.model===b.model).length===1)]);
  out.push(['every Colorful AM5 board is RELEASED (no fabricated HOLD)', colorfulAm5.every(b=>b.availability_status==='RELEASED')]);
  out.push(['price never enters the Colorful board score', colorfulAm5.every(b=>!('price_eur' in b)&&!('price_rsd' in b)&&b.pn_score===b.overall&&Number.isFinite(b.overall))]);
  out.push(['Colorful iGame X870E VULCAN OC V14 carries verified 18+2+2 VRM, 110A, USB4 and 5x M.2 facts', (function(){const b=catalogFind('MOBO','Colorful iGame X870E VULCAN OC V14');return b&&b.vrm_phases===22&&b.power_stage_rating===110&&b.usb4===true&&b.m2_slots===5&&b.wifi_standard==='Wi-Fi 7'&&b.ethernet_speed==='5G'&&b.pcb_layers===10&&b.pn_score>=85})()]);
  out.push(['Colorful iGame X870 Senna V14 carries verified 14+2+1 VRM, Wi-Fi 7 and 3x M.2', (function(){const b=catalogFind('MOBO','Colorful iGame X870 Senna V14');return b&&b.vrm_phases===17&&b.wifi_standard==='Wi-Fi 7'&&b.usb4===true&&b.m2_slots===3&&b.ethernet_speed==='5G'&&b.pn_score>=80})()]);
  out.push(['Colorful CVN B850M ARK FROZEN V14 carries verified 14+2+1 VRM, Wi-Fi 7 and 8-layer PCB', (function(){const b=catalogFind('MOBO','Colorful CVN B850M ARK FROZEN V14');return b&&b.vrm_phases===17&&b.wifi_standard==='Wi-Fi 7'&&b.pcb_layers===8&&b.m2_slots===3&&b.form_factor==='Micro-ATX'&&b.pn_score>=80})()]);
  out.push(['stored Colorful board PCIe gen overrides the B650 label fallback', (function(){const b=catalogFind('MOBO','Colorful CVN B650M GAMING FROZEN V14');return b&&moboGpuPcieGen(b)===Number(b.primary_pcie_generation)&&moboGpuPcieGen(b)===5})()]);
  out.push(['Colorful X870E resolves Gen5 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('Colorful iGame X870E VULCAN OC V14')===5&&detectMoboStoragePcieGeneration('Colorful iGame X870E VULCAN OC V14')===5]);
  out.push(['Colorful B850M resolves Gen4 GPU / Gen5 M.2 through the PCIe matrix', detectMoboPcieGeneration('Colorful CVN B850M ARK FROZEN V14')===4&&detectMoboStoragePcieGeneration('Colorful CVN B850M ARK FROZEN V14')===5]);
  out.push(['Colorful B650 and A620 boards resolve Gen4 GPU / Gen4 M.2 through the PCIe matrix', detectMoboPcieGeneration('Colorful CVN B650M GAMING FROZEN V14')===4&&detectMoboStoragePcieGeneration('Colorful CVN B650M GAMING FROZEN V14')===4&&detectMoboPcieGeneration('Colorful BATTLE-AX A620M-GHA WIFI V14')===4&&detectMoboStoragePcieGeneration('Colorful BATTLE-AX A620M-GHA WIFI V14')===4]);

  const hero=catalogFind('MOBO','ASUS ROG CROSSHAIR X870E HERO');
  out.push(['X870E HERO carries verified board facts', hero&&hero.socket==='AM5'&&hero.chipset==='X870E'&&hero.primary_pcie_generation===5&&hero.wifi===true&&hero.usb4===true&&hero.m2_slots===5&&hero.form_factor==='ATX']);
  const miku=catalogFind('MOBO','ASUS ROG STRIX X870E-H GAMING WIFI7 HATSUNE MIKU EDITION');
  out.push(['special-edition submodel stays distinct', miku&&miku.chipset==='X870E'&&miku.rating_confidence]);
  out.push(['X870E-H and MIKU edition resolve independently', catalogFind('MOBO','ASUS ROG STRIX X870E-H GAMING WIFI7').model!==catalogFind('MOBO','ASUS ROG STRIX X870E-H GAMING WIFI7 HATSUNE MIKU EDITION').model]);
  out.push(['Wi-Fi and non-Wi-Fi submodels are distinct SKUs', catalogFind('MOBO','ASUS PRIME B650-PLUS').model!==catalogFind('MOBO','ASUS PRIME B650-PLUS WIFI').model&&catalogFind('MOBO','ASUS PRIME B650-PLUS').wifi===false&&catalogFind('MOBO','ASUS PRIME B650-PLUS WIFI').wifi===true]);
  const x870A=catalogFind('MOBO','ASUS PRIME B850M-A');
  out.push(['B850M-A has canonical model and revision scaffolding', x870A&&x870A.canonical_model&&Array.isArray(x870A.revisions)&&x870A.model===x870A.canonical_model]);
  out.push(['stored board PCIe gen overrides the label fallback', (function(){const b=asusAm5.find(x=>x.model==='ASUS TUF GAMING B850-PLUS WIFI')||asusAm5[0];return moboGpuPcieGen(b)===Number(b.primary_pcie_generation)})()]);
  out.push(['storage PCIe gen reads M.2 config on catalog boards', (function(){const b=catalogFind('MOBO','ASUS TUF GAMING B850-PRO WIFI7 W NEO');return b&&moboStoragePcieGen(b)===5})()]);
  out.push(['catalog search finds new ASUS entries', catalogSearch('MOBO','A620M').some(b=>b.brand==='ASUS'&&b.socket==='AM5')&&catalogSearch('MOBO','CROSSHAIR').some(b=>b.chipset==='X870E')]);
  out.push(['B840M-A WIFI exact lookup resolves with updated facts', (function(){const b=catalogFind('MOBO','ASUS PRIME B840M-A WIFI');return b&&b.m2_slots===3&&b.primary_pcie_generation===4&&b.wifi===true})()]);
  out.push(['Pro WS 665-ACE resolves on the PRO 665 chipset', (function(){const b=catalogFind('MOBO','ASUS Pro WS 665-ACE');return b&&b.chipset==='PRO 665'&&b.primary_pcie_generation===4&&b.ethernet_speed==='2.5G'})()]);
  out.push(['form factor normalizes for the new registry', motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','ASUS ROG CROSSHAIR X870E GLACIAL')}})==='ATX'&&motherboardCatalogFormFactor({pn:{data:catalogFind('MOBO','ASUS PRIME B650M-A')}})==='MATX']);
  const ddr5Family=catalogSearch('RAM','G.Skill Trident Z5');
  out.push(['DDR5 RAM families found via catalog search', ddr5Family.length>0&&ddr5Family[0].technology==='DDR5']);
  const ddr5Kit=HardwareCatalog.ramFamilies.find(f=>f.technology==='DDR5'&&f.kits&&f.kits.length>0);
  out.push(['DDR5 RAM families carry kit data', ddr5Kit&&ddr5Kit.kits[0].capacity>0&&ddr5Kit.kits[0].speed>=4800]);
  const ddr5Rating=ramRating({technology:'DDR5',moduleCount:2,perModuleCapacity:16,totalCapacity:32,speed:6000,casLatency:30});
  out.push(['DDR5 6000 CL30 remains on the V3 policy while V3.1 targets DDR4 only', ddr5Rating.overall===81&&ddr5Rating.tier==='EPIC'&&ddr5Rating.rating_method==='PN_RAM_V3_2026']);
  const am5Build=newRigDraft('AM5 TEST');am5Build.slots.CPU=cat('CPU','AMD Ryzen 7 9800X3D');am5Build.slots.GPU=cat('GPU','NVIDIA RTX 5070 Ti 16GB');am5Build.slots.MOBO=cat('MOBO','ASUS ROG CROSSHAIR X870E HERO');am5Build.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'2x16GB DDR5 6000',cost:0,originalPrice:0,currency:'RSD',ram:{technology:'DDR5',moduleCount:2,perModuleCapacity:16,totalCapacity:32,speed:6000,casLatency:30}};am5Build.slots.PSU=cat('PSU','Corsair RM850x 850W Gold');am5Build.slots.STORAGE=cat('STORAGE','Samsung 990 Pro 2TB NVMe');am5Build.slots.CASE=cat('CASE','Fractal Design Meshify 2');am5Build.slots.COOLER=cat('COOLER','Noctua NH-D15');
  const am5Integrity=rigIntegrity(am5Build);
  out.push(['AM5 build integrity resolves SOUND with DDR5', am5Integrity.state==='SOUND']);
  const am5BuildCheck=buildCheckModel(am5Build);
  out.push(['AM5 build check passes RAM_PLATFORM with DDR5', am5BuildCheck.findings.some(f=>f.id==='RAM_PLATFORM'&&f.status==='PASS')]);
  const am5Profile=rigHardwareProfile(am5Build);
  out.push(['AM5 build profiling succeeds', !!(am5Profile&&am5Profile.complete)]);
  out.push(['AM5 build resolves LEGENDARY tier with RTX 5070 Ti', !!(am5Profile.complete&&am5Profile.tierIndex>=5)]);
  const storageRig=example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  const hdd=HardwareCatalog.storage.find(e=>e.drive_type==='HDD'&&e.capacity_gb===2000),gen4=HardwareCatalog.storage.find(e=>e.drive_type==='NVMe SSD'&&/PCIe 4/.test(e.interface));
  storageRig.slots.STORAGE=cat('STORAGE',hdd.brand+' '+hdd.model);
  storageRig.slots.STORAGE2=cat('STORAGE2',gen4.brand+' '+gen4.model);
  const storageWarnings=rigWarnings(storageRig);
  out.push(['primary and secondary storage slots are distinct', RIG_SLOT_LABELS.STORAGE==='Primary Storage'&&RIG_SLOT_LABELS.STORAGE2==='Storage 2']);
  out.push(['HDD-only primary warning fires', storageWarnings.some(w=>w.includes('HDD-ONLY PRIMARY'))]);
  out.push(['newer NVMe on older platform is compatible but speed limited', storageWarnings.some(w=>w.includes('COMPATIBLE — PCIe SPEED LIMITED'))]);
  const storageEditor=renderRigSlotRow('STORAGE2',storageRig);
  out.push(['secondary storage shows role-specific suitability', storageEditor.includes('Secondary ')&&storageEditor.includes('Bulk ')&&storageEditor.includes('Archive ')]);

  HardwareCatalog.cases = canonicalCases.cases;
  HardwareCatalog.coolers = canonicalCoolers.coolers;
  out.push(['canonical case catalog is loaded with 24 entries', HardwareCatalog.cases.length === 24]);
  out.push(['canonical cooler catalog is loaded with 24 entries', HardwareCatalog.coolers.length === 24]);
  out.push(['case catalog searches brand + model', catalogSearch('CASE','Lancool 216').some(e => e.brand === 'Lian Li' && e.model === 'Lancool 216')]);
  out.push(['cooler catalog searches brand + model', catalogSearch('COOLER','NH-D15').some(e => e.brand === 'Noctua' && e.caps.type === 'DUAL TOWER')]);
  out.push(['cooler and case names receive restrained category-aware tiers', pnPartNameTier({category:'COOLING',manufacturer:'Noctua',model:'NH-D15'}).key==='LEGENDARY'&&pnPartNameTier({category:'CASE',manufacturer:'Lian Li',model:'Lancool 216'}).key==='RARE'&&pnPartNameHtml({category:'COOLING',manufacturer:'Noctua',model:'NH-D15'}).includes('pn-part-name-subtle')]);
  const hydCase = {kind:'PLANNED',catalogType:'CASE',catalogKey:null,label:'Fractal Design Meshify 2',cost:0,currency:'RSD'};
  const hydCC = caseCapabilities(hydCase,'Fractal Design Meshify 2');
  out.push(['case capabilities hydrate from the canonical catalog', hydCC && hydCC.maxGpuLengthMm === 355 && hydCC.airflow === 'EXCELLENT' && hydCase.source === 'CATALOG' && hydCase.catalogKey === 'CASE:FRACTAL DESIGN MESHIFY 2']);
  const encRig = example('AMD Ryzen 5 3600','NVIDIA RTX 2060 6GB','MSI B450 TOMAHAWK MAX');
  encRig.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'NZXT H510',cost:0,currency:'RSD'};
  encRig.slots.COOLER = {kind:'CATALOG',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,currency:'RSD'};
  const caseSlotHtml = renderRigSlotRow('CASE',encRig);
  out.push(['CASE slot renders the enclosure editor', caseSlotHtml.includes('data-rig-generic="CASE"') && caseSlotHtml.includes('data-rig-cap-field="CASE.maxGpuLengthMm"') && caseSlotHtml.includes('data-rig-catalog-item="CASE"')]);
  const coolerSlotHtml = renderRigSlotRow('COOLER',encRig);
  out.push(['COOLER slot renders the compact final component editor', coolerSlotHtml.includes('COOLER DETAILS / ADVANCED') && coolerSlotHtml.includes('data-rig-cap-field="COOLER.coolingClass"') && coolerSlotHtml.includes('data-rig-catalog-item="COOLER"') && coolerSlotHtml.includes('FIT:')]);
  out.push(['COOLER UI omits nonessential technical fields', !/TDP class|Fan count|Noise class|RAM clearance|Heatpipe|Pump speed/i.test(coolerSlotHtml)]);
  out.push(['legacy cooler catalog values normalize to AIR and BASIC/MID/HIGH', (function(){const c=normalizeCoolerCaps({type:'DUAL TOWER',coolingClass:'EXTREME'});return c.type==='AIR'&&c.coolingClass==='HIGH'})()]);

  function cat2(type,label){ return {kind:'CATALOG',catalogType:type,label,cost:0,originalPrice:0,currency:'RSD'}; }
  function goodRig(){
    const r = newRigDraft('INTG');
    r.slots.CPU = cat2('CPU','AMD Ryzen 5 3600');
    r.slots.GPU = cat2('GPU','NVIDIA GTX 1650 4GB GDDR5 280mm');
    r.slots.MOBO = cat2('MOBO','ASRock B450M-HDV');
    r.slots.RAM = {kind:'PLANNED',catalogType:'RAM',label:'DDR4 test kit',cost:0,originalPrice:0,currency:'RSD',ram:{moduleCount:2,perModuleCapacity:8,totalCapacity:16,speed:3200,casLatency:16}};
    r.slots.CASE = {kind:'CATALOG',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,originalPrice:0,currency:'RSD'};
    r.slots.COOLER = {kind:'PLANNED',catalogType:'COOLER',label:'Noctua NH-D15',cost:0,originalPrice:0,currency:'RSD',caps:{type:'DUAL TOWER',radiator:null,heightMm:160,sockets:['AM4','AM5','LGA1200','LGA1700'],coolingClass:'EXTREME',fanCount:2,noiseClass:'NORMAL',tdpClass:'EXTREME',ramClearance:'NO',notes:''}};
    r.slots.PSU = cat2('PSU','BeQuiet Pure Power 750W');
    r.slots.STORAGE = {kind:'PLANNED',label:'NVMe SSD 1TB',cost:0,originalPrice:0,currency:'RSD'};
    return r;
  }
  const moboSlotHtml=renderRigSlotRow('MOBO',goodRig());
  out.push(['motherboard slot exposes canonical form, socket and chipset compactly', moboSlotHtml.includes('FORM mATX · SOCKET AM4 · CHIPSET B450')]);
  out.push(['canonical Micro-ATX board fits a case supporting mATX and ATX', rigIntegrity(goodRig()).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='PASS'&&c.detail.includes('mATX motherboard'))]);
  const atxMismatch=goodRig();atxMismatch.slots.MOBO=cat2('MOBO','Gigabyte GA-A320-DS3');atxMismatch.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'mATX-only case',cost:0,originalPrice:0,currency:'RSD',source:'MANUAL',caps:{formFactors:['ITX','MATX']}};
  out.push(['canonical ATX board fails a case limited to mATX', rigIntegrity(atxMismatch).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='FAIL')]);
  const unknownMoboSize=goodRig();unknownMoboSize.slots.MOBO=cat2('MOBO','Mystery Z999M-K');
  out.push(['uncataloged M-style motherboard name remains UNVERIFIED', rigIntegrity(unknownMoboSize).checks.some(c=>c.id==='MOBO_FORM_FACTOR'&&c.status==='UNVERIFIED')]);
  HardwareCatalog.psus = [
    {brand:'BeQuiet',model:'Pure Power 750W',wattage_w:750,quality_score:90,quality_class:'GOLD',safety_status:'ACCEPTABLE',connector_data_confidence:'OFFICIAL',pcie_6_2_connectors:6,pcie_16pin_connectors:0,atx_spec:'ATX'},
    {brand:'Montech',model:'CENTURY 550W',wattage_w:550,quality_score:84,quality_class:'STRONG',safety_status:'APPROVED',connector_data_confidence:'DERIVED',pcie_6_2_connectors:2,pcie_16pin_connectors:0,atx_spec:'ATX 2.52'}
  ];
  const perfectIt = rigIntegrity(goodRig());
  out.push(['fully-characterized build judges BUILD INTEGRITY EXCELLENT', perfectIt.state === 'EXCELLENT']);
  out.push(['EXCELLENT build has every present check PASS or informational', perfectIt.checks.every(c => c.status === 'PASS' || c.status === 'INFO') && perfectIt.checks.filter(c => c.status === 'WARN' || c.status === 'FAIL').length === 0]);
  const socketFail=goodRig();socketFail.slots.COOLER.caps.sockets=['LGA1700'];
  out.push(['incompatible cooler socket is a confirmed FAIL', rigIntegrity(socketFail).checks.some(c=>c.id==='CPU_SOCKET'&&c.status==='FAIL')]);
  const weakCooler=goodRig();weakCooler.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');weakCooler.slots.COOLER.caps.coolingClass='BASIC';
  out.push(['obviously inadequate cooler is a WARNING, not a compatibility FAIL', rigIntegrity(weakCooler).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='WARN')]);
  const noRequiredCooler=goodRig();noRequiredCooler.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');noRequiredCooler.slots.COOLER=null;
  out.push(['missing cooler for a CPU that requires one is a confirmed FAIL', rigIntegrity(noRequiredCooler).checks.some(c=>c.id==='MISSING_COOLER'&&c.status==='FAIL')&&buildCheckModel(noRequiredCooler).verdict==='FAIL']);
  const bundledStock=goodRig();bundledStock.slots.COOLER=null;
  out.push(['adequate bundled stock cooling is accepted without an aftermarket cooler', rigIntegrity(bundledStock).checks.some(c=>c.id==='MISSING_COOLER'&&c.status==='PASS')]);
  const tallAir=goodRig();tallAir.slots.COOLER.caps.heightMm=220;
  out.push(['air cooler over the case height limit is a confirmed FAIL', rigIntegrity(tallAir).checks.some(c=>c.id==='COOLER_HEIGHT'&&c.status==='FAIL')]);
  const badAio=goodRig();badAio.slots.CASE.caps={formFactors:['MATX','ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:180,psuSupport:'ATX',radiator:{front:'240',top:'240',rear:'120'},airflow:'GOOD'};badAio.slots.COOLER.caps={type:'AIO',radiator:'360',heightMm:null,sockets:['AM4'],coolingClass:'HIGH'};
  out.push(['unsupported AIO radiator size is a confirmed FAIL', rigIntegrity(badAio).checks.some(c=>c.id==='RADIATOR_FIT'&&c.status==='FAIL')]);
  const stronger=goodRig();stronger.slots.CPU=cat2('CPU','AMD Ryzen 3 3100');stronger.slots.COOLER.caps.coolingClass='HIGH';
  out.push(['stronger cooling than required passes without warning', rigIntegrity(stronger).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='PASS')&&!rigIntegrity(stronger).checks.some(c=>c.id==='COOLER_SUFFICIENCY'&&c.status==='WARN')]);
  const coolerTierA=goodRig(),coolerTierB=goodRig();coolerTierA.slots.COOLER.caps.coolingClass='BASIC';coolerTierB.slots.COOLER.caps.coolingClass='HIGH';
  out.push(['cooler strength cannot promote rig performance or Gear Tier', rigHardwareProfile(coolerTierA).performance===rigHardwareProfile(coolerTierB).performance&&rigHardwareProfile(coolerTierA).tier===rigHardwareProfile(coolerTierB).tier]);
  const oversized = goodRig();
  oversized.slots.GPU = cat2('GPU','NVIDIA RTX 3080 10GB 500mm');
  const marginalIt = rigIntegrity(oversized);
  out.push(['GPU beyond the case envelope judges MARGINAL with a clearance WARN', marginalIt.state === 'MARGINAL' && marginalIt.checks.some(c => c.id === 'GPU_CLEARANCE' && c.status === 'WARN')]);
  const plain = goodRig();
  plain.slots.CASE = {kind:'PLANNED',label:'Generic steel case',cost:0,originalPrice:0,currency:'RSD'};
  plain.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD'};
  const unknownIt = rigIntegrity(plain);
  out.push(['unknown enclosure stays SOUND — UNKNOWN is never INCOMPATIBLE', unknownIt.state === 'SOUND' && unknownIt.checks.every(c => c.status !== 'WARN')]);
  out.push(['unreadable GPU length grades UNVERIFIED rather than failing the build', unknownIt.checks.find(c => c.id === 'GPU_CLEARANCE').status === 'UNVERIFIED']);
  const dec = example('AMD Ryzen 7 5800X3D','NVIDIA RTX 3080 10GB','ASRock X570 Taichi');
  const perfBefore = rigHardwareProfile(dec).performance;
  dec.slots.CASE = {kind:'PLANNED',label:'NZXT H510',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:160,psuSupport:'ATX',radiator:{front:'none',top:'240',rear:'none'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'steel',notes:''}};
  dec.slots.COOLER = {kind:'PLANNED',label:'Tower cooler',cost:0,originalPrice:0,currency:'RSD',caps:{type:'SINGLE TOWER',radiator:null,heightMm:155,sockets:[],coolingClass:'STANDARD',fanCount:1,noiseClass:'NORMAL',tdpClass:'STANDARD',ramClearance:'NO',notes:''}};
  dec.slots.PSU = {kind:'PLANNED',label:'Corsair 750W',cost:0,originalPrice:0,currency:'RSD'};
  out.push(['MARGINAL enclosure profile never changes the CPU/GPU/MOBO performance score', rigHardwareProfile(dec).performance === perfBefore && rigIntegrity(dec).state === 'MARGINAL']);
  out.push(['integrity findings no longer duplicate into rigWarnings', !rigWarnings(oversized).some(w => w.includes('GPU EXCEEDS CASE CLEARANCE'))]);
  const passModel=buildCheckModel(goodRig());
  out.push(['Build Check PASS-only build resolves compatible and completely verified', passModel.verdict==='PASS'&&passModel.compatibility==='PASS'&&passModel.verification==='COMPLETE'&&passModel.counts.PASS>0&&passModel.counts.UNVERIFIED===0&&passModel.counts.WARN===0&&passModel.counts.FAIL===0]);
  const unverifiedModel=buildCheckModel(plain);
  out.push(['Build Check PASS + UNVERIFIED remains compatible but partial', unverifiedModel.verdict==='PASS'&&unverifiedModel.compatibility==='PASS'&&unverifiedModel.verification==='PARTIAL'&&unverifiedModel.counts.PASS>0&&unverifiedModel.counts.UNVERIFIED>0&&unverifiedModel.counts.WARN===0&&unverifiedModel.counts.FAIL===0]);
  const warningRig=goodRig();warningRig.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Airflow test case',cost:0,originalPrice:0,currency:'RSD',caps:{formFactors:['MATX','ATX'],maxGpuLengthMm:400,maxCoolerHeightMm:180,psuSupport:'ATX',radiator:{front:'360',top:'280',rear:'120'},airflow:'POOR',buildQuality:'SOLID',sidePanel:'mesh',notes:''}};
  const warningModel=buildCheckModel(warningRig);
  out.push(['Build Check PASS + WARNING resolves WARNING', warningModel.verdict==='WARNING'&&warningModel.compatibility==='WARNING'&&warningModel.counts.WARN>0&&warningModel.counts.FAIL===0]);
  const failModel=buildCheckModel(oversized);
  out.push(['Build Check confirmed incompatibility resolves FAIL', failModel.verdict==='FAIL'&&failModel.compatibility==='FAIL'&&failModel.counts.FAIL>0]);
  const mixedRig=goodRig();mixedRig.slots.GPU=cat2('GPU','NVIDIA RTX 3080 10GB 500mm');mixedRig.slots.PSU={kind:'PLANNED',catalogType:'PSU',label:'Unknown 750W PSU',cost:0,originalPrice:0,currency:'RSD'};
  const mixedModel=buildCheckModel(mixedRig);
  out.push(['Build Check mixed FAIL + UNVERIFIED stays FAIL', mixedModel.verdict==='FAIL'&&mixedModel.counts.FAIL>0&&mixedModel.counts.UNVERIFIED>0]);
  out.push(['Build Check prevents duplicate messages', new Set(failModel.findings.map(f=>pnNorm(f.id+' '+f.detail))).size===failModel.findings.length]);
  state.rigDraft=oversized;const failHtml=renderBuildCheck();
  out.push(['contradictory severity states stay impossible against a socket-clash build', (function(){const r=goodRig();r.slots.CPU=cat2('CPU','AMD Ryzen 5 7600');r.slots.MOBO=cat2('MOBO','ASRock B550M-HDV');const m=buildCheckModel(r);return m.verdict==='FAIL'&&m.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='FAIL')})()]);
  state.rigDraft=plain;const unverifiedHtml=renderBuildCheck();
  out.push(['PASS/UNVERIFIED Build Check details default collapsed', !/<details class="pn-bc-details" open/.test(unverifiedHtml)]);
  out.push(['Build Check renders compatibility and verification as separate axes', unverifiedHtml.includes('data-build-check-verdict="PASS"')&&unverifiedHtml.includes('data-build-check-verification="PARTIAL"')&&unverifiedHtml.includes('COMPATIBILITY')&&unverifiedHtml.includes('VERIFICATION')]);
  out.push(['case advanced capabilities default collapsed', caseSlotHtml.includes('<summary>CASE CAPABILITIES / ADVANCED</summary>')&&!caseSlotHtml.includes('<details class="pn-cap-details" open>')]);
  const scenarios=[['PASS',goodRig()],['PASS',plain],['WARNING',warningRig],['FAIL',oversized]];
  out.push(['complete Build Check scenario matrix renders the same overall state as its model', scenarios.every(([expected,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck();return model.verdict===expected&&html.includes('data-build-check-verdict="'+expected+'"')} )]);
  out.push(['contradictory Build Check severity states are impossible', scenarios.every(([,rig])=>{const model=buildCheckModel(rig),expected=model.counts.FAIL?'FAIL':model.counts.WARN?'WARNING':(model.counts.PASS||model.counts.INFO)?'PASS':'UNVERIFIED';return model.verdict===expected} )]);
  const clash=goodRig();clash.slots.CPU=cat2('CPU','AMD Ryzen 5 7600');clash.slots.MOBO=cat2('MOBO','ASRock B550M-HDV');
  const clashModel=buildCheckModel(clash);state.rigDraft=clash;const clashHtml=renderBuildCheck();
  out.push(['socket clash is a genuine incompatibility', clashModel.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='FAIL')&&clashModel.verdict==='FAIL']);
  out.push(['socket clash routes into the Build Integrity tile with visible FAIL detail', (function(){const seg=clashHtml.slice(clashHtml.indexOf('data-bc-tile="build-integrity"'),clashHtml.indexOf('data-bc-tile="psu"')),levels=[...seg.matchAll(/data-bc-level="([^"]+)"/g)].map(m=>m[1]);return seg.includes('Build Integrity')&&levels.includes('FAIL')&&clashHtml.includes('motherboard platform')})()]);
  const verdicts=scenarios.map(([,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck(),tileLevels=[...html.matchAll(/pn-bc-chip pn-bc-status(?: is-partial)?" data-bc-level="([^"]+)"/g)].map(m=>m[1]),expected=model.counts.FAIL?'FAIL':model.counts.WARN?'WARNING':(model.counts.PASS||model.counts.INFO)?'PASS':'UNVERIFIED';return tileLevels.length===5&&model.verdict===expected&&(model.counts.FAIL>0)===tileLevels.includes('FAIL')&&(model.counts.WARN>0)===tileLevels.includes('WARN')&&!(!model.counts.FAIL&&!model.counts.WARN)===tileLevels.some(l=>l==='FAIL'||l==='WARN')});
  out.push(['each FAIL/WARN finding lands in exactly one tile and the five tile chips mirror the verdict', verdicts.every(Boolean)&&scenarios.every(([,rig])=>{state.rigDraft=rig;const model=buildCheckModel(rig),html=renderBuildCheck();return model.findings.filter(f=>f.status==='FAIL'||f.status==='WARN').every(f=>html.includes(f.detail))})]);
  const reserve=goodRig();reserve.slots.PSU={kind:'PLANNED',label:'Unknown wattage PSU',cost:0,originalPrice:0,currency:'RSD'};
  const reserveModel=buildCheckModel(reserve);state.rigDraft=reserve;const reserveHtml=renderBuildCheck();
  out.push(['unreadable PSU wattage stays UNVERIFIED and never hard-fails the build', reserveModel.verdict==='PASS'&&reserveModel.counts.UNVERIFIED>0&&reserveModel.counts.FAIL===0&&reserveHtml.includes('UNVERIFIED</span>')]);
  const viable=goodRig();viable.expectedSalePrice=100000;
  const shopStates=[rigOperatorRead(viable,rigDerived(viable),buildCheckModel(viable)).title,rigOperatorRead(plain,rigDerived(plain),buildCheckModel(plain)).title,rigOperatorRead(warningRig,rigDerived(warningRig),buildCheckModel(warningRig)).title,rigOperatorRead(oversized,rigDerived(oversized),buildCheckModel(oversized)).title];
  out.push(['SHOP READ explains good, unknown, warning and incompatible complete states', shopStates.join('|')==='READY TO ASSEMBLE|SET SALE TARGET|REVIEW BEFORE ASSEMBLY|HOLD BUILD']);
  const assembled=JSON.parse(JSON.stringify(viable));assembled.status='ASSEMBLED';const sold=JSON.parse(JSON.stringify(viable));sold.status='SOLD';
  out.push(['SHOP READ covers assembled and sold operational states', rigOperatorRead(assembled,rigDerived(assembled),buildCheckModel(assembled)).title==='SELLING CANDIDATE'&&rigOperatorRead(sold,rigDerived(sold),buildCheckModel(sold)).title==='SALE CLOSED']);
  const valueRig=goodRig();valueRig.id='VALUE';valueRig.status='TEST_BUILD';valueRig.slots.CPU.cost=20000;valueRig.expectedSalePrice=50000;
  const performanceRig=goodRig();performanceRig.id='PERFORMANCE';performanceRig.slots.CPU=cat2('CPU','AMD Ryzen 7 5800X3D');performanceRig.slots.CPU.cost=30000;performanceRig.expectedSalePrice=100000;
  const familyRanks=rigVariantRankings([valueRig,performanceRig]);
  out.push(['family ranking identifies active, cheapest, fastest and best-margin variants', familyRanks.activeId==='VALUE'&&familyRanks.cheapestId==='VALUE'&&familyRanks.fastestId==='PERFORMANCE'&&familyRanks.bestMarginId==='PERFORMANCE']);
  out.push(['family ranking badges expose the decision hierarchy', rigRankBadges(valueRig,familyRanks).includes('ACTIVE')&&rigRankBadges(valueRig,familyRanks).includes('CHEAPEST')&&rigRankBadges(performanceRig,familyRanks).includes('BEST PERFORMANCE')&&rigRankBadges(performanceRig,familyRanks).includes('BEST MARGIN')]);
  const weakRig=goodRig();weakRig.id='WEAK';weakRig.status='TEST_BUILD';weakRig.slots.CPU.cost=20000;weakRig.expectedSalePrice=15000;
  const healthy=goodRig();healthy.id='HEALTHY';healthy.slots.CPU.cost=20000;healthy.expectedSalePrice=120000;
  const recCheck=rigFamilyRecommendation([weakRig,healthy]);
  out.push(['family recommendation skips a weak deal and names the viable variant', !!(recCheck&&recCheck.id==='HEALTHY')]);
  out.push(['family recommendation prefers an assembled selling candidate', (function(){const a=JSON.parse(JSON.stringify(healthy));a.id='ASSEMBLED_BUILD';a.status='ASSEMBLED';const p=goodRig();p.id='PLANNED_HIGHER';p.slots.CPU.cost=20000;p.expectedSalePrice=160000;const r=rigFamilyRecommendation([p,a]);return !!(r&&r.id==='ASSEMBLED_BUILD')})()]);
  out.push(['all-fail family produces no clear assembly candidate', rigFamilyRecommendation([weakRig,JSON.parse(JSON.stringify(weakRig))])===null]);
  out.push(['qualification chips expose the per-variant operational read', rigReadChip(healthy).includes('READY')&&rigReadChip(clash).includes('HOLD')&&rigReadChip(plain).includes('SET TARGET')&&rigReadChip(viable).includes('READY')]);
  const sanity=goodRig();sanity.slots.STORAGE={kind:'PLANNED',catalogType:'STORAGE',label:'Samsung 850 EVO 120GB',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.GPU=cat2('GPU','NVIDIA GTX 1070 8GB');
  sanity.slots.RAM={kind:'PLANNED',catalogType:'RAM',label:'Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:10000,originalPrice:0,currency:'RSD'};
  sanity.slots.COOLER={kind:'PLANNED',catalogType:'COOLER',label:'AMD Wraith Stealth',cost:0,originalPrice:0,currency:'RSD'};
  sanity.slots.PSU={kind:'PLANNED',catalogType:'PSU',label:'Montech Century 550W 80 Plus Gold',cost:7500,originalPrice:0,currency:'RSD'};
  sanity.expectedSalePrice=65000;
  const sanityModel=buildCheckModel(sanity),sanityRead=rigOperatorRead(sanity,rigDerived(sanity),sanityModel);
  out.push(['Ryzen5-3600 / B450M / GTX-1070 / 550W Gold reference build resolves PASS with no warnings and no failures', sanityModel.verdict==='PASS'&&sanityModel.counts.FAIL===0&&sanityModel.counts.WARN===0&&sanityModel.counts.PASS>0]);
  out.push(['the same reference build keeps only unavailable connector inventory unverified', sanityModel.counts.UNVERIFIED===1&&sanityModel.findings.some(f=>f.id==='PSU_CONNECTORS'&&f.status==='UNVERIFIED')]);
  out.push(['uncataloged planned parts complete the platform without breaking compatibility', sanityModel.findings.some(f=>f.id==='CPU_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='RAM_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='GPU_PLATFORM'&&f.status==='PASS')&&sanityModel.findings.some(f=>f.id==='STORAGE_INTERFACE'&&f.status==='PASS')]);
  out.push(['canonical B450M form factor fits the case without name parsing', sanityModel.findings.some(f=>f.id==='MOBO_FORM_FACTOR'&&f.status==='PASS')]);
  out.push(['bundled AMD stock cooling is positively verified, not treated as unknown', sanityModel.findings.some(f=>f.id==='COOLER_SUFFICIENCY'&&f.status==='PASS'&&f.detail.includes('OEM STOCK COOLING'))&&sanityModel.findings.some(f=>f.id==='COOLER_OPERATING_NOTE'&&f.status==='INFO')]);
  out.push(['reference build PSU wattage grades against the real GPU requirement', sanityModel.findings.some(f=>f.id==='PSU_WATTAGE'&&f.status==='PASS'&&f.detail.includes('RECOMMENDED'))]);
  out.push(['PSU checks preserve known capacity, requirement, quality and safety beside unknown connector inventory', ['PSU_CAPACITY','GPU_PSU_BASELINE','PSU_WATTAGE','GPU_CONNECTOR_REQUIREMENT','PSU_QUALITY','PSU_SAFETY'].every(id=>sanityModel.findings.some(f=>f.id===id&&f.status==='PASS'))&&sanityModel.findings.some(f=>f.id==='PSU_CONNECTORS'&&f.status==='UNVERIFIED')]);
  out.push(['generic GTX 1070 envelope verifies comfortable clearance without pretending to know an exact card length', sanityModel.findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='PASS'&&f.detail.includes('generic envelope'))]);
  out.push(['uncataloged planned parts are clear work notes, never operational warnings', sanityModel.counts.WARN===0&&sanityRead.title==='READY TO ASSEMBLE'&&sanityRead.detail.includes('remain unverified')&&sanityRead.tone==='pass'&&rigReadChip(sanity).includes('READY')]);
  state.rigDraft=sanity;const sanityHtml=renderBuildCheck();state.rigDraft=null;
  out.push(['reference build renders a calm Build Check dashboard', sanityHtml.includes('data-build-check-verdict="PASS"')&&!/data-bc-level="(WARN|FAIL)"/.test(sanityHtml)&&sanityHtml.includes('NOTES <b>3</b>')&&!/<details class="pn-bc-details" open/.test(sanityHtml)]);
  out.push(['PSU tile exposes six verified sub-checks and its one honest unknown', sanityHtml.includes('data-bc-tile="psu" data-bc-pass="6" data-bc-unverified="1"')&&sanityHtml.includes('6 PASS / 1 UNVERIFIED')&&sanityHtml.includes('data-bc-finding="PSU_WATTAGE" data-bc-level="PASS"')&&sanityHtml.includes('data-bc-finding="PSU_CONNECTORS" data-bc-level="UNVERIFIED"')]);
  const genericCase=JSON.parse(JSON.stringify(sanity));genericCase.slots.CASE={kind:'PLANNED',catalogType:'CASE',label:'Generic ATX Airflow Case',genericId:'generic-atx-airflow',cost:0,originalPrice:0,currency:'RSD'};
  const genericCaseModel=buildCheckModel(genericCase);state.rigDraft=genericCase;const genericCaseHtml=renderBuildCheck();state.rigDraft=null;
  out.push(['generic ATX case independently verifies motherboard, cooler and conservative GPU envelope fit', ['MOBO_FORM_FACTOR','COOLER_HEIGHT','GPU_CLEARANCE'].every(id=>genericCaseModel.findings.some(f=>f.id===id&&f.status==='PASS'))&&genericCaseHtml.includes('data-bc-tile="fit" data-bc-pass="3" data-bc-unverified="0"')]);
  const closeGpuCase=JSON.parse(JSON.stringify(genericCase));closeGpuCase.slots.CASE.caps={formFactors:['ITX','MATX','ATX'],maxGpuLengthMm:305,maxCoolerHeightMm:160,psuSupport:'ATX',radiator:{front:'280',top:'240',rear:'120'},airflow:'GOOD'};closeGpuCase.slots.CASE.source='MANUAL';
  out.push(['generic GPU envelope near the case limit requests the exact card model', buildCheckModel(closeGpuCase).findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='UNVERIFIED'&&f.detail.includes('exact card model required'))]);
  const exactGpuCase=JSON.parse(JSON.stringify(closeGpuCase));exactGpuCase.slots.GPU=cat2('GPU','NVIDIA GTX 1070 8GB 320mm');
  out.push(['exact selected-card dimensions override the family envelope and can confirm a clearance failure', buildCheckModel(exactGpuCase).findings.some(f=>f.id==='GPU_CLEARANCE'&&f.status==='FAIL'&&f.detail.includes('320 mm GPU'))]);
  out.push(['every reference-build finding lands in exactly one tile and cooling never leaks into core integrity', (function(){const sets=bcTileSets(sanityModel.findings),flat=[];Object.keys(sets).forEach(k=>flat.push(...sets[k]));return new Set(flat.map(f=>f.id)).size===flat.length&&flat.length===sanityModel.findings.length&&(sets.cooling||[]).some(f=>f.id==='COOLER_SUFFICIENCY')&&!(sets.integrity||[]).some(f=>f.id==='COOLER_SUFFICIENCY')&&!(sets.integrity||[]).some(f=>/COOLER|COOLING/.test(f.id))})()]);

  const plainTxt=rigExportBuildText(sanity,'plain'),aiTxt=rigExportBuildText(sanity,'ai');
  out.push(['COPY BUILD export carries the build identity, tier, status and completeness', plainTxt.includes('PROFITNODE RIG BUILD EXPORT')&&plainTxt.includes('BUILD NAME: INTG · MAIN')&&plainTxt.includes('BUILD TIER: ')&&plainTxt.includes('BUILD STATUS: PLANNED')&&plainTxt.includes('HARDWARE: COMPLETE')&&plainTxt.includes('SALE READY: NO')]);
  out.push(['COPY BUILD export lists every component and no missing parts', ['CPU:','GPU:','Motherboard:','RAM:','PSU:','Case:','Cooler:','Primary Storage:'].every(s=>plainTxt.includes(s))&&plainTxt.includes('AMD Ryzen 5 3600')&&plainTxt.includes('NVIDIA GTX 1070 8GB')&&plainTxt.includes('MISSING PARTS:')&&plainTxt.includes('  NONE')&&!plainTxt.includes('REVIEW REQUEST')]);
  out.push(['COPY BUILD export embeds both Build Check axes and the shop read', plainTxt.includes('BUILD CHECK:')&&plainTxt.includes('COMPATIBILITY: COMPATIBLE')&&plainTxt.includes('VERIFICATION: PARTIAL')&&plainTxt.includes('COMPATIBLE')&&plainTxt.includes('SHOP READ:')&&plainTxt.includes('READY TO ASSEMBLE')&&plainTxt.includes('NOTES:')]);
  out.push(['COPY FOR AI REVIEW appends the seven-point review request', aiTxt.includes('REVIEW REQUEST:')&&aiTxt.split(String.fromCharCode(10)).filter(l=>/^ {2}[1-7]. /.test(l)).length===7&&aiTxt.includes('1. Rate this build 1-10')&&aiTxt.includes('7. What changes would you make before assembly to maximize resale value?')]);
  out.push(['COPY FOR AI REVIEW adds hardware metadata with honest statuses', aiTxt.includes('Socket: AM4')&&aiTxt.includes('Chipset: B450')&&aiTxt.includes('RAM type: DDR4')&&aiTxt.includes('Wattage: 550 W')&&aiTxt.includes('GPU limit: 355 mm')&&aiTxt.includes('Connectors: 1x8-pin')&&aiTxt.includes('Estimated power: 150 W')&&aiTxt.includes('UNVERIFIED')&&aiTxt.includes('COMPATIBLE')]);
  out.push(['COPY FOR AI REVIEW carries prices and business metrics', aiTxt.includes('PRICES:')&&aiTxt.includes('Total paid:')&&aiTxt.includes('Expected sale price:')&&aiTxt.includes('Expected profit:')&&aiTxt.includes('ROI:')&&aiTxt.includes('Margin:')]);
  const gr=goodRig(),grAi=rigExportBuildText(gr,'ai');
  out.push(['AI export reports catalog-grade PSU, cooler and GPU detail', grAi.includes('Wattage: 750 W')&&grAi.includes('Quality: 90 / 100 GOLD')&&grAi.includes('Type: AIR')&&grAi.includes('Height: 160 mm')&&grAi.includes('Sockets: AM4 / AM5 / LGA1200 / LGA1700')&&grAi.includes('Length: 280 mm')&&grAi.includes('Config: 2x8 GB')&&grAi.includes('Speed: 3200 MT/s')&&grAi.includes('XMP: UNKNOWN')]);
  const bare=newRigDraft('BARE');bare.slots.CPU=cat2('CPU','AMD Ryzen 5 3600');
  const bareTxt=rigExportBuildText(bare,'plain');
  out.push(['incomplete build export flags every missing part and no tier', bareTxt.includes('BUILD TIER: —')&&bareTxt.includes('HARDWARE: INCOMPLETE')&&['- GPU','- Motherboard','- RAM','- PSU','- Case','- Cooler','- Primary Storage'].every(m=>bareTxt.includes(m))&&bareTxt.includes('VIDEO OUTPUT: WARNING')&&bareTxt.includes('REVIEW BEFORE ASSEMBLY')]);
  out.push(['export reflects the live draft, never a canned snapshot', rigExportBuildText(sanity,'plain')!==rigExportBuildText(clash,'plain')&&rigExportBuildText(sanity,'ai')!==rigExportBuildText(sanity,'plain')]);
  out.push(['Build Check head exposes the EXPORT BUILD dropdown with both copy modes', sanityHtml.includes('EXPORT BUILD')&&sanityHtml.includes('pn-bc-export-panel')&&sanityHtml.includes('data-rig-export="plain"')&&sanityHtml.includes('data-rig-export="ai"')&&sanityHtml.includes('COPY BUILD')&&sanityHtml.includes('COPY FOR AI REVIEW')]);
  out.push(['SALE READY flips YES only for an assembled selling candidate', rigExportBuildText(Object.assign({},sanity,{status:'ASSEMBLED'}),'plain').includes('SALE READY: YES')&&rigExportBuildText(Object.assign({},sanity,{status:'SOLD'}),'plain').includes('SALE READY: NO')&&bareTxt.includes('SALE READY: NO')]);
  out.push(['AI export names the exact catalog GPU model when it differs from the label', grAi.includes('Model: GTX 1650 4GB GDDR5')]);
  const invGpu=Store.insert('inventory',{category:'GPU',manufacturer:'MSI',model:'GTX 1650 Ventus',purchasePrice:2300,currency:'RSD',estimatedMarketValue:3400,condition:'FAULTY',status:'IN_STORAGE'});
  const invSsd=Store.insert('inventory',{category:'STORAGE',manufacturer:'Kingston',model:'A400 240GB SATA SSD',purchasePrice:2500,currency:'RSD',estimatedMarketValue:3200,condition:'WORKING',status:'IN_STORAGE',driveHealthPercent:82});
  const invRig=goodRig();invRig.slots.GPU={kind:'INVENTORY',inventoryItemId:invGpu.id};invRig.slots.STORAGE={kind:'INVENTORY',inventoryItemId:invSsd.id};
  const invAi=rigExportBuildText(invRig,'ai');
  out.push(['AI export carries per-part condition only where the ledger tracks it', invAi.includes('Condition: FAULTY')&&invAi.includes('Condition: WORKING')&&!grAi.includes('Condition:')]);
  out.push(['AI export reports case fan configuration from the catalog', invAi.includes('Fans: 2 included · 9 positions')]);
  out.push(['AI export reports storage health only when the ledger tracks it', invAi.includes('Health: 82%')&&!grAi.includes('Health:')]);
  out.push(['warning text is compressed: a note that repeats a build-check detail appears once', (function(){const noStor=goodRig();delete noStor.slots.STORAGE;const t=rigExportBuildText(noStor,'ai');return (t.split('No primary storage selected.').length-1)===1&&t.includes('COMPLETENESS: UNVERIFIED — No primary storage selected.')&&!t.includes('BALANCE & OPERATIONAL NOTES')})()]);
  out.push(['connector uncertainty is not repeated between the PSU/GPU block and Build Check', (invAi.split('No GPU connector baseline available.').length-1)===1&&invAi.includes('  Status: UNVERIFIED')&&!invAi.includes('  Connectors: No GPU connector baseline available.')]);
  out.push(['build-check detail lines stay within a concise length bound', (function(){const NL=String.fromCharCode(10),re=/^  [A-Z0-9 ()&-]+: (COMPATIBLE|WARNING|FAIL|UNVERIFIED|NOTE)( —|$)/;return [aiTxt,grAi,invAi].every(t=>t.split(NL).filter(l=>re.test(l)).every(l=>l.length<=160))})()]);

  HardwareCatalog.cases = [];
  HardwareCatalog.coolers = [];
  const missingCaseCaps = caseCapabilities({kind:'PLANNED',catalogType:'CASE',label:'Fractal Design Meshify 2',cost:0,currency:'RSD'},'Fractal Design Meshify 2');
  out.push(['missing case catalog degrades to UNVERIFIED, never a hard fail', missingCaseCaps === null && rigIntegrity(plain).state === 'SOUND']);

  /* ---- NVMe recognition + rating registry: merge, alias resolution, PC601 sanity ---- */
  out.push(['NVMe registry counts match the handoff spec (412 new families / 1311 new models / 179 aliases)', canonicalNvmeRegistry.family_count_new===412&&canonicalNvmeRegistry.model_count_new===1311&&canonicalNvmeRegistry.alias_count===179&&canonicalNvmeRegistry.models.length===1311&&canonicalNvmeRegistry.aliases.length===179]);
  const scoredStorage = canonicalStorage.entries.map(e=>Object.assign({overall:e.overall_score,pn_tier:tierName(storageGearTier(e))},e));
  const recognitionStorage = canonicalNvmeRegistry.models.map(e=>Object.assign({overall:e.overall_score,pn_tier:tierName(storageGearTier(e))},e));
  HardwareCatalog.storage = mergeStorageCatalog(scoredStorage,recognitionStorage);
  const aliasBuild = buildStorageAliasIndex(HardwareCatalog.storage, canonicalNvmeRegistry);
  HardwareCatalog.storageAliasIndex = aliasBuild.index;
  HardwareCatalog.storageAliasPrefixes = aliasBuild.prefixes;
  HardwareCatalog.nvmeRegistryMeta = {familyCountNew: canonicalNvmeRegistry.family_count_new, modelCountNew: canonicalNvmeRegistry.model_count_new, aliasCount: canonicalNvmeRegistry.alias_count};
  HardwareCatalog.status = 'ready';
  out.push(['merged storage catalog preserves 1,325 scored rows plus 1,310 non-colliding recognition rows', HardwareCatalog.storage.length===2635]);
  out.push(['every recognition row that survives the merge now carries a real PN Score and tier from the full-rated package — no null ratings remain', HardwareCatalog.storage.filter(e=>e.registry_status==='new_recognition').every(e=>Number.isFinite(e.overall_score)&&null!==storageGearTier(e))]);
  out.push(['newly-rated recognition rows are tagged with an honest confidence level, never presented as lab-verified', HardwareCatalog.storage.filter(e=>e.registry_status==='new_recognition').every(e=>['ESTIMATED-HIGH','ESTIMATED-MEDIUM','ESTIMATED-LOW'].includes(e.rating_confidence))]);
  out.push(['pre-existing scored NVMe rows are untouched by the merge (970 EVO Plus 1TB still resolves with its real score)', (function(){const e=catalogFind('STORAGE','Samsung 970 EVO Plus 1TB');return e&&Number.isFinite(e.overall_score)&&storageGearTier(e)!==null})()]);
  const pc601_512 = catalogFind('STORAGE','SK hynix PC601 512GB');
  out.push(['the hand-verified SK hynix PC601 512GB catalog row wins over its full-rated-package duplicate, and neither source’s fictional Mass Effect label ("N7"/"GHOUL") leaks into the real tier', pc601_512&&pc601_512.brand==='SK hynix'&&pc601_512.series==='PC601'&&pc601_512.capacity_gb===512&&pc601_512.drive_type==='NVMe SSD'&&pnTier(storageGearTier(pc601_512))==='EPIC']);
  out.push(['exact OEM part number HFS512GD9TNG-L2A0A BA resolves to the PC601 512GB canonical entry', (function(){const e=catalogFind('STORAGE','HFS512GD9TNG-L2A0A BA');return e&&e.brand==='SK hynix'&&e.series==='PC601'&&e.capacity_gb===512})()]);
  out.push(['normalized OEM part number (no hyphen/case) still resolves the same PC601 512GB entry', (function(){const e=catalogFind('STORAGE','hfs512gd9tng l2a0a ba');return e&&e.series==='PC601'&&e.capacity_gb===512})()]);
  out.push(['Dell alias V4RWG resolves to the PC601 512GB entry the user actually owns', (function(){const e=catalogFind('STORAGE','V4RWG');return e&&e.series==='PC601'&&e.capacity_gb===512})()]);
  out.push(['Dell alias 0V4RWG resolves to the PC601 512GB entry', (function(){const e=catalogFind('STORAGE','0V4RWG');return e&&e.series==='PC601'&&e.capacity_gb===512})()]);
  out.push(['Dell alias KR-0V4RWG resolves to the PC601 512GB entry', (function(){const e=catalogFind('STORAGE','KR-0V4RWG');return e&&e.series==='PC601'&&e.capacity_gb===512})()]);
  out.push(['plain family+capacity search "PC601 512" also finds the same drive through ordinary token search', catalogSearch('STORAGE','PC601 512').some(e=>e.brand==='SK hynix'&&e.series==='PC601'&&e.capacity_gb===512)]);
  out.push(['exact part numbers are searchable (not just find-able) through catalogSearch', catalogSearch('STORAGE','V4RWG').some(e=>e.series==='PC601'&&e.capacity_gb===512)]);
  out.push(['a capacity-less family alias (PC601 NVMe) surfaces every PC601 capacity through search without collapsing them', (function(){const r=catalogSearch('STORAGE','PC601 NVMe');return r.length===3&&new Set(r.map(e=>e.capacity_gb)).size===3})()]);
  out.push(['catalogFind refuses to auto-collapse an ambiguous capacity-less alias to a single guess', catalogFind('STORAGE','PC601 NVMe')===null]);
  out.push(['a multi-family alias (Kingston OEM OM8/OM3/RBUS, one physical SKU) still resolves to exactly one entry', (function(){const e=catalogFind('STORAGE','OCP0S3512Q-A0');return e&&e.brand==='Kingston'&&e.capacity_gb===512})()]);
  out.push(['a prefix pattern alias (KBG3*) matches an observed part number by prefix', (function(){const e=catalogFind('STORAGE','KBG30ZMV256G');return e&&e.brand==='Kioxia'&&e.series==='BG3'&&e.capacity_gb===256})()]);
  out.push(['prefix alias search returns every capacity in the family when the query carries no capacity', (function(){const r=catalogSearch('STORAGE','KBG3XXXXXXX');return r.length===4&&r.every(e=>e.brand==='Kioxia'&&e.series==='BG3')})()]);
  out.push(['HOLD/unreleased exclusion still applies alongside the new alias path (no availability_status leak)', HardwareCatalog.storage.filter(e=>'DOCUMENTED_UNRELEASED'===e.availability_status).length===0]);
  const ratedRecognitionSample = HardwareCatalog.storage.find(e=>e.registry_status==='new_recognition');
  const ratedMeta = renderCatalogMeta('STORAGE', ratedRecognitionSample, null);
  out.push(['renderCatalogMeta renders a full-rated-package recognition row with its real performance and tier, never a placeholder', !/undefined|NaN/.test(ratedMeta) && !ratedMeta.includes('UNRATED') && !ratedMeta.includes('>—<')]);
  out.push(['pnConfidenceLabel maps every real rating_confidence value to a short human label, and anything else (including undefined) to null', pnConfidenceLabel('ESTIMATED-HIGH')==='Est. High' && pnConfidenceLabel('ESTIMATED-MEDIUM')==='Est. Medium' && pnConfidenceLabel('ESTIMATED-LOW')==='Est. Low' && pnConfidenceLabel(undefined)===null && pnConfidenceLabel('LAB_VERIFIED')===null]);
  out.push(['a bulk-estimated NVMe recognition row carries a visible confidence badge in the catalog dropdown, so it never looks identical to a lab-verified row', ratedMeta.includes('pn-confidence-pill') && ratedMeta.includes(pnConfidenceLabel(ratedRecognitionSample.rating_confidence))]);
  const lockedMeta = renderCatalogMeta('STORAGE', pc601_512, null);
  out.push(['the hand-verified, locked-catalog PC601 512GB row carries no confidence badge at all — it is not an estimate', !lockedMeta.includes('pn-confidence-pill')]);
  out.push(['pnConfidenceBadge stays silent (no stray title attribute or markup) for any entry with no rating_confidence field', pnConfidenceBadge({})===""]);
  out.push(['pnTierClass/pnTierLabel/pnNumOrDash still degrade cleanly for a genuinely unscored entry (defensive fallback stays correct even though no live NVMe row needs it anymore)', (function(){const fake={brand:'Unknown',model:'Placeholder 1TB',drive_type:'NVMe SSD'};const html=renderCatalogMeta('STORAGE',fake,null);return pnTierClass(null)==='pn-tier-unrated'&&pnTierClass('EPIC')==='pn-tier-epic'&&pnTierLabel(null)==='UNRATED'&&pnTierLabel('LEGENDARY')==='LEGENDARY'&&pnNumOrDash(null)==='—'&&pnNumOrDash(0)===0&&!/undefined|NaN/.test(html)&&html.includes('UNRATED')})()]);
  const draft=newRigDraft('PC601 RATED TEST');draft.slots.STORAGE={kind:'PLANNED',catalogType:'STORAGE',label:'SK hynix PC601 512GB',cost:0,originalPrice:0,currency:draft.currency};
  const slotHtml=renderRigSlotRow('STORAGE',draft);
  out.push(['the rated PC601 512GB entry renders cleanly inside the live RIG ASSEMBLY slot dropdown with its real score (no crash, no literal undefined/null)', typeof slotHtml==='string'&&!/undefined|NaN/.test(slotHtml)]);

  const coveragePanel = renderCatalogCoveragePanel();
  out.push(['Catalog Coverage panel reports the real live catalog sizes once HardwareCatalog is ready, not placeholders', coveragePanel.includes('Catalog Coverage') && coveragePanel.includes(String(HardwareCatalog.cpus.length)) && coveragePanel.includes(String(HardwareCatalog.gpus.length)) && coveragePanel.includes(String(HardwareCatalog.storage.length)) && coveragePanel.includes(String(HardwareCatalog.nvmeRegistryMeta.aliasCount)) && !/undefined|NaN/.test(coveragePanel)]);
  out.push(['Catalog Coverage panel degrades to a loading row instead of misleading zero counts while the catalog is still loading', (function(){const prev=HardwareCatalog.status;HardwareCatalog.status='loading';const html=renderCatalogCoveragePanel();HardwareCatalog.status=prev;return html.includes('Loading Hardware Foundation')&&!html.includes('Recognized')&&!html.includes('Mapped')})()]);
  const backupHtml = renderBackup();
  out.push(['the Backup/Archive page embeds the Catalog Coverage panel alongside the user\\'s own ledger stats', backupHtml.includes('Catalog Coverage') && backupHtml.includes('Current Ledger')]);

  return out;
})()`);

let failures=0;
for(const [name, ok] of results){
  console.log((ok ? 'PASS' : 'FAIL') + ' - ' + name);
  if(!ok) failures++;
}
console.log('\n'+(failures===0?'ALL PASSED':failures+' FAILED')+' ('+results.length+' assertions)');
process.exit(failures===0?0:1);
