"use strict";

/*
  PROFITNODE realized profit cash-pool model v1

  Doctrine:
  REALIZED PROFIT is the shop's available flip cash generated by operations.
  Money spent on inventory leaves the pool immediately.
  Completed sales add their received cash back to the pool.
  This keeps component quality/value separate from cashflow accounting and
  prevents unsold inventory purchases from pretending they never happened.
*/
(function installRealizedProfitCashflowV1(){
  if (typeof dashboardStats !== "function" || dashboardStats.__pnCashflowV1) return;

  const baseDashboardStats = dashboardStats;

  function completedSales(){
    return Store.all("sales").filter(sale =>
      typeof saleIsCompleted !== "function" || saleIsCompleted(sale)
    );
  }

  function inventoryCashSpent(currency){
    return Store.all("inventory").reduce((sum,item)=>{
      return sum + convert(Number(item.purchasePrice)||0,item.currency||currency,currency);
    },0);
  }

  function repairCashSpent(currency){
    return Store.all("repairs").reduce((sum,repair)=>{
      return sum + convert(Number(repair.cost)||0,repair.currency||currency,currency);
    },0);
  }

  function projectDirectCosts(currency){
    return Store.all("projects").reduce((sum,project)=>{
      return sum + convert(Number(project.additionalCosts)||0,project.currency||currency,currency);
    },0);
  }

  function standaloneSaleCosts(currency){
    return completedSales().reduce((sum,sale)=>{
      // Project-linked sale additional costs are already represented by project.additionalCosts.
      if (sale.projectId) return sum;
      return sum + convert(Number(sale.additionalCosts)||0,sale.currency||currency,currency);
    },0);
  }

  function realizedCashPool(currency){
    const revenue = completedSales().reduce((sum,sale)=>{
      return sum + convert(Number(sale.buyerPrice)||0,sale.currency||currency,currency);
    },0);

    const spend = inventoryCashSpent(currency)
      + repairCashSpent(currency)
      + projectDirectCosts(currency)
      + standaloneSaleCosts(currency);

    return revenue - spend;
  }

  const wrappedDashboardStats = function(currency){
    const out = baseDashboardStats(currency);
    out.realizedProfit = realizedCashPool(currency);
    out.realizedProfitModel = "CASH_POOL_V1";
    out.realizedRevenue = completedSales().reduce((sum,sale)=>
      sum + convert(Number(sale.buyerPrice)||0,sale.currency||currency,currency),0
    );
    out.realizedCashSpent = out.realizedRevenue - out.realizedProfit;
    return out;
  };

  wrappedDashboardStats.__pnCashflowV1 = true;
  dashboardStats = wrappedDashboardStats;

  globalThis.__PN_REALIZED_PROFIT_V1 = {
    model:"CASH_POOL_V1",
    doctrine:"completed sale cash received minus actual shop cash spent",
    inventoryPurchases:"deduct immediately",
    qualityIndependent:true
  };

  console.info("[PROFITNODE] REALIZED PROFIT CASH POOL V1 active.");
})();
