"use strict";

/* PERSONAL TREASURY is deliberately isolated from the shop/business ledgers. */
const PN_TREASURY_CORE_BALANCES=[
  {sourceKey:"PAYONEER",label:"Payoneer",currency:"USD"},
  {sourceKey:"PREPLY",label:"Preply",currency:"USD"},
  {sourceKey:"FIVERR",label:"Fiverr",currency:"USD"},
  {sourceKey:"CASH_RSD",label:"Cash (RSD)",currency:"RSD"},
  {sourceKey:"CASH_EUR",label:"Cash (EUR)",currency:"EUR"}
];
function pnTreasuryId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function pnTreasuryData(){const e=Store.load();return e.treasury=normalizeTreasury(e.treasury),e.treasury}
function pnTreasuryEur(e,t,a){const r=Math.max(0,Number(e)||0),n=a||pnTreasuryData().settings;return"USD"===t?r*(Number(n.usdToEur)||0):"RSD"===t?r*(Number(n.rsdToEur)||0):r}
function pnTreasuryCalculate(e){
  const t=normalizeTreasury(e),a=t.settings;
  const sum=(e,r)=>e.reduce((e,t)=>e+(r(t)?pnTreasuryEur(t.amount,t.currency,a):0),0);
  const liquid=sum(t.balances,e=>e.include!==!1),obligations=sum(t.obligations,e=>"PAID"!==e.status),pending=sum(t.pendingAssets,e=>!e.converted),income=sum(t.incomes,()=>!0),fortress=liquid-obligations;
  return{liquid,obligations,fortress,pending,income,afterPending:fortress+pending,afterSalary:fortress+pending+income}
}
function pnTreasuryMoney(e){return money(Number(e)||0,"EUR")}
function pnTreasuryConfidence(e){return String(e||"MEDIUM").toUpperCase()}
function pnTreasuryFloor(e,t){const a=Number(t)||0;return a<=0?{tone:"good",label:"NO FLOOR SET"}:e>=a?{tone:"good",label:"ABOVE FLOOR"}:e>=.85*a?{tone:"near",label:"NEAR FLOOR"}:{tone:"danger",label:"BELOW FLOOR"}}
function pnTreasuryDays(e){if(!e)return null;const t=new Date(todayISO()+"T00:00:00"),a=new Date(e+"T00:00:00");return isNaN(a)?null:Math.ceil((a-t)/864e5)}
function pnTreasuryNewestIncome(e){const t=e||[];return t.filter(e=>e.expectedDate).slice().sort((e,t)=>e.expectedDate.localeCompare(t.expectedDate))[0]||t[0]||null}
function pnTreasuryCoreDraft(e){
  const t=normalizeTreasury(e),a=t.balances.slice(),r=[];
  PN_TREASURY_CORE_BALANCES.forEach(e=>{let t=a.find(t=>t.sourceKey===e.sourceKey);t||(t=a.find(t=>String(t.label||"").trim().toLowerCase()===e.label.toLowerCase()));t?t.sourceKey=e.sourceKey:t={id:pnTreasuryId(),sourceKey:e.sourceKey,label:e.label,amount:0,currency:e.currency,include:!0,note:"",updatedAt:todayISO()};r.push(t)});
  const n=new Set(PN_TREASURY_CORE_BALANCES.map(e=>e.sourceKey)),s=new Set(PN_TREASURY_CORE_BALANCES.map(e=>e.label.toLowerCase()));t.balances=r.concat(a.filter(e=>!r.includes(e)&&!n.has(e.sourceKey)&&!s.has(String(e.label||"").trim().toLowerCase())));return t
}
function pnTreasuryClone(){return pnTreasuryCoreDraft(JSON.parse(JSON.stringify(pnTreasuryData())))}
function pnTreasuryCard(e,t,a,r){return'<div class="pn-treasury-card '+(r||'')+'"><span>'+e+'</span><strong>'+t+'</strong>'+(a?'<small>'+a+'</small>':'')+'</div>'}
function pnTreasuryOptions(e,t){return e.map(e=>'<option value="'+e+'"'+(e===t?' selected':'')+'>'+STATUS_LABEL(e)+'</option>').join("")}
function pnTreasuryInput(e,t,a,r){return'<label><span>'+e+'</span><input type="'+(r||"text")+'" value="'+escAttr(null==a?"":a)+'" data-treasury-path="'+t+'"'+("number"===r?' min="0" step="0.01" data-treasury-number':'')+'></label>'}
function pnTreasurySelect(e,t,a,r){return'<label><span>'+e+'</span><select data-treasury-path="'+t+'">'+pnTreasuryOptions(r,a)+'</select></label>'}
function pnTreasuryRemove(e,t){return'<button type="button" class="pn-treasury-remove" aria-label="Remove row" data-treasury-remove="'+e+'" data-treasury-index="'+t+'">×</button>'}
function pnTreasuryRows(e,t){
  if(!e.length)return'<div class="pn-treasury-empty">No entries yet.</div>';
  return e.map((e,a)=>{
    const r=t+"."+a+".";
    if("balances"===t)return'<div class="pn-treasury-row balance"'+(e.sourceKey?' data-treasury-core="'+escAttr(e.sourceKey)+'"':'')+'>'+(e.sourceKey?'<label><span>Source</span><input type="text" value="'+escAttr(e.label)+'" readonly></label>':pnTreasuryInput("Label",r+"label",e.label))+pnTreasuryInput("Amount",r+"amount",e.amount,"number")+pnTreasurySelect("Currency",r+"currency",e.currency,["EUR","USD","RSD"])+'<label class="pn-check"><span>Liquid</span><input type="checkbox" data-treasury-path="'+r+'include"'+(e.include!==!1?' checked':'')+'></label>'+pnTreasuryInput("Note",r+"note",e.note)+'<div class="pn-treasury-updated"><span>Updated</span><b>'+fmtDate(String(e.updatedAt||todayISO()).slice(0,10),"short")+'</b></div>'+(e.sourceKey?'<span class="pn-treasury-required" title="Core rebalance source">CORE</span>':pnTreasuryRemove(t,a))+"</div>";
    if("obligations"===t)return'<div class="pn-treasury-row obligation">'+pnTreasuryInput("Obligation",r+"name",e.name)+pnTreasuryInput("Amount",r+"amount",e.amount,"number")+pnTreasurySelect("Currency",r+"currency",e.currency,["EUR","USD","RSD"])+pnTreasurySelect("Status",r+"status",e.status,["PENDING","PAID"])+pnTreasuryInput("Category",r+"category",e.category)+pnTreasuryInput("Due",r+"dueDate",e.dueDate,"date")+'<label class="pn-check"><span>Recurring</span><input type="checkbox" data-treasury-path="'+r+'recurring"'+(e.recurring?' checked':'')+'></label>'+pnTreasuryInput("Note",r+"note",e.note)+pnTreasuryRemove(t,a)+"</div>";
    if("pendingAssets"===t)return'<div class="pn-treasury-row pending">'+pnTreasuryInput("Asset / income",r+"name",e.name)+pnTreasuryInput("Expected",r+"amount",e.amount,"number")+pnTreasurySelect("Currency",r+"currency",e.currency,["EUR","USD","RSD"])+pnTreasurySelect("Type",r+"type",e.type,["HARDWARE_SALE","PENDING_INCOME","SIDE_JOB","OTHER"])+pnTreasurySelect("Confidence",r+"confidence",e.confidence,["LOW","MEDIUM","HIGH","GUARANTEED"])+pnTreasuryInput("Expected date",r+"expectedDate",e.expectedDate,"date")+'<label class="pn-check"><span>Converted</span><input type="checkbox" data-treasury-path="'+r+'converted"'+(e.converted?' checked':'')+'></label>'+pnTreasuryInput("Note",r+"note",e.note)+pnTreasuryRemove(t,a)+"</div>";
    return'<div class="pn-treasury-row income">'+pnTreasuryInput("Income source",r+"source",e.source)+pnTreasuryInput("Expected",r+"amount",e.amount,"number")+pnTreasurySelect("Currency",r+"currency",e.currency,["EUR","USD","RSD"])+pnTreasuryInput("Expected date",r+"expectedDate",e.expectedDate,"date")+pnTreasurySelect("Confidence",r+"confidence",e.confidence,["LOW","MEDIUM","HIGH","GUARANTEED"])+pnTreasuryInput("Note",r+"note",e.note)+'<label class="pn-check"><span>Recurring</span><input type="checkbox" data-treasury-path="'+r+'recurring"'+(e.recurring?' checked':'')+'></label>'+pnTreasuryRemove(t,a)+"</div>"
  }).join("")
}
function pnTreasurySection(e,t,a){return'<section class="pn-treasury-edit-section"><div class="pn-treasury-edit-head"><div><h3>'+e+'</h3><p>'+a+'</p></div><button type="button" class="btn btn-sm" data-treasury-add="'+t+'">+ ADD</button></div>'+pnTreasuryRows(state.treasuryDraft[t],t)+"</section>"}
function pnTreasuryEditor(){const e=state.treasuryDraft,t=e.settings;return'<div class="panel pn-treasury-editor"><div class="panel-head"><h2>New Rebalance</h2><div><button type="button" class="btn" data-treasury-cancel>CANCEL</button> <button type="button" class="btn btn-primary" data-treasury-save>SAVE REBALANCE</button></div></div><div class="panel-body"><div class="pn-treasury-settings">'+pnTreasuryInput("USD → EUR",'settings.usdToEur',t.usdToEur,"number")+pnTreasuryInput("RSD → EUR",'settings.rsdToEur',t.rsdToEur,"number")+pnTreasuryInput("Fortress floor (EUR)",'settings.fortressFloor',t.fortressFloor,"number")+pnTreasurySelect("Snapshot label","snapshotLabel",state.treasurySnapshotLabel||"MID_MONTH",["POST_SALARY","POST_SEXODIA","PRE_MOVE","POST_MOVE","MID_MONTH","FINAL_STRETCH","CUSTOM"])+pnTreasuryInput("Snapshot note","snapshotNote",state.treasurySnapshotNote||"")+"</div><p class=\"pn-treasury-fx-note\">Planning rates only · primary display EUR · rates are never fetched live.</p>"+pnTreasurySection("Core balances","balances","Payoneer, Preply, Fiverr and both cash currencies are always ready for every rebalance. Add custom sources only when needed.")+pnTreasurySection("Obligations","obligations","Only pending obligations reduce the fortress.")+pnTreasurySection("Pending / saleable assets","pendingAssets","Potential recovery only; converted rows stop counting here.")+pnTreasurySection("Salary / income projection","incomes","Projected income never enters Current Treasury.")+'<div class="pn-treasury-savebar"><button type="button" class="btn btn-primary" data-treasury-save>SAVE REBALANCE</button></div></div></div>'}
function pnTreasuryTrend(e){
  const t=e.slice(-12);if(t.length<2)return'<div class="pn-treasury-empty">Two snapshots are needed to draw the trend.</div>';
  const a=t.flatMap(e=>[Number(e.liquid)||0,Number(e.fortress)||0]),r=Math.min.apply(null,a),n=Math.max.apply(null,a),s=n-r||1,l=e=>t.map((t,n)=>{const a=12+n*(476/(t.length-1)),l=104-((Number(t[e])||0)-r)/s*82;return a.toFixed(1)+","+l.toFixed(1)}).join(" ");
  return'<div class="pn-treasury-trend"><svg viewBox="0 0 500 118" role="img" aria-label="Treasury and fortress trend"><polyline class="liquid" points="'+l("liquid")+'"></polyline><polyline class="fortress" points="'+l("fortress")+'"></polyline></svg><div><span class="liquid">LIQUID</span><span class="fortress">FORTRESS</span><small>'+escHtml(t[0].date||"")+" → "+escHtml(t[t.length-1].date||"")+"</small></div></div>"}
function pnTreasuryCompare(e){if(e.length<2)return"";const t=state.treasuryCompareA||e[e.length-2].id,a=state.treasuryCompareB||e[e.length-1].id,r=e.find(e=>e.id===t)||e[e.length-2],n=e.find(e=>e.id===a)||e[e.length-1],s=(t,a)=>e.map(e=>'<option value="'+e.id+'"'+(e.id===a?' selected':'')+'>'+escHtml(e.date+" · "+e.label)+'</option>').join("");return'<div class="pn-treasury-compare"><label><span>FROM</span><select data-treasury-compare="a">'+s(e,r.id)+'</select></label><label><span>TO</span><select data-treasury-compare="b">'+s(e,n.id)+'</select></label><div><span>LIQUID Δ</span><strong>'+pnTreasuryMoney(n.liquid-r.liquid)+'</strong></div><div><span>FORTRESS Δ</span><strong>'+pnTreasuryMoney(n.fortress-r.fortress)+'</strong></div></div>'}
function pnTreasuryHistory(e){const t=e.snapshots||[],a=t.slice(-1)[0],r=t.slice(-2,-1)[0],n=a&&r?a.liquid-r.liquid:null;return'<details class="panel pn-treasury-history"><summary><b>REBALANCE HISTORY</b><span>'+t.length+' snapshot'+(1===t.length?'':'s')+(null===n?'':' · '+(n<0?'DAMAGE ':'CHANGE ')+pnTreasuryMoney(n))+'</span></summary><div class="panel-body">'+pnTreasuryTrend(t)+pnTreasuryCompare(t)+'<div class="pn-treasury-history-list">'+t.slice().reverse().map(e=>'<div><span>'+escHtml(e.date+" · "+e.label)+'</span><b>'+pnTreasuryMoney(e.liquid)+'</b><em>Fortress '+pnTreasuryMoney(e.fortress)+'</em></div>').join("")+'</div></div></details>'}
function pnTreasuryFlowMeta(f){const m={SALE:"Sale revenue",ACQUISITION:"deal"===f.refType?"Deal purchase":"Inventory purchase",SHIPPING_IN:"Incoming shipping",SHIPPING_OUT:"Outgoing shipping"};return m[f.kind]||f.kind}
function pnTreasuryActivityRows(e){
  const rows=(e.flows||[]).slice().sort((a,b)=>String(b.updatedAt||b.createdAt||"").localeCompare(String(a.updatedAt||a.createdAt||""))).slice(0,8);
  if(!rows.length)return'<div class="pn-treasury-empty">No pool activity yet — sales, purchases and shipping will post here automatically as they happen.</div>';
  return rows.map(f=>{const pos=(Number(f.signedDelta)||0)>=0,meta=pnTreasuryFlowMeta(f);return'<div class="pn-treasury-activity-row '+(pos?"is-in":"is-out")+'"><span>'+escHtml(meta)+(f.note&&f.note!==meta?' <em>'+escHtml(f.note)+"</em>":"")+'</span><b>'+(pos?"+":"−")+money(Math.abs(Number(f.amount)||0),f.currency||"RSD")+'</b><small>'+fmtDate(String(f.updatedAt||f.createdAt||"").slice(0,10),"short")+'</small></div>'}).join("")
}
function pnTreasuryActivityPanel(e){const n=(e.flows||[]).length;return'<section class="panel pn-treasury-activity"><div class="panel-head"><h2>Pool Activity</h2><span>'+n+" recorded flow"+(1===n?"":"s")+'</span></div><div class="panel-body">'+pnTreasuryActivityRows(e)+"</div></section>"}
function renderTreasury(){
  const e=pnTreasuryData(),t=pnTreasuryCalculate(e),a=pnTreasuryFloor(t.fortress,e.settings.fortressFloor),r=pnTreasuryNewestIncome(e.incomes),n=r?pnTreasuryDays(r.expectedDate):null,s=r?(r.source||"Projected income")+" · "+pnTreasuryConfidence(r.confidence)+(null===n?" · DATE NOT SET":n<0?" · OVERDUE":0===n?" · TODAY":" · "+n+" DAYS"):"No income projection";
  const cards=pnTreasuryCard("Post-Obligation Fortress",pnTreasuryMoney(t.fortress),"Floor "+pnTreasuryMoney(e.settings.fortressFloor)+" · "+a.label,"is-fortress "+a.tone)+pnTreasuryCard("Current Treasury",pnTreasuryMoney(t.liquid),e.balances.filter(e=>e.include!==!1).length+" included balance(s)")+pnTreasuryCard("Remaining Obligations",pnTreasuryMoney(t.obligations),e.obligations.filter(e=>"PAID"!==e.status).length+" pending","is-obligation")+pnTreasuryCard("Pending Assets",pnTreasuryMoney(t.pending),e.pendingAssets.filter(e=>!e.converted).length+" unconverted")+pnTreasuryCard("Projected After Pending",pnTreasuryMoney(t.afterPending),"Fortress + pending")+pnTreasuryCard("Next Salary / Income",pnTreasuryMoney(t.income),s)+pnTreasuryCard("Projected After Salary",pnTreasuryMoney(t.afterSalary),"Pending + projected income");
  return pageHeader("Personal Treasury","Private strategic position · entirely separate from shop finance",'<button type="button" class="btn btn-primary" data-treasury-new>NEW REBALANCE</button>')+'<div class="content pn-treasury"><div class="pn-treasury-strip"><span>PLANNING FX</span><b>USD '+Number(e.settings.usdToEur).toFixed(4)+' EUR</b><b>RSD '+Number(e.settings.rsdToEur).toFixed(5)+' EUR</b><small>Rates set manually · never fetched live</small></div><div class="pn-treasury-grid">'+cards+'</div>'+(state.treasuryDraft?pnTreasuryEditor():'<div class="pn-treasury-prompt"><b>POSITION READY</b><span>Use NEW REBALANCE to update balances, obligations, pending recovery, income and create a dated snapshot.</span></div>')+pnTreasuryActivityPanel(e)+pnTreasuryHistory(e)+'</div>'
}

ROUTES.splice(1,0,{key:"treasury",label:"TREASURY",nix:"02",render:renderTreasury});

(function(){
  const style=document.createElement("style");style.textContent=`
  .pn-treasury{padding-top:14px}.pn-treasury-strip{display:flex;align-items:center;gap:14px;padding:9px 13px;border:1px solid var(--border);background:var(--panel);font-family:var(--mono);font-size:11px}.pn-treasury-strip span{color:var(--text-muted);text-transform:uppercase;letter-spacing:.08em}.pn-treasury-strip b{font-size:13px;color:var(--text);font-variant-numeric:tabular-nums}.pn-treasury-strip small{margin-left:auto;color:var(--text-muted)}
  .pn-treasury-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:10px 0}.pn-treasury-card{min-height:86px;padding:12px 13px;border:1px solid var(--border);border-left:3px solid var(--border-strong);background:var(--panel);display:flex;flex-direction:column;justify-content:center}.pn-treasury-card span,.pn-treasury-card small{font-family:var(--mono);font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em}.pn-treasury-card strong{font:800 21px/1.2 var(--mono);color:var(--text);margin:5px 0;font-variant-numeric:tabular-nums}.pn-treasury-card.is-obligation{border-left-color:var(--sem-warning-dim)}.pn-treasury-card.is-obligation strong{color:var(--sem-warning)}.pn-treasury-card.is-fortress{grid-column:1/-1;min-height:112px;padding:20px 24px;background:var(--panel-2)}.pn-treasury-card.is-fortress strong{font-size:36px;margin:8px 0}.pn-treasury-card.is-fortress.good{border-left-color:var(--green)}.pn-treasury-card.is-fortress.near{border-left-color:var(--sem-warning)}.pn-treasury-card.is-fortress.danger{border-left-color:var(--red)}
  .pn-treasury-prompt{display:flex;gap:14px;align-items:center;padding:13px;border:1px dashed var(--border);font-family:var(--mono);font-size:11px;color:var(--text-muted)}.pn-treasury-prompt b{color:var(--sem-active)}
  .pn-treasury-activity{margin-top:10px}.pn-treasury-activity-row{display:flex;align-items:center;gap:10px;padding:8px 14px;border-top:1px solid var(--border);font:11px var(--mono)}.pn-treasury-activity-row:first-child{border-top:0}.pn-treasury-activity-row span{flex:1;color:var(--text)}.pn-treasury-activity-row span em{font-style:normal;color:var(--text-muted);margin-left:6px}.pn-treasury-activity-row b{font-variant-numeric:tabular-nums;min-width:90px;text-align:right}.pn-treasury-activity-row.is-in b{color:var(--sem-positive)}.pn-treasury-activity-row.is-out b{color:var(--sem-fail)}.pn-treasury-activity-row small{color:var(--text-muted);width:64px;text-align:right;flex:none}
  .pn-treasury-editor{margin-top:10px}.pn-treasury-settings{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.pn-treasury-editor label,.pn-treasury-compare label{display:flex;flex-direction:column;gap:5px}.pn-treasury-editor label>span,.pn-treasury-compare label>span{font-family:var(--mono);font-size:9px;color:var(--text-muted);text-transform:uppercase}.pn-treasury-editor input,.pn-treasury-editor select,.pn-treasury-compare select{width:100%;min-width:0;height:33px}.pn-treasury-fx-note{margin:7px 0 0;color:var(--text-muted);font:10px var(--mono)}
  .pn-treasury-edit-section{margin-top:13px;padding-top:11px;border-top:1px solid var(--border)}.pn-treasury-edit-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:7px}.pn-treasury-edit-head h3{margin:0;color:var(--text);font:800 12px var(--display);text-transform:uppercase}.pn-treasury-edit-head p{margin:3px 0 0;color:var(--text-muted);font:10px var(--mono)}.pn-treasury-row{display:grid;gap:7px;align-items:end;padding:7px 0;border-top:1px solid color-mix(in srgb,var(--border) 55%,transparent)}.pn-treasury-row.balance{grid-template-columns:1fr .55fr .5fr .4fr 1fr .55fr 40px}.pn-treasury-row.obligation{grid-template-columns:1fr .5fr .45fr .55fr .65fr .65fr .4fr .85fr 28px}.pn-treasury-row.pending{grid-template-columns:1fr .5fr .45fr .7fr .65fr .65fr .45fr .85fr 28px}.pn-treasury-row.income{grid-template-columns:1.1fr .6fr .5fr .8fr .7fr 1fr .5fr 28px}.pn-check{align-items:flex-start}.pn-check input{width:18px;height:18px;margin:7px 0}.pn-treasury-updated{height:33px;display:flex;flex-direction:column;justify-content:center}.pn-treasury-updated span{font:9px var(--mono);color:var(--text-muted);text-transform:uppercase}.pn-treasury-updated b{font:10px var(--mono);color:var(--text)}.pn-treasury-required{height:33px;display:flex;align-items:center;justify-content:center;color:var(--sem-active);font:800 9px var(--mono);border:1px solid var(--sem-active)}.pn-treasury-remove{height:33px;border:1px solid var(--red-dim);background:transparent;color:var(--red);cursor:pointer;font-size:18px}.pn-treasury-empty{padding:13px;border:1px dashed var(--border);color:var(--text-muted);font:10px var(--mono)}.pn-treasury-savebar{text-align:right;margin-top:13px}
  .pn-treasury-history{margin-top:10px}.pn-treasury-history>summary{display:flex;justify-content:space-between;cursor:pointer;padding:12px 14px;color:var(--text);font:11px var(--mono);list-style:none}.pn-treasury-history>summary span{color:var(--text-muted)}.pn-treasury-history>summary::-webkit-details-marker{display:none}.pn-treasury-trend svg{display:block;width:100%;height:118px;border:1px solid var(--border);background:var(--panel)}.pn-treasury-trend polyline{fill:none;stroke-width:2}.pn-treasury-trend polyline.liquid{stroke:var(--sem-active)}.pn-treasury-trend polyline.fortress{stroke:var(--green)}.pn-treasury-trend>div{display:flex;gap:12px;margin-top:5px;font:9px var(--mono)}.pn-treasury-trend span.liquid{color:var(--sem-active)}.pn-treasury-trend span.fortress{color:var(--green)}.pn-treasury-trend small{margin-left:auto;color:var(--text-muted)}.pn-treasury-compare{display:grid;grid-template-columns:1fr 1fr .7fr .7fr;gap:8px;margin:12px 0}.pn-treasury-compare>div{display:flex;flex-direction:column;justify-content:center;padding:6px 10px;border:1px solid var(--border)}.pn-treasury-compare>div span{font:9px var(--mono);color:var(--text-muted)}.pn-treasury-compare>div strong{font:13px var(--mono)}.pn-treasury-history-list>div{display:grid;grid-template-columns:1fr .5fr .7fr;gap:10px;padding:7px;border-top:1px solid var(--border);font:10px var(--mono)}.pn-treasury-history-list em{font-style:normal;color:var(--text-muted)}
  @media(max-width:1180px){.pn-treasury-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pn-treasury-settings{grid-template-columns:repeat(2,minmax(0,1fr))}.pn-treasury-row{grid-template-columns:repeat(2,minmax(0,1fr))!important}.pn-treasury-remove{grid-column:2}.pn-treasury-strip small{display:none}}@media(max-width:760px){.pn-treasury-grid{grid-template-columns:1fr}.pn-treasury-strip{flex-wrap:wrap}.pn-treasury-settings,.pn-treasury-compare{grid-template-columns:1fr}.pn-treasury-history-list>div{grid-template-columns:1fr}.pn-treasury-row{grid-template-columns:1fr!important}.pn-treasury-remove{grid-column:1}}
  `;document.head.appendChild(style);
  document.addEventListener("DOMContentLoaded",()=>{
    const root=document.getElementById("root");if(!root)return;
    const update=e=>{const el=e.target.closest&&e.target.closest("[data-treasury-path]");if(!el||!state.treasuryDraft)return;const path=el.dataset.treasuryPath,value="checkbox"===el.type?el.checked:el.hasAttribute("data-treasury-number")?Math.max(0,Number(el.value)||0):el.value;if("snapshotLabel"===path)state.treasurySnapshotLabel=value;else if("snapshotNote"===path)state.treasurySnapshotNote=value;else setDeepOn(state.treasuryDraft,path,value)};
    root.addEventListener("input",update);root.addEventListener("change",e=>{update(e);const c=e.target.closest&&e.target.closest("[data-treasury-compare]");if(c){"a"===c.dataset.treasuryCompare?state.treasuryCompareA=c.value:state.treasuryCompareB=c.value;render()}});
    root.addEventListener("click",e=>{
      const fresh=e.target.closest("[data-treasury-new]");if(fresh){state.treasuryDraft=pnTreasuryClone();state.treasurySnapshotLabel="MID_MONTH";state.treasurySnapshotNote="";render();return}
      if(e.target.closest("[data-treasury-cancel]")){state.treasuryDraft=null;render();return}
      const add=e.target.closest("[data-treasury-add]");if(add&&state.treasuryDraft){const k=add.dataset.treasuryAdd,d={balances:{id:pnTreasuryId(),label:"",amount:0,currency:"EUR",include:!0,note:"",updatedAt:todayISO()},obligations:{id:pnTreasuryId(),name:"",amount:0,currency:"EUR",status:"PENDING",category:"",dueDate:"",recurring:!1,note:""},pendingAssets:{id:pnTreasuryId(),name:"",amount:0,currency:"EUR",type:"HARDWARE_SALE",confidence:"MEDIUM",expectedDate:"",converted:!1,note:""},incomes:{id:pnTreasuryId(),source:"",amount:0,currency:"EUR",expectedDate:"",confidence:"HIGH",recurring:!1,note:""}};state.treasuryDraft[k].push(d[k]);render();return}
      const rem=e.target.closest("[data-treasury-remove]");if(rem&&state.treasuryDraft){state.treasuryDraft[rem.dataset.treasuryRemove].splice(Number(rem.dataset.treasuryIndex),1);render();return}
      if(e.target.closest("[data-treasury-save]")&&state.treasuryDraft){const ledger=Store.load(),saved=normalizeTreasury(state.treasuryDraft),calc=pnTreasuryCalculate(saved),stamp=nowISO(),label=(state.treasurySnapshotLabel||"MID_MONTH").replace(/_/g," ");saved.balances.forEach(e=>e.updatedAt=stamp);saved.snapshots.push({id:pnTreasuryId(),timestamp:stamp,date:todayISO(),label,note:state.treasurySnapshotNote||"",liquid:calc.liquid,fortress:calc.fortress,pending:calc.pending,projectedSalary:calc.income,afterPending:calc.afterPending,afterSalary:calc.afterSalary});ledger.treasury=saved;Store.persist();state.treasuryDraft=null;state.treasurySnapshotNote="";render();return}
    })
  })
})();
